### ISSUE TITLE
HTML display error in 6.0.1

### ISSUE THREAD

**Issue by Corwin7** [phoronix-test-suite/phoronix-test-suite#100]
![2015-12-29_phoronix_6 0 1_display_buy](https://cloud.githubusercontent.com/assets/2396987/12043153/eb7ce40a-ae36-11e5-9db3-cf8179d17a9a.png)

**Comment by michaellarabel** [comment]
It's not an HTML error per se and am aware of an odd bug causing this issue. If you're able to, do you still have the raw composite.xml results for this run? Just to confirm the output, thanks.

**Comment by michaellarabel** [comment]
This issue should have been fixed a while ago, but just noticed the ticket wasn't closed. If it still happens for you, please reopen.
