### ISSUE TITLE
This product has no real instructions anymore...

### ISSUE THREAD

**Issue by derekdickerson** [phoronix-test-suite/phoronix-test-suite#103]
I test arm boards and have found this completely unusable now.

I am wanting to run just one test at a time and I get this
I type this: phoronix-test-suite pts/compress-gzip

I get this shit....
WEB / GUI SUPPORT

   gui
   start-remote-gui-server
   start-ws-server

MODULES

   list-modules
   module-info [Phoronix Test Suite Module]
   module-setup [Phoronix Test Suite Module]
   test-module [Phoronix Test Suite Module]

PHOROMATIC

   start-phoromatic-server

**Comment by michaellarabel** [comment]
Yes, that output is the command helper when typing an invalid command. It's always been e.g. phoronix-test-suite benchmark pts/compress-gzip
