### ISSUE TITLE
Force line graph fails

### ISSUE THREAD

**Issue by mjlyon** [phoronix-test-suite/phoronix-test-suite#106]
6.2.0m2

When selecting 'force line graph' as a part of the results display, the following error is displayed:

core/objects/pts_Graph/pts_graph_lines.php:259 min(): When only one parameter is given, it must be an array in /usr/share/phoronix-test-suite/pts-core/objects/pts_Graph/pts_graph_lines.php:257 max(): When only one parameter is given, it must be an array in /usr/share/phoronix-test-suite/pts-core/objects/pts_Graph/pts_graph_lines.php:258 array_sum() expects parameter 1 to be array, string given in /usr/share/phoronix-test-suite/pts-core/objects/pts_Graph/pts_graph_lines.php:259 min(): When only one parameter is given, it must be an array in /usr/share/phoronix-test-suite/pts-core/objects/pts_Graph/pts_graph_lines.php:257 max(): When only one parameter is given, it must be an array in /usr/share/phoronix-test-suite/pts-core/objects/pts_Graph/pts_graph_lines.php:258 array_sum() expects parameter 1 to be array, string given in /usr/share/phoronix-test-suite/pts-core/objects/pts_Graph/pts_graph_lines.php:259 min(): When only one parameter is given, it must be an array in /usr/share/phoronix-test-suite/pts-core/objects/pts_Graph/pts_graph_lines.php:257 max(): When only one parameter is given, it must be an array in /usr/share/phoronix-test-suite/pts-core/objects/pts_Graph/pts_graph_lines.php:258 array_sum() expects parameter 1 to be array, string given in /usr/share/phoronix-test-suite/pts-core/objects/pts_Graph/pts_graph_lines.php:259 min(): When only one parameter is given, it must be an array in /usr/share/phoronix-test-suite/pts-core/objects/pts_Graph/pts_graph_lines.php:257 max(): When only one parameter is given, it must be an array in /usr/share/phoronix-test-suite/pts-core/objects/pts_Graph/pts_graph_lines.php:258 array_sum() expects parameter 1 to be array, string given in /usr/share/phoronix-test-suite/pts-core/objects/pts_Graph/pts_graph_lines.php:259 min(): When only one parameter is given, it must be an array in /usr/share/phoronix-test-suite/pts-
<img width="209" alt="screen shot 2016-01-27 at 8 37 53 am" src="https://cloud.githubusercontent.com/assets/786306/12615032/4a572098-c4d1-11e5-9dee-ef38bd8c0ae3.png">

**Comment by michaellarabel** [comment]
Can you try latest Git? There's been a few other improvements in graphing recently as well. If it still causes problems for you, can you send over the XML for that result file? From that same phoromatic page you should be able to have a 'download XML' link on the right hand side.
