### ISSUE TITLE
Multiple results in 'compare' view result in unreadable numbers in bar graph

### ISSUE THREAD

**Issue by mjlyon** [phoronix-test-suite/phoronix-test-suite#107]
<img width="733" alt="screen shot 2016-01-27 at 8 39 07 am" src="https://cloud.githubusercontent.com/assets/786306/12615063/7eeefefc-c4d1-11e5-95b9-cb75c10368b4.png">

**Comment by michaellarabel** [comment]
Hi @mjlyon can you try latest PTS 6.2.0m4 / Git? Using the same result identifier multiple times in the same result file isn't an ideal use-case, but past M2 there should be a fix for handling cases like this.
