### ISSUE TITLE
php5-cli not availible in Ubuntu 16.04

### ISSUE THREAD

**Issue by Halamix2** [phoronix-test-suite/phoronix-test-suite#118]
I am unable to run e.g "phoronix-test-suite benchmark smallpt" with php7.0-cli only installed since php5-cli was removed in Ubu 16.04 and replaced by php7.0-cli. (Xubuntu 16.04 64bit)

**Comment by michaellarabel** [comment]
You need php-cli and php-xml installed on Ubuntu 16.04. With Ubuntu 16.04's PHP7 packaging, they split XML support into its own php-xml package. The Phoronix Test Suite has long supported PHP7.
