### ISSUE TITLE
Phoronix Test Suite Windows Installation Guide

### ISSUE THREAD

**Issue by qubodup** [phoronix-test-suite/phoronix-test-suite#120]
Hello,

While Windows support is in the works, please provide foolsafe installation instructions for Windows users who don't know what PHP or a .bat file is.

PHP Windows install guides like for example https://www.sitepoint.com/how-to-install-php-on-windows/ could be used as a reference. Hopefully Phoronix doesn't require all those steps though.

**Comment by michaellarabel** [comment]
Simply installing the Windows PHP binaries from windows.php.net is all that's needed. The Windows PTS support is provided as-is with unfortunately having no extra resources to dedicate towards it until there is any sponsorship or enterprise support agreements around that platform target.

**Comment by alexandrul** [comment]
For the record, `php-7.2.4-nts-Win32-VC15-x64.zip` seems to be good enough.

**Comment by michaellarabel** [comment]
There are no known (at least any significant bugs) remaining for Phoronix Test Suite 8.0 on Windows. For those looking to run PTS on Windows, the starter spot is: https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/documentation/phoronix-test-suite-window.md
