### ISSUE TITLE
about the pts/network-loopback-1.0.* error

### ISSUE THREAD

**Issue by lining-github** [phoronix-test-suite/phoronix-test-suite#127]
hello~
    I use the reference pressure measurement tools recently, I found that when the test network error. I have been using the "pts/network-loopback-1.0.1" in the script, he used the NC command to test. The command "NC -d -l > /dev/null & 9999". But this command should be -d.Nc commands to parameter error specify a numeric value, otherwise he will not execute correctly. My system is centos7.

**Comment by michaellarabel** [comment]
pts/network-loopback-1.0.2 should fix this issue.
