### ISSUE TITLE
Provide an official Docker container

### ISSUE THREAD

**Issue by nanawel** [phoronix-test-suite/phoronix-test-suite#134]
A lot of PTS containers already exist on the Docker hub but none of them is official nor up-to-date. It would really help to provide an official container for Docker.

**Comment by michaellarabel** [comment]
Is there a unofficial PTS Docker container you are currently using? I haven't made an 'official' one as while my personal usage of Docker is extremely limited, there are already a few out there, but if it's useful to more people I could look at making one of them official and keep it updated.

https://github.com/eea/eea.phoronix-test-suite and https://github.com/moul/docker-phoronix-test-suite appear to be two of the most popular right now.

**Comment by nanawel** [comment]
I'm currently trying to use [dperson/pts/](https://hub.docker.com/r/dperson/pts/) but I get a lot of failures when attempting to install the required packages for the tests which prevent them to run.

PTS uses a lot of additional packages that I don't want to keep after running the tests, so in this situation Docker and its really thin virtualisation layer seems the right way to go.

**Comment by snigel** [comment]
Having a docker container would also be a great way to test that phoronix-test-suite is actually pulling all required dependencies to compile the different tests.

**Comment by michaellarabel** [comment]
There is now an official Phoronix Test Suite Docker image available now: docker run -it phoronix/pts

Details: https://www.phoronix.com/scan.php?page=article&item=docker-phoronix-pts&num=1

It's still being revised but should be in good shape by PTS 8.2.0 shipping in a few weeks.
