### ISSUE TITLE
pts/mafft fails to compile on FreeBSD 11

### ISSUE THREAD

**Issue by snigel** [phoronix-test-suite/phoronix-test-suite#138]
Looking at the log I get error messages such as :
Make [file path] Missing dependency operator
Make [file path] Need an operator

It seems this can be solved by invoking gmake instead of make when compiling mafft.
The install.sh uses regular make.

**Comment by michaellarabel** [comment]
With pts/mafft-1.5.0 this issue should be resolved, at least I had no problems running it during some recent FreeBSD/TrueOS tests a while back.

http://openbenchmarking.org/test/pts/mafft
