### ISSUE TITLE
pts/tiobench fails to compile on FreeBSD 11

### ISSUE THREAD

**Issue by snigel** [phoronix-test-suite/phoronix-test-suite#139]
From the install-failed.log

gcc -o tiotest tiotest.o crc32.o -lpthread
tiotest.o: In function `initialize_test':
tiotest.c:(.text+0x1a4): undefined reference to `crc32'
tiotest.o: In function `do_read_test':
tiotest.c:(.text+0x20d8): undefined reference to `crc32'
tiotest.o: In function `do_random_read_test':
tiotest.c:(.text+0x23aa): undefined reference to `crc32'
collect2: error: ld returned 1 exit status
Makefile:37: recipe for target 'tiotest' failed
make: *** [tiotest] Error 1

**Comment by thesandbender** [comment]
The version of tiobench that PTS links against declares crc32 as inline in a non-standard way.  @mkuoppal has been maintaining a newer build of tiobench that fixes some of these issues and I submitted a [pull request](https://github.com/mkuoppal/tiobench/pull/7) that reverts back to inline method that works with gcc/clang.  You can get PTS to use it by downloading a zip of the fixed source and placing it in .phoronix-test-suite/installed-tests/pts/tiobench-1.2.0/tiobench-0.3.3.zip (you may have to repack so it expands into tiobench-0.33).

**Comment by michaellarabel** [comment]
This issue should be fixed by pts/tiobench-1.3.0 that now switches to the GitHub fork of tiobench with the fix as pointed out by @thesandbender rather than the original 0.3.3 build.

http://openbenchmarking.org/test/pts/tiobench
