### ISSUE TITLE
pts/sunflow test fails to produce result. Ubuntu 16.04 & FreeBSD 11

### ISSUE THREAD

**Issue by snigel** [phoronix-test-suite/phoronix-test-suite#140]
FreeBSD 11:
root@rpi2:/home/snigel# java -version
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-b14)
OpenJDK Zero VM (build 25.102-b14, interpreted mode)

Sunflow Rendering System 0.07.2:
    pts/sunflow-1.1.0
    Test 1 of 1
    Estimated Trial Run Count:    2
    Estimated Time To Completion: 2 Minutes (00:13 UTC)
        Started Run 1 @ 00:11:36
        The test run did not produce a result.
        Started Run 2 @ 00:55:59
        The test run did not produce a result.

    Test Results:

    Average: 0 Seconds
    This test failed to run properly.

Ubuntu 16.04:
root@ubmate:/home/snigel# java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK Zero VM (build 25.111-b14, interpreted mode)

Sunflow Rendering System 0.07.2:
    pts/sunflow-1.1.0
    Test 1 of 1
    Estimated Trial Run Count:    2
    Estimated Time To Completion: 2 Minutes
        Started Run 1 @ 01:06:15
        The test run did not produce a result.
        Started Run 2 @ 01:44:41
        The test run did not produce a result.

    Test Results:

    Average: 0 Seconds
    This test failed to run properly.

The following tests failed to properly run:

        - pts/sunflow-1.1.0: Global Illumination + Image Synthesis

**Comment by michaellarabel** [comment]
pts/sunflow-1.1.1 is now available.
