### ISSUE TITLE
pts/blake2 fails to run on Ubuntu 16.04 and FreeBSD 11

### ISSUE THREAD

**Issue by snigel** [phoronix-test-suite/phoronix-test-suite#141]
FreeBSD:
BLAKE2 20130131:
    pts/blake2-1.1.0
    Test 1 of 1
    Estimated Trial Run Count: 3
        Started Run 1 @ 06:38:42
        The test exited with a non-zero exit status.
        Started Run 2 @ 06:38:43
        The test exited with a non-zero exit status.
        Started Run 3 @ 06:38:44
        The test exited with a non-zero exit status.
        E: ./blake2: ./blake2s: not found

Ubuntu 16.04:
BLAKE2 20130131:
    pts/blake2-1.1.0
    Test 1 of 1
    Estimated Trial Run Count: 3
        Started Run 1 @ 07:39:17
        The test exited with a non-zero exit status.
        Started Run 2 @ 07:39:19
        The test exited with a non-zero exit status.
        Started Run 3 @ 07:39:21
        The test exited with a non-zero exit status.
        E: ./blake2: 3: ./blake2: ./blake2s: not found

**Comment by michaellarabel** [comment]
I haven't been able to reproduce these issues but there is now pts/blake2-1.2.0 test profile update regardless that does pull in the latest BLAKE2 upstream code that may help in your case.
