### ISSUE TITLE
PTS attempting cache of non-specified test-profiles

### ISSUE THREAD

**Issue by kkebb** [phoronix-test-suite/phoronix-test-suite#144]
Currently, when I attempt to install the test-profiles within my Docker image, it seems that for some reason PTS is searching for additional test-profiles (that I haven't specified and tries to cache their information) please see a sample of the installation logs:

Here are the tests I wish to install AND cache:

    To Install: pts/minion-1.4.0
    To Install: pts/network-loopback-1.0.1
    To Install: pts/scimark2-1.2.0
    To Install: pts/ramspeed-1.4.0
    To Install: pts/stream-1.3.1
    To Install: pts/cachebench-1.0.0
    To Install: pts/compress-gzip-1.1.0
    To Install: pts/apache-1.6.1
    To Install: pts/pgbench-1.5.2
    To Install: pts/compilebench-1.0.1
    To Install: pts/iozone-1.8.0
    To Install: pts/dbench-1.0.0
    To Install: pts/fs-mark-1.0.1
    To Install: pts/fio-1.8.2
    To Install: pts/tiobench-1.2.0
    To Install: pts/john-the-ripper-1.5.1
    To Install: pts/compress-pbzip2-1.5.0
    To Install: pts/compress-7zip-1.6.2
    To Install: pts/openssl-1.9.0
    To Install: pts/gcrypt-1.0.3
    To Install: pts/himeno-1.2.0
    To Install: pts/c-ray-1.1.0
    To Install: pts/povray-1.1.2
    To Install: pts/crafty-1.3.1
    To Install: pts/npb-1.2.2

    Determining File Requirements ..........................................
    Searching Download Caches ..............................................

    25 Tests To Install
        29 Files To Download [212MB]
        2506MB Of Disk Space Is Needed

    pts/minion-1.4.0:
        Test Installation 1 of 25
        1 File Needed [6.64 MB]
        Downloading: minion-0.15-src.tar.gz                         [6.64MB]
        Downloading ........................................................
        Installation Size: 55 MB
        Installing Test @ 02:13:20

    pts/network-loopback-1.0.1:
        Test Installation 2 of 25
        Installation Size: 1 MB
        Installing Test @ 02:15:07

    pts/scimark2-1.2.0:
        Test Installation 3 of 25
        1 File Needed [0.01 MB / 1 Minute]
        Downloading: scimark2_1c.zip                                [0.01MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 0.1 MB
        Installing Test @ 02:15:13
            The installer exited with a non-zero exit status.
            ERROR: g++: fatal error: no input files
            LOG: /var/lib/phoronix-test-suite/installed-tests/pts/scimark2-1.2.0/install-failed.log

    pts/ramspeed-1.4.0:
        Test Installation 4 of 25
        1 File Needed [0.08 MB / 1 Minute]
        Downloading: ramsmp-3.5.0.tar.gz                            [0.08MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 0.72 MB
        Installing Test @ 02:15:25

    pts/stream-1.3.1:
        Test Installation 5 of 25
        1 File Needed [0.01 MB / 1 Minute]
        Downloading: stream-2013-01-17.tar.bz2                      [0.01MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 0.1 MB
        Installing Test @ 02:15:32

    pts/cachebench-1.0.0:
        Test Installation 6 of 25
        1 File Needed [0.17 MB / 1 Minute]
        Downloading: llcbench.tar.gz                                [0.17MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 0.5 MB
        Installing Test @ 02:15:38
            The installer exited with a non-zero exit status.
            LOG: /var/lib/phoronix-test-suite/installed-tests/pts/cachebench-1.0.0/install-failed.log

    pts/compress-gzip-1.1.0:
        Test Installation 7 of 25
        Installing Test @ 02:15:39

    pts/apache-1.6.1:
        Test Installation 8 of 25
        4 Files Needed [6.22 MB / 3 Minutes]
        Downloading: httpd-2.4.7.tar.bz2                            [4.77MB]
        Estimated Download Time: 3m ........................................
        Downloading: apache-ab-test-files-1.tar.gz                  [0.01MB]
        Estimated Download Time: 1m ........................................
        Downloading: apr-1.5.0.tar.bz2                              [0.78MB]
        Estimated Download Time: 1m ........................................
        Downloading: apr-util-1.5.3.tar.bz2                         [0.66MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 365 MB
        Installing Test @ 02:16:10

    pts/pgbench-1.5.2:
        Test Installation 9 of 25
        1 File Needed [16.8 MB / 3 Minutes]
        Downloading: postgresql-9.4.3.tar.bz2                      [16.80MB]
        Estimated Download Time: 3m ........................................
        Installation Size: 990 MB
        Installing Test @ 02:17:57

    pts/compilebench-1.0.1:
        Test Installation 10 of 25
        1 File Needed [0.56 MB / 1 Minute]
        Downloading: compilebench-0.6.tar.bz2                       [0.56MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 100 MB
        Installing Test @ 02:19:22

    pts/iozone-1.8.0:
        Test Installation 11 of 25
        1 File Needed [1.62 MB / 1 Minute]
        Downloading: iozone3_405.tar                                [1.62MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 2.3 MB
        Installing Test @ 02:19:38

    pts/dbench-1.0.0:
        Test Installation 12 of 25
        1 File Needed [1.96 MB / 1 Minute]
        Downloading: dbench-4.0.tar.gz                              [1.96MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 46.4 MB
        Installing Test @ 02:20:05

    pts/fs-mark-1.0.1:
        Test Installation 13 of 25
        1 File Needed [0.01 MB / 1 Minute]
        Downloading: fs_mark-3.3.tar.gz                             [0.01MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 1 MB
        Installing Test @ 02:20:18

    pts/fio-1.8.2:
        Test Installation 14 of 25
        1 File Needed [0.44 MB / 1 Minute]
        Downloading: fio-2.1.13.tar.bz2                             [0.44MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 4 MB
        Installing Test @ 02:20:25

    pts/tiobench-1.2.0:
        Test Installation 15 of 25
        1 File Needed [0.03 MB / 1 Minute]
        Downloading: tiobench-0.3.3.tar.gz                          [0.03MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 0.2 MB
        Installing Test @ 02:20:57

    pts/john-the-ripper-1.5.1:
        Test Installation 16 of 25
        1 File Needed [5.2 MB / 1 Minute]
        Downloading: john-1.8.0.tar.gz                              [5.20MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 5 MB
        Installing Test @ 02:21:10

    pts/compress-pbzip2-1.5.0:
        Test Installation 17 of 25
        3 Files Needed [127 MB / 13 Minutes]
        Downloading: bzip2-1.0.6.tar.gz                             [0.75MB]
        Estimated Download Time: 1m ........................................
        Downloading: pbzip2-1.1.12.tar.gz                           [0.05MB]
        Estimated Download Time: 1m ........................................
        Downloading: linux-4.3.tar.gz                                [126MB]
        Estimated Download Time: 14m .......................................
        Installation Size: 647 MB
        Installing Test @ 02:22:43

    pts/compress-7zip-1.6.2:
        Test Installation 18 of 25
        1 File Needed [3.66 MB / 1 Minute]
        Downloading: p7zip_9.20.1_src_all.tar.bz2                   [3.66MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 10 MB
        Installing Test @ 02:23:00

    pts/openssl-1.9.0:
        Test Installation 19 of 25
        1 File Needed [4.3 MB / 1 Minute]
        Downloading: openssl-1.0.1g.tar.gz                          [4.30MB]
        Estimated Download Time: 1m ........................................
            Download Failed: ftp://ftp.openssl.org/source/openssl-1.0.1g.tar.gz
            Attempting to download from alternate mirror.
        Downloading: openssl-1.0.1g.tar.gz                          [4.30MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 69 MB
        Installing Test @ 02:23:32

    pts/gcrypt-1.0.3:
        Test Installation 20 of 25
        2 Files Needed [1.48 MB / 1 Minute]
        Downloading: libgcrypt-1.4.4.tar.bz2                        [1.09MB]
        Estimated Download Time: 1m ........................................
        Downloading: libgpg-error-1.7.tar.bz2                       [0.39MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 16 MB
        Installing Test @ 02:25:10

    pts/himeno-1.2.0:
        Test Installation 21 of 25
        1 File Needed
        Downloading: himenobmtxpa.tar.bz2                           [0.00MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 0.05 MB
        Installing Test @ 02:25:40

    pts/c-ray-1.1.0:
        Test Installation 22 of 25
        1 File Needed [0.22 MB / 1 Minute]
        Downloading: c-ray-1.1.tar.gz                               [0.22MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 6.0 MB
        Installing Test @ 02:25:50

    pts/povray-1.1.2:
        Test Installation 23 of 25
        1 File Needed [34.41 MB / 3 Minutes]
        Downloading: povray-3.7.0.tar.bz2                          [34.41MB]
        Estimated Download Time: 3m ........................................
        Installation Size: 172 MB
        Installing Test @ 02:26:08

    pts/crafty-1.3.1:
        Test Installation 24 of 25
        1 File Needed [0.41 MB / 1 Minute]
        Downloading: crafty-23.4.zip                                [0.41MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 6 MB
        Installing Test @ 02:28:40
            The installer exited with a non-zero exit status.
            ERROR: pts/crafty-1.3.1/install.sh: line 3: unzip: command not found
            LOG: /var/lib/phoronix-test-suite/installed-tests/pts/crafty-1.3.1/install-failed.log

    pts/npb-1.2.2:
        Test Installation 25 of 25
        1 File Needed [0.59 MB / 1 Minute]
        Downloading: NPB3.3.tar.gz                                  [0.59MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 8 MB
        Installing Test @ 02:28:48

    The following tests failed to install:

    - pts/scimark2-1.2.0
    - pts/cachebench-1.0.0
    - pts/crafty-1.3.1

    Download Cache Directory: /var/lib/phoronix-test-suite/download-cache/

    Checking Downloads For: pts/apache-1.6.1
    Caching: httpd-2.4.7.tar.bz2
    Caching: apache-ab-test-files-1.tar.gz
    Caching: apr-1.5.0.tar.bz2
    Caching: apr-util-1.5.3.tar.bz2

    Checking Downloads For: pts/c-ray-1.1.0
    Caching: c-ray-1.1.tar.gz

    Checking Downloads For: pts/cachebench
    Caching: llcbench.tar.gz

    Checking Downloads For: pts/cachebench-1.0.0
    Previously Cached: llcbench.tar.gz

    Checking Downloads For: pts/compilebench-1.0.1
    Caching: compilebench-0.6.tar.bz2

    Checking Downloads For: pts/compress-7zip-1.6.2
    Caching: p7zip_9.20.1_src_all.tar.bz2

    Checking Downloads For: pts/compress-gzip-1.1.0

    Checking Downloads For: pts/compress-pbzip2-1.5.0
    Caching: bzip2-1.0.6.tar.gz
    Caching: pbzip2-1.1.12.tar.gz

    Checking Downloads For: pts/crafty
    Caching: crafty-23.4.zip

    Checking Downloads For: pts/crafty-1.3.1
    Previously Cached: crafty-23.4.zip

    Checking Downloads For: pts/dbench-1.0.0
    Caching: dbench-4.0.tar.gz

    Checking Downloads For: pts/fio-1.8.2
    Caching: fio-2.1.13.tar.bz2

    Checking Downloads For: pts/fs-mark-1.0.1
    Caching: fs_mark-3.3.tar.gz

    Checking Downloads For: pts/gcrypt-1.0.3
    Caching: libgcrypt-1.4.4.tar.bz2
    Caching: libgpg-error-1.7.tar.bz2

    Checking Downloads For: pts/himeno-1.2.0
    Caching: himenobmtxpa.tar.bz2

    Checking Downloads For: pts/iozone-1.8.0
    Caching: iozone3_405.tar

    Checking Downloads For: pts/john-the-ripper-1.5.1
    Caching: john-1.8.0.tar.gz

    Checking Downloads For: pts/minion-1.4.0
    Caching: minion-0.15-src.tar.gz

    Checking Downloads For: pts/network-loopback-1.0.1

    Checking Downloads For: pts/npb-1.2.2
    Caching: NPB3.3.tar.gz

    Checking Downloads For: pts/openssl-1.9.0
    Caching: openssl-1.0.1g.tar.gz

    Checking Downloads For: pts/pgbench-1.5.2
    Caching: postgresql-9.4.3.tar.bz2

    Checking Downloads For: pts/povray-1.1.2
    Caching: povray-3.7.0.tar.bz2

    Checking Downloads For: pts/ramspeed-1.4.0
    Caching: ramsmp-3.5.0.tar.gz

    Checking Downloads For: pts/scimark2
    Caching: scimark2_1c.zip

    Checking Downloads For: pts/scimark2-1.2.0
    Previously Cached: scimark2_1c.zip

    Checking Downloads For: pts/stream-1.3.1
    Caching: stream-2013-01-17.tar.bz2

    Checking Downloads For: pts/tiobench-1.2.0
    Caching: tiobench-0.3.3.tar.gz

However, when the caching ends for the specified test-profiles, PTS goes on attempts to cache additional tests (for whatever reason..) see the logs that follow:

    [PROBLEM] Network support is needed to obtain pts/opm-git-1.3.6 data.

    [PROBLEM] Network support is needed to obtain pts/tesseract-1.1.0 data.

**Comment by michaellarabel** [comment]
It's not actually a bug, when generating a download cache it needs to know what each test profile's meta-data is and the associated files it needs. So when building a download cache, it will ensure it has all test profile meta-data to ensure it's doing an accurate job caching of the download files.

**Comment by kkebb** [comment]
so based on your statement, you are saying that the opm-git and the tesseract test-profiles' meta-data is needed by one of the tests that I require?

**Comment by michaellarabel** [comment]
@kkebb, no, but it's getting that test profile meta-data [not all of the file downloads that test may or may not need] in order to know that. As some of those files being cached could be used by multiple different test profiles, so first PTS is getting all of the relevant test profile meta-data to be able to determine that -- and for other queries that may come after that such as wanting to list all test profiles that could be run with the files in the cache.

**Comment by kkebb** [comment]
oh okay - well why not just grab the meta-data of the test-profiles that have been installed/listed when calling the make-download-cache function?

**Comment by michaellarabel** [comment]
It's simply trying to be more helpful by collecting all the test profiles. Is there a particular issue you have with it? Would you rather it just not display an error when it can't fetch more meta-data during that process or what do you suggest as the workflow?

**Comment by kkebb** [comment]
I don't think that error should be masked from the user, if anything it needs to be shown. The main issues it seems like PTS is timing out when it fails to grab the meta-data it is searching for when we run it on our bamboo agents in the cloud. What I would probably suggest, is to implement some timeout "feature" and if the request for the meta-data times out then the PTS software would log all of the failed meta-data requests as a summary at the end of the `make-download-cache` function call.

Also, the [documentation](http://www.phoronix-test-suite.com/documentation/phoromatic.html) may require updating:

> This command will simply download all of the needed test files for the tests/suites passed to the sub-command. Alternatively you could also pass pts/all to cache all tests. It's important though to just cache the tests/suites you'll be using on your network. This will generate the test file download cache by default to ~/.phoronix-test-suite/download-cache/ or /usr/share/phoronix-test-suite/download-cache/ depending upon your write permissions. You can always run this command later with more test files. Alternatively, if you already have a number of tests installed on the system, simply running "phoronix-test-suite make-download-cache" will generate the cache based upon the currently installed tests.

since it says that when you run the `make-download-cache` without any test-profiles as arguments, PTS will go ahead download the meta-data for the tests that are already installed, however, based on the behaviour that I have seen and described to you, it is grabbing the meta-data for all.
