### ISSUE TITLE
Failure to install pts/cachebench due to corrupt tar.gz file

### ISSUE THREAD

**Issue by kkebb** [phoronix-test-suite/phoronix-test-suite#145]
pts/cachebench-1.0.0:
        Test Installation 6 of 25
        1 File Needed [0.17 MB / 1 Minute]
        Downloading: llcbench.tar.gz                                [0.17MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 0.5 MB
        Installing Test @ 02:15:38
            The installer exited with a non-zero exit status.
             LOG: /var/lib/phoronix-test-suite/installed-tests/pts/cachebench-1.0.0/install-failed.log

When I run an `ls -lah` under the path I noticed the llbench.tar.gz file was few hundred bytes, however when I downloaded the image off of this website it was 85KB, and then I re-ran the installation of pts/cachebench using: `phoronix-test-suite install pts/cachebench` and it worked.

**Comment by michaellarabel** [comment]
I've updated the pts/cachebench test profile so it's now using a different and static URL for the snapshot so those download troubles shouldn't happen again.
