### ISSUE TITLE
stress-ng is out of date

### ISSUE THREAD

**Issue by rsjohnso** [phoronix-test-suite/phoronix-test-suite#154]
Stress-ng package  #was updated to version 0.07.14 on January 10th so the current download URL and installation script are broken.  And apparently there is a version 0.07.15 that has just been released today.

**Comment by michaellarabel** [comment]
The pts/stress-ng test profile has been updated (v1.2.0) against the latest stress-ng upstream. The test also now uses the file hosted on the PTS server to avoid broken download links in the future - http://openbenchmarking.org/test/pts/stress-ng Thanks, Michael

**Comment by rsjohnso** [comment]
Thanks Michael!
 


Scott Johnson Production Eng, Sr
Desk: (217) 255-4317
IM: rsjohnso36
