### ISSUE TITLE
Support for ARM?

### ISSUE THREAD

**Issue by hellyberry** [phoronix-test-suite/phoronix-test-suite#155]
Is ARM (Raspberry 2/3) as platform for phoronix test suite environment supported? Can I use it to benchmark different audio and video codecs? So each run of ffmpeg or other cli calls with different options are benchmarked. Is this currently supported?

**Comment by michaellarabel** [comment]
Yes, ARMv7/ARMv8 is supported (ARMv6 can run too, the phoronix-test-suite itself works, albeit some of the upstream tests have issues). FFmpeg and other tests are supported; run 'phoronix-test-suite list-tests' to see the available tests.

**Comment by tsjsdbd** [comment]
@michaellarabel 
Can make `Docker Hub phoronix/pts` support ARM ？ 🙏

**Comment by michaellarabel** [comment]
Due to resource constraints and using ClearLinux as a base, there are no plans at this time to support the Docker instance on Arm. But the Phoronix Test Suite can be easily run bare metal on Arm or by creating a custom Docker container based off Ubuntu or others.

**Comment by tsjsdbd** [comment]
get，thanks。and I found in Dockerhub phoronix/pts，it‘s not release the `Dockerfile`，if have it，build ARM iamge can be much easier for newbie。
