### ISSUE TITLE
"auto-compare" option don't work.

### ISSUE THREAD

**Issue by Achaean** [phoronix-test-suite/phoronix-test-suite#157]
I'm on Debian Jessie x64.
I have this problem, with the latest stable version (v6.8.0 (Tana)).
Choosing 1,2. or 3, doesn't do any difference.

Here's the output:
```
giorgos@PC:~$ phoronix-test-suite auto-compare

1: Processor
2: Graphics
3: Disk
Sub-System To Test: 1

Querying test data from OpenBenchmarking.org...

[PROBLEM] No Tests Found For Installation.

[PROBLEM] You must enter at least one test, suite, or result identifier to run.

giorgos@PC:~$
```

**Comment by michaellarabel** [comment]
Hi @Achaean what sort of hardware/software were you trying to compare your system to? Sorry for the belated response as somehow overlooked this bug report. Anyhow, for the auto comparison it relies upon OpenBenchmarking.org being able to find close matches to your system's hardware/software from the publicly available results to compare to from OpenBenchmarking.org. If you could share your `phoronix-test-suite system-info` output I can run some manual checks to see if there should have been matches or if there is indeed a bug for certain hardware. On a majority of the systems, it's able to find matches.

**Comment by Achaean** [comment]
**Hi** Michael and **thanks** for your responce! :-)

I installed the new test suite version and indeed it informs me that it failed to fetch openbenchmarking data!

I installed it, on my new system (a 4-core AMD with an onboard graphic card and 4 GB memory). I've installed Debian Jessie x64 KDE, on it.

No problem for the test suites.  The Super Tux Kart test, is more than OK for me! :-)

Here's the Konsole's output:
```
giorgos-Τετ 22/03/2017 02:39 πμ~>phoronix-test-suite system-info

[NOTICE] Failed To Fetch OpenBenchmarking.org Repository Data: pts 

[NOTICE] Failed To Fetch OpenBenchmarking.org Repository Data: system

Phoronix Test Suite v7.0.0
System Information


  PROCESSOR:          AMD Athlon 5350 APU with Radeon R3 @ 2.05GHz (4 Cores)
    Core Count:       4
    Extensions:       SSE 4.2 + AVX
    Cache Size:       2048 KB
    Microcode:        0x700010b
    Scaling Driver:   acpi-cpufreq ondemand

  GRAPHICS:           ASUS AMD Radeon HD 8400 / R3
    OpenGL:           4.4.13399
    Screen:           1360x768

  MOTHERBOARD:        ASUS AM1M-A
    Memory:           3584MB
    Chipset:          AMD Family 16h Root Complex
    Network:          Realtek RTL8111/8168/8411

  DISK:               500GB Seagate ST3500320AS
    File-System:      ext4
    Mount Options:    data=ordered errors=remount-ro relatime rw
    Disk Scheduler:   CFQ

  OPERATING SYSTEM:   Debian 8.7
    Kernel:           3.16.0-4-amd64 (x86_64)
    Desktop:          KDE
    Display Server:   X Server 1.16.4
    Compiler:         GCC 4.9.2

giorgos-Τετ 22/03/2017 02:39 πμ~>
```

**Comment by michaellarabel** [comment]
Hi @Achaean are you behind a network proxy or anything like that? Network related issues would explain the OpenBenchmarking fetching problem.

**Comment by Achaean** [comment]
No. Just a usual PC, with ethernet connection to the router.
I'm getting the same error, even with UFW disabled.

**Comment by michaellarabel** [comment]
If you go into your browser are you able to access phoronix-test-suite.com and openbenchmarking.org?

**Comment by Achaean** [comment]
Yes of course!
I did an extensive use, of both sites.

**Comment by michaellarabel** [comment]
From your terminal could you try running:

php -r "echo file_get_contents('http://www.phoronix-test-suite.com/PTS');"

It should just print `PTS`. Or to try a non-Phoronix server, to see if anything is output for ` php -r "echo file_get_contents('http://google.com/');"  `

**Comment by Achaean** [comment]
```
giorgos-Τετ 22/03/2017 03:12 πμ~>php -r "echo file_get_contents('http://www.phoronix-test-suite.com/PTS');"
PHP Warning:  file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in Command line code on line 1
PHP Warning:  file_get_contents(http://www.phoronix-test-suite.com/PTS): failed to open stream: no suitable wrapper could be found in Command line code on line 1
giorgos-Τετ 22/03/2017 03:30 πμ~>
```
No. Seems there is a problem with php5.
BTW, what are the nescessary packages, for running PTS?
I think they're all installed.

**Comment by michaellarabel** [comment]
You have all the packages installed, but some distribution packages ship a weird php.ini file in /etc/. If you open your php.ini configuration file, search in there for allow_url_fopen and make sure it's enabled. If you change that allow_url_fopen setting, then your PTS issues should go away. Let me know if you have any issues in doing.

**Comment by Achaean** [comment]
Indeed, It was set to Off.
Turning it to On, solved the problem! :-)
