### ISSUE TITLE
RFE: Add AppStream metainfo file

### ISSUE THREAD

**Issue by AsciiWolf** [phoronix-test-suite/phoronix-test-suite#159]
_Phoronix Test Suite_ cannot be found and/or installed using GNOME Software or another [AppStream](https://www.freedesktop.org/software/appstream/docs/)-based package manager interface on Linux because it does not ship any desktop or metadata files. Please, consider adding a XML [metainfo](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html) file.

**Comment by michaellarabel** [comment]
Actually the Phoronix Test Suite does ship a phoronix-test-suite.appdata.xml, but will do some checking to see if it's out of date to the spec or something.

**Comment by michaellarabel** [comment]
$ appstream-util validate pts-core/static/phoronix-test-suite.appdata.xml 
pts-core/static/phoronix-test-suite.appdata.xml: FAILED:
• tag-missing           : <translation> not specified

It was complaining about <translation> not being set, but the documentation seems to indicate it's an optional tag: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

But anyhow when adding the empty translation tag [ https://github.com/phoronix-test-suite/phoronix-test-suite/commit/7aadba1d5786825e74b516e57880008dbf15f032 ] the validator at least seems to make it pass.

$ appstream-util validate pts-core/static/phoronix-test-suite.appdata.xml 
pts-core/static/phoronix-test-suite.appdata.xml: OK

So I think it should be working fine, feel free to re-open if there is anything else missing.
