### ISSUE TITLE
"SSL certificate problem: unable to get local issuer certificate" on Raspbian 8

### ISSUE THREAD

**Issue by ljishen** [phoronix-test-suite/phoronix-test-suite#160]
This is my `downloads.xml`
```<?xml version="1.0"?>
<!--Phoronix Test Suite v6.8.0-->
<PhoronixTestSuite>
  <Downloads>
    <Package>
      <URL>https://github.com/ckolivas/interbench/archive/v0.31.tar.gz</URL>
      <MD5>8cd587d2229041da24381bbd5ba087f0</MD5>
      <SHA256>eb838f89a95ba0bffde06c86f6bda565ef234e6165ab86df4e187933ac779151</SHA256>
      <FileName>v0.31.tar.gz</FileName>
      <FileSize>38791</FileSize>
    </Package>
  </Downloads>
</PhoronixTestSuite>
```

Error message I got after adding setting `CURLOPT_VERBOSE` as true in `pts_network.php`
```
* Hostname was NOT found in DNS cache
        Estimated Download Time: 1m *   Trying 192.30.253.112...
* Connected to github.com (192.30.253.112) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /home/pi/benchmarks/phoronix-test-suite-7.0.0/pts-core/static/certificates/
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
```

My current solution is to add
```
curl_setopt($cr, CURLOPT_SSL_VERIFYPEER, false);
```
to line 157 in file `pts_network.php`

The test PTS version I downloaded from `https://github.com/phoronix-test-suite/phoronix-test-suite/archive/v7.0.0.tar.gz`.

**Comment by michaellarabel** [comment]
If you comment out line 127 (		curl_setopt($cr, CURLOPT_CAPATH, PTS_CORE_STATIC_PATH . 'certificates/');) does that affect the behavior for you?

**Comment by michaellarabel** [comment]
This issue should be fixed by https://github.com/phoronix-test-suite/phoronix-test-suite/commit/daa583d7839c64169dc99e32053123acfa0f4734 if problem persists, please reopen.

**Comment by ljishen** [comment]
Sorry for the late reply. I solved this problem by adding a [CA certificates](https://curl.haxx.se/docs/caextract.html) to `php.ini`.
```
curl.cainfo=/path/to/cacert.pem
```
