### ISSUE TITLE
Test files cannot be fetched from a phoromatic instance

### ISSUE THREAD

**Issue by aieri** [phoronix-test-suite/phoronix-test-suite#162]
I have a phoromatic server with tests and test files cached. My pts clients are configured with `<NoInternetCommunication>TRUE</NoInternetCommunication>`.
I start with no tests installed on the clients.
When I run `phoronix-test-suite phoromatic.connect` I can observe the following (for example):

```
    pts/x264-2.0.0:
        Test Installation 10 of 12
        2 Files Needed [349 MB / 2 Minutes]
            Internet support is needed and it's disabled or not available.
            Downloading of needed test files failed.
```
To continue with the x264 example, soccer_4cif.y4m is clearly listed in the phoromatic cache web page.

Is this the expected behavior?

**Comment by michaellarabel** [comment]
What is your output of: phoronix-test-suite phoromatic.explore   when run from the client? It should download files from the Phoromatic Server unless for some reason the cache is messed up, etc, but the phoromatic.explore sub-command should provide some insight on what's being discovered by the client.

**Comment by aieri** [comment]
Totally empty. Even if phoromatic.connect works fine.

```
# phoronix-test-suite phoromatic.explore

Internet Communication Is Disabled Per Your User Configuration.


Phoronix Test Suite v7.0.0
Phoromatic Servers


No Phoromatic Servers detected.


```

**Comment by michaellarabel** [comment]
If you put the Phoromatic server IP:port into ~/.phoronix-test-suite/user-config.xml into <PhoromaticServers></PhoromaticServers> does it change the behavior?

**Comment by aieri** [comment]
After adding IP:port in `<PhoromaticServers>` phoromatic.explore indeed shows something...
Now it seems to be able to fetch all test dependencies correctly. Will test again on Monday and update this. Thanks!

**Comment by aieri** [comment]
Yes, I can confirm that adding the IP:port of my phoromatic server was enough to have the client go through the suite without any Internet access. I had understood that connecting a client to a phoromatic account via the special URL would have also cached the phoromatic server IP somewhere, but I see that that is not the case. Thanks for the help!

**Comment by michaellarabel** [comment]
@aieri when you use the "phoromatic.connect" command it should automatically add it to the Phoromatic download cache. But for some reason on your system it is not. I will look into that and re-open this if I find any bug there that could explain the behavior. But glad anyhow that adding it to your user configuration file works.

**Comment by aieri** [comment]
Sounds good. Let me know if you need help with the testing.
