### ISSUE TITLE
Uninstalling Tests/Suites and their Dependencies

### ISSUE THREAD

**Issue by mtimyself** [phoronix-test-suite/phoronix-test-suite#163]
Is there a way to uninstall a test suite and the dependencies that were installed (just) for it?
Your universe test is a great tool as it really does save hours of individual testing. The problem with it, however, is that it installs over 3600MB of dependencies, most of which will never be relevant again to a production server.
Is there anything that can be done short of running your benchmarks on a fresh system and then wiping it after completing the tests?

**Comment by michaellarabel** [comment]
@mtimyself There is the `phoronix-test-suite remove-installed-test` sub-command to remove a test. Removing a test is basically equivalent to `rm -rf ~/.phoronix-test-suite/installed-tests/<the tests>`. Each test is self-contained nicely.

Currently there isn't any removal of installed dependencies. It's already fragile in having to deal with supporting all reasonable Linux/BSD package managers for installing tests, but I'm not sure the removal of installed dependencies is something we would want to deal with and it hasn't been a feature that's been requested in the past nearly decade of PTS. It would then involve tracking which packages PTS installed itself and then just various risks that I'd rather not deal with when this is the first time anyone has requested such support. But with PTS showing what dependencies it's installing, you could easily run your distro's remove command on those packages after your testing is done.
