### ISSUE TITLE
gcc-c++ is not installed as a test dependency

### ISSUE THREAD

**Issue by markus-mayer** [phoronix-test-suite/phoronix-test-suite#164]
A Fedora user reported the following bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1436120

How to reproduce:
- install gcc, but not gcc-c++ (the c++ compiler)
- execute: 'phoronix-test-suite install-dependencies pts/compress-7zip'

Expected result:
pts is prompting the user, if he wants to install gcc-c++, because it is not installed

Actual result:
the user isn't prompted anything

Investigation:
In pts-core/external-test-dependencies/xml/generic-packages.xml line 62. For the package 'build-utilitites' it is only check if gcc (the c compiler) is present, but not if g++ (the c++ compiler) is present.

**Comment by michaellarabel** [comment]
The issue should be fixed by this commit to explicitly check for gcc and c++ on Fedora - https://github.com/phoronix-test-suite/phoronix-test-suite/commit/6cee52c4162a456384ba81d11ef4db87d2555f74 - Let me know if any other questions or issues.
