### ISSUE TITLE
Missing Text in PDF Output from Phoromatic

### ISSUE THREAD

**Issue by PsychoSid** [phoronix-test-suite/phoronix-test-suite#166]
Hello,

After running some tests and attempting output to PDF I get the front page and the graphs drawn but there is no text.

This is with 7.0.1 and CentOS7 tried with FPDF v1.7 and latest 1.8.x versions.

There are the default files in /usr/share/php/fpdf/fonts ?

What could be the issue here ?

Thanks
Paul

**Comment by michaellarabel** [comment]
If you are able to open up phoronix-test-suite/pts-core/pts_svg_dom_gd.php you should see:

`				$possible_fonts = array(
				'/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf',
				'/usr/share/fonts/truetype/freefont/FreeSans.ttf',
				'/usr/share/fonts/truetype/ttf-bitstream-vera/Vera.ttf',
				'/usr/share/fonts/dejavu/DejaVuSans.ttf',
				'/usr/share/fonts/liberation/LiberationSans-Regular.ttf',
				'/usr/share/fonts/truetype/DejaVuSans.ttf',
				'/usr/share/fonts/truetype/LiberationSans-Regular.ttf',
				'/usr/share/fonts/TTF/dejavu/DejaVuSans.ttf',
				'/usr/share/fonts/TTF/liberation/LiberationSans-Regular.ttf',
				'/usr/X11/lib/X11/fonts/TrueType/arphic/uming.ttf',
				'/usr/local/lib/X11/fonts/bitstream-vera/Vera.ttf',
				'/usr/share/fonts/aajohan-comfortaa/Comfortaa-Regular.ttf',
				'/Library/Fonts/Courier New.ttf',
				'/Library/Fonts/Trebuchet MS.ttf',
				'/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
				'/usr/share/fonts/truetype/ttf-bitstream-vera/Vera.ttf',
				'/usr/share/fonts/truetype/freefont/FreeSans.ttf',
				'/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf',
				);`

You are likely having no matches to any of those fonts. If you add some reasonable font to that list, does it work then? If so, let me know what font/path you use and can add it upstream so there will be a match for CentOS7.

**Comment by PsychoSid** [comment]
Thanks installed the dejavu-sans-fonts package from CentOS repos and now all text is included.
