### ISSUE TITLE
Serious Sam Fusion 2017 [pts/sam2017] Doesn't Run

### ISSUE THREAD

**Issue by Enverex** [phoronix-test-suite/phoronix-test-suite#167]
This test appears to have downloaded and installed OK, but it never runs the actual test. Trying to run it results in the game successfully opening, but it just sits at the pre-menu screen waiting for you to press any key to go to the main menu.

PTS itself just sits there with "Started Run 1 @ (the time)".

**Comment by michaellarabel** [comment]
Do you have Steam installed in the standard path? And with the standard Steam settings? Unfortunately, debugging the Steam-based test profiles is rather a pain due to the nature of Steam and not having much direct control over the program's execution.

**Comment by Enverex** [comment]
Should be. PTS manages to launch Serious Sam (it gets as far as the game's startup screen) so it's getting that far, it just doesn't seem to be telling it to actually do the benchmark.

**Comment by michaellarabel** [comment]
Then it's likely a regression in Sam2017 itself. You can try running `phoronix-test-suite debug-run sam2017` to see if anything useful is dumped by the game, but beyond that, there isn't much else to be done from PTS side with the it passing the arguments to the game unless they silently changed the game arguments now post-release (another problem in dealing with Steam for benchmarking is its unfortunate dynamic nature).

**Comment by Enverex** [comment]
That seems to actually output less, although now it does mention the command it's using:

>Test Run Command: cd /home/arcade/.phoronix-test-suite/installed-tests/pts/sam2017-1.0.1/ && ./sam2017 1280 800 Low OpenGL 2>&1

I think I've tracked down the issue. Steam is installed in the default location, but the game isn't (it's in an additional Steam game location) and the PTS seems to assume it's in the common folder of Steam's main install. I'll work around it and see if it still happens when it looks in the right place.
