### ISSUE TITLE
Deus Ex MD : Backup preferences

### ISSUE THREAD

**Issue by vhda** [phoronix-test-suite/phoronix-test-suite#169]
The benchmarking scripts are currently overriding the user's preferences.
Would it be possible to backup the current preferences before overriding them and restoring the preferences after the benchmark is complete? Ideally, the flow should be able to survive a ctrl-c.

**Comment by michaellarabel** [comment]
This issue is now open @ https://github.com/phoronix-test-suite/test-profiles/issues/1 with test profiles being separate from the PTS client.
