### ISSUE TITLE
Option to force run count ?

### ISSUE THREAD

**Issue by ikus060** [phoronix-test-suite/phoronix-test-suite#170]
I'm using phoronix test suite and I want to force the number of pass to be executed. Is their an option to force this number of pass ?

My goal is to run the same test  ~10 times otherwise I know the test I'm running is meaning less and will only measure the memory buffer instead of the real throughput.

Thanks

**Comment by michaellarabel** [comment]
Yep, just use the FORCE_TIMES_TO_RUN=<number> environment variable or there is also the FORCE_MIN_TIMES_TO_RUN= environment var too. See the documentation for specific details. Feel free to reopen if any issues, etc.
