### ISSUE TITLE
detailed-system-info not implemented?

### ISSUE THREAD

**Issue by akuckartz** [phoronix-test-suite/phoronix-test-suite#171]
README.md says:
> Viewing installed system hardware and software is available via phoronix-test-suite system-info or phoronix-test-suite detailed-system-info for greater verbosity.

But the second more verbose option did not work. It only displayed a general help page.

**Comment by michaellarabel** [comment]
With PTS 7.0, the system-info and detailed-system-info are the same. Will update the documentation to reflect.

**Comment by michaellarabel** [comment]
Fixed documentation @ https://github.com/phoronix-test-suite/phoronix-test-suite/commit/27e9e5a56ca029335b7c84450e55a6eefdf148e3
