### ISSUE TITLE
Dota test won't start

### ISSUE THREAD

**Issue by vadi2** [phoronix-test-suite/phoronix-test-suite#175]
```
Dota 2:
    pts/dota2-1.2.1 [Resolution: 1920 x 1200 - Renderer: OpenGL]
    Test 1 of 2
    Estimated Trial Run Count:    3
    Estimated Test Run-Time:      4 Minutes
    Estimated Time To Completion: 7 Minutes [06:31 CEST]
        Running Pre-Test Script @ 06:24:30

```

It opens Dota up and does not actually launch the benchmark - using 7.0.1.

**Comment by michaellarabel** [comment]
Do you have Steam setup in the default paths? Does it work if you try 'phoronix-test-suite force-install dota2' to reinstall it? Unfortunately, Steam games are only limitedly supported by PTS, but basically see that it works out-of-the-box on clean Ubuntu installs but your mileage may vary as unfortunately Steam makes things a mess for benchmarking compared to other games.

**Comment by vadi2** [comment]
Yep, it's in the default paths - using `steam` from the terminal works. The game also launches and I don't think it would otherwise.

I think this might be the issue - I have the replay in `/home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota/dota2-pts-1971360796.dem` but this doesn't work:

```
] timedemo dota2-pts-1971360796.dem
[Console] CDemoFile::Open: couldn't open file dota2-pts-1971360796.dem for reading.
ReadDemoHeader: invalid pBuffer.
dota2-pts-1971360796.dem:  unable to extract addons from file
```

Doing `timedemo "/home/vadi/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota/dota2-pts-1971360796.dem"` does work though.

The issue seems to be that the `dota2-benchmark` script expects an all-lowercase path whereas mine isn't (who knows why I didn't touch it).
