### ISSUE TITLE
[NOTICE] Undefined: ch in pts_network:166

### ISSUE THREAD

**Issue by brassh** [phoronix-test-suite/phoronix-test-suite#179]
when installing a test from behind an authenticating proxy, I get the following error:

> brassh:~/Downloads/phoronix/phoronix-test-suite> ./phoronix-test-suite run pts/ffmpeg
[PROBLEM] pts/ffmpeg-2.5.0 is not installed. 
    Would you like to stop and install these tests now (Y/n): Y
Phoronix Test Suite v7.2.0
    To Install:    pts/ffmpeg-2.5.0
    Determining File Requirements 
    Searching Download Caches 
    1 Test To Install
        2 Files To Download [298MB]
        372MB Of Disk Space Is Needed
    pts/ffmpeg-2.5.0:
        Test Installation 1 of 1
        2 Files Needed [298 MB]
        Downloading: ffmpeg-2.8.1.tar.bz2                                                                                                                                                                                        [8.17MB]
[NOTICE] Undefined: ch in pts_network:166
[NOTICE] curl_setopt() expects parameter 1 to be resource, null given in pts_network:166
        Downloading 
            Checksum Failed: http://ffmpeg.org/releases/ffmpeg-2.8.1.tar.bz2
    Try downloading the file again (Y/n): 

Reason seems to be a typo in file pts_network.php, lines 134 and 166, where the variable name is $ch but should be $cr. When I change the variable name accordingly, the installation succeeds as expected

I proposed a patch and pull request #178 (d751e3c)

**Comment by michaellarabel** [comment]
Yep was a typo and the patch is fine. Thanks.
