### ISSUE TITLE
disk tests doesn't see ZFS mounted partitions

### ISSUE THREAD

**Issue by gmelikov** [phoronix-test-suite/phoronix-test-suite#187]
Current algorithm can't give a variant to use ZFS mounted partition in https://github.com/phoronix-test-suite/phoronix-test-suite/blob/3981d4a169f905b7f2d16d0ccd90ca82059d84f4/pts-core/objects/pts_test_run_options.php#L283 , because it makes `$all_devices = array_merge(pts_file_io::glob('/dev/hd*'), pts_file_io::glob('/dev/sd*'), pts_file_io::glob('/dev/md*'), pts_file_io::glob('/dev/nvme*'), array('testpool'));` and tries to find some lines with them in `/proc/mounts`.

Example for usual xfs in `/proc/mounts`: 
`/dev/sda1 /boot xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0`
Example for usual zfs in `/proc/mounts`: 
`testpool /testpool zfs rw,seclabel,xattr,noacl 0 0`

**Comment by gmelikov** [comment]
Fast ugly patch, I'll make a PR if it's suitable:

```diff
@@ -318,6 +318,20 @@
 							$option_names[] = $mount_point; // ' [' . $partition_d . ']'
 						}
 					}
+					
+					//ZFS only
+					$mounts_arr = explode("\n", $mounts);
+					
+					foreach ($mounts_arr as $mount)
+					{
+						$mount_arr = explode(" ", $mount);
+						if ($mount_arr[2]=='zfs')
+						{
+							$option_values[] = $mount_arr[1];
+							$option_names[] = $mount_arr[1];
+						}
+					}
+					
 				}
 				else
 				{

```

**Comment by michaellarabel** [comment]
Hi @gmelikov apologies for overlooking this issue. Yes that should be fine if you want to send in a PR.
