### ISSUE TITLE
pts/mplayer-base installation fails

### ISSUE THREAD

**Issue by oberon2007** [phoronix-test-suite/phoronix-test-suite#188]
I'm trying to run `pts/battery-power-usage` with phoronix-test-suite v7.2.0 on Manjaro but required installation of **pts/mplayer-base** fails with
```
ERROR: libavcodec/libvpxenc.c:83:6: error: array index in initializer not of integer type
```
install-failed.log attached.
[install-failed.txt](https://github.com/phoronix-test-suite/phoronix-test-suite/files/1151276/install-failed.txt)

**Comment by michaellarabel** [comment]
The pts/mplayer-base-1.4.0 test profile is now available that uses upstream MPlayer 1.3.0 that should take care of this build issue.
