### ISSUE TITLE
pts/scimark2 incorrect optimization level

### ISSUE THREAD

**Issue by kristerw** [phoronix-test-suite/phoronix-test-suite#190]
The `pts/scimark2` builds the benchmark as
```
cc $CFLAGS -o scimark2 -O *.c -lm
```
that is, the optimization level in `$CFLAGS` is overridden by the later `-O`. This is bad as the test does not test what is intended, and it is made worse by GCC and LLVM treating  `-O`  differently (GCC treats it as `-O1` that focus as much on compilation time and debuggability as on generating fast code, and LLVM treats it as `-O2` that is a "real" optimization level that prioritizes performance) which makes the results nonrepresentative.

**Comment by michaellarabel** [comment]
After it was reported the rogue -O accidentally being left in, it was already corrected, thanks though.

http://openbenchmarking.org/test/pts/scimark2

http://openbenchmarking.org/innhold/bc2688849ac5c227ff8bc8c27e9665abaa68c29a
