### ISSUE TITLE
Create User

### ISSUE THREAD

**Issue by guilhermepga** [phoronix-test-suite/phoronix-test-suite#196]
Hello Guys,
When i create a user in index page the user dont show on users list, and i cant remove or add again, this user can access others users files.

thanks for all

**Comment by michaellarabel** [comment]
What version of PTS are you running? I haven't encountered this behavior but will check.

**Comment by guilhermepga** [comment]
Hello @michaellarabel , Phoronix Test Suite v7.2.1 (Trysil) - Core Version 7210 - PHP 7.0.20-1~dotdeb+8.2

**Comment by michaellarabel** [comment]
I have just tried reproducing this with 7.4 Git (should be same as 7.2.1 as I hadn't changed any of that Phoromatic code) but have been unable to reproduce it.

When I log into the account after making a new account, I see no other users' data on that server and it does show itself in the list. So if you could please provide more information it would be helpful.
