### ISSUE TITLE
setting disk target for pts/fio

### ISSUE THREAD

**Issue by gamkiller77** [phoronix-test-suite/phoronix-test-suite#202]
I been looking for many days on a way to point FIO to use a test directory on a test node not on the test server.
 
I can see the all the setting to store stuff on the server but no way to tell it how to do this on a remove test client.

The only option i get for PTS/fio is just default Test Directory.  It would be nice to spell it out some how.

**Comment by junghan0611** [comment]
solved?

**Comment by swarth100** [comment]
Have you tried modifying the test locally?
Once you have installed it via phoronix, you can edit the installation files to use a custom directory.

Firstly mount the test directory onto your system (there is a lot of online documentation, with multiple utilities out there, I would personally use NFS as its the simplest option).
Lets assume you have mounted the directory into `/mnt/server`

Initially install the test on the target machine:
```
$ phoronix-test-suite install pts/fio
```

Now navigate to the installation directory.
[As of the time I am writing this, `pts/fio` is running version `1.11.2`]
```
# For a user installation:
$ cd ~/.phoronix-test-suite/test-profiles/pts/fio-1.11.2

# For a root installation
$ cd /var/lib/phoronix-test-suite/test-profiles/pts/fio-1.11.2
```

Edit the `test-definition.xml`, changing
FROM:
```
    <Option>
      <DisplayName>Disk Target</DisplayName>
      <Identifier>auto-disk-mount-points</Identifier>
      <ArgumentPrefix></ArgumentPrefix>
      <ArgumentPostfix></ArgumentPostfix>
      <DefaultEntry>0</DefaultEntry>
    </Option>
```
TO:
```
    <Option>
      <DisplayName>Disk Target</DisplayName>
      <Identifier>custom-field</Identifier>
      <ArgumentPrefix></ArgumentPrefix>
      <ArgumentPostfix></ArgumentPostfix>
      <DefaultEntry>0</DefaultEntry>
      <Menu>
        <Entry>
          <Name>Mounted-Directory</Name>
          <Value>/mnt/server</Value>
          <Message></Message>
        </Entry>
        <Entry>
          <Name>Tmp-Directory</Name>
          <Value>/tmp</Value>
          <Message></Message>
        </Entry>
      </Menu>
    </Option>
```
[Note: change the **Name** and **Value** fields to your custom directories]
[Note2: using only one **Entry** tag will not prompt you for a choice when running the test as it uses the only option as default]

When you now run fio, you will get the options you have provided:
```
$ phoronix-test-suite run pts/fio
[...]
        1: Mounted-Directory
        2: Tmp-Directory
        3: Test All Options
        ** Multiple items can be selected, delimit by a comma. **

```
