### ISSUE TITLE
Library libGLEW.so.1.5 not found | Arch Linux

### ISSUE THREAD

**Issue by airvzxf** [phoronix-test-suite/phoronix-test-suite#216]
```bash
phoronix-test-suite run lightsmark
```
E: ./backend: error while loading shared libraries: libGLEW.so.1.5: cannot open shared object file: No such file or directory

**Comment by michaellarabel** [comment]
Unfortunately this is an issue with Lightsmark depending upon an older version of libGLEW not readily available on modern distributions. With Lightsmark being a closed-source app, there is no readily available solution AFAIK and is a problem with trying to run Lightsmark on any Linux distro in recent years.

**Comment by airvzxf** [comment]
**Solution:**

Modified these files with some HEX Editor:
```
~/.phoronix-test-suite/installed-tests/pts/lightsmark-1.2.0/Lightsmark2008.2.0/bin/pc-linux64/backend
~/.phoronix-test-suite/installed-tests/pts/lightsmark-1.2.0/Lightsmark2008.2.0/bin/pc-linux32/backend

```

**Steps**
1. Open the file `backend` in some hex editor.
1. Search the string `libGLEW.so.1.5`
1. Replace for `libGLEW.so.2.1`

_Note:_
Find the libGLEW in your system using: `sudo find / -iname *libGLEW.so* 2>/dev/null`

In my Arch Linux I have this libraries:
```
/usr/lib32/libGLEW.so.2.1
/usr/lib32/libGLEW.so.1.10
/usr/lib32/libGLEW.so.1.10.0
/usr/lib32/libGLEW.so.2.1.0
/usr/lib32/libGLEW.so
/usr/lib/libGLEW.so.2.1
/usr/lib/libGLEW.so.1.10
/usr/lib/libGLEW.so.1.10.0
/usr/lib/libGLEW.so.2.1.0
/usr/lib/libGLEW.so

```

**Comment by airvzxf** [comment]
Thanks for the fast answer @michaellarabel, I understand and I'm trying to document the solutions of this errors to future references.

The easy way to fix that is make a symbolic links instead of hard links that's mean execute this commands:
```bash
sudo ln -s /usr/lib/libGLEW.so.1.10.0 /usr/lib/libGLEW.so.1.5
sudo ln -s /usr/lib32/libGLEW.so.1.10.0 /usr/lib32/libGLEW.so.1.5
```
With this solution we trap to the program which is looking for the version 1.5 but it redirect to the 1.10 in my case is the last installed version.

This result in a symbolic file like:
`libGLEW.so.1.5 -> /usr/lib/libGLEW.so.1.10.0`
