### ISSUE TITLE
Mirror for "pyruvate_decarboxylase.fasta.bz2" for "pts/mafft-1.4.0" Is Non-Functional

### ISSUE THREAD

**Issue by TheUltraCode** [phoronix-test-suite/phoronix-test-suite#221]
Whenever I and [this guy](https://github.com/phoronix-test-suite/phoronix-test-suite/issues/211) tried to install "pts/mafft-1.4.0", we were unable to download the dependency file "pyruvate_decarboxylase.fasta.bz2". Upon further research, I found out that the current mirror for downloading the file does not work, as it brings up a 500 "internal server error" instead of a functional download link.

I *strongly* suggest that a new mirror is decided on for this file, such as this [GitHub page](https://github.com/BCLinux/auto-test/blob/master/download-cache/pyruvate_decarboxylase.fasta.bz2), which is where I got the file from. Although I have not run the test to see if it functions properly, the installation of the test completed with no errors with the use of this file, so to me, that was a success.

**Comment by michaellarabel** [comment]
pts/mafft-1.4.1 has mirrors updated - http://openbenchmarking.org/test/pts/mafft
