### ISSUE TITLE
Mirror Link for "openssl-1.0.1g.tar.gz" for "pts/openssl-1.9.0" Is Incorrect

### ISSUE THREAD

**Issue by TheUltraCode** [phoronix-test-suite/phoronix-test-suite#223]
Whenever I tried to install "pts/openssl-1.9.0", I was unable to download the dependency file "openssl-1.0.1g.tar.gz". Upon further research, I found out that the current mirror *link* for downloading the file does not work anymore. The reason why is because, while "ftp.openssl.org/source/" still exists, the maintainers of that website moved the file from where it originally was (where PTS tries to look for it) to the "/old/1.0.1" subdirectory.

I *strongly* suggest that the current mirror link is fixed and pointed here to find the file (ftp://ftp.openssl.org/source/old/1.0.1/). Although I have not run the test to see if it functions properly, the installation of the test completed with no errors with the use of this file, so to me, that was a success.

**Comment by michaellarabel** [comment]
pts/openssl-1.10.0 updates the test against the newer upstream OpenSSL and in the process also adds more robust download mirrors.

http://openbenchmarking.org/test/pts/openssl-1.10.0
