### ISSUE TITLE
pts/openarea-1.5.3 fails at fullscreen resolution of 3840x2160 on Quadro M2200 w/ 4GB VRAM and 32GB RAM

### ISSUE THREAD

**Issue by dragon788** [phoronix-test-suite/phoronix-test-suite#226]
This appears to be due to an error allocating memory. I'm not sure if this is a bug the PHP calling `openarena` or how PTS calls it or in `openarena` itself. The one thing that was frustrating about it was  since `openarena` took over full screen I had to drop to a TTY in order to kill it and then even though I killed it and tried to <kbd>Ctrl</kbd><kbd>C</kbd> in the terminal where I started the testing to abort further testing, it only killed the dialog that was asking if I wanted to use failsafe video mode, but then the command continued to run more executions of openarena.

```GL_VENDOR: NVIDIA Corporation
GL_RENDERER: Quadro M2200/PCIe/SSE2
GL_VERSION: 4.5.0 NVIDIA 384.90
GL_EXTENSIONS: GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_AMD_vertex_shader_viewport_index GL_AMD_vertex_shader_layer GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_cl_event GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_locations GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_sparse_texture2 GL_ARB_sparse_texture_clamp GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_minmax GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_GL_MAX_TEXTURE_SIZE: 16384
GL_MAX_TEXTURE_UNITS_ARB: 4

PIXELFORMAT: color(24-bits) Z(24-bit) stencil(0-bits)
MODE: -1, 3840 x 2160 fullscreen hz:N/A
GAMMA: hardware w/ 0 overbright bits
rendering primitives: single glDrawElements
texturemode: GL_LINEAR_MIPMAP_LINEAR
picmip: 0
texture bits: 32
multitexture: enabled
compiled vertex arrays: enabled
texenv add: enabled
compressed textures: disabled
glsl programs: disabled
Initializing Shaders
----- finished R_Init -----
Loading vm file vm/ui.qvm...
File "vm/ui.qvm" found in "./baseoa/pak6-patch088.pk3"
...which has vmMagic VM_MAGIC_VER2
Loading 1555 jump table targets
VM file ui compiled to 1663211 bytes of code (0x7f847555c000 - 0x7f84756f20eb)
compilation took 0.206643 seconds
ui loaded in 1451648 bytes on the hunk
58 arenas parsed
33 bots parsed
********************
ERROR: Hunk_AllocateTempMemory: failed on 67108872
********************
RE_Shutdown( 0 )
Hunk_Clear: reset the hunk ok
----- R_Init -----
Trying SMP acceleration...
^3ERROR: SMP support was disabled at compile time
...failed.
```

**Comment by michaellarabel** [comment]
Can you confirm if running it at ~1080p (or say 2560x or below) works fine? I've seen cases of OpenArena failing at 4K and is due to an issue with OpenArena itself.

**Comment by dragon788** [comment]
Oddly enough all the lower resolutions work in windowed or fullscreen, and the issue only seems to manifest when doing 4K fullscreen. If it is a known failing of OpenArena it might be a good idea to filter 4K to be an opt in/explicit only test rather than a default in the "All tests" selection. A lot of newer laptops are shipping with 2K-3K-4K screens and if you are doing automated tests it opens and "runs" OpenArena at 4K, but it just hangs on pulling down the snapshot, which since it is actually "running" I don't know if there is a PTS timeout that kills a test if it runs longer than expected or if you have to manually pass that (which many people probably wouldn't know to do).

**Comment by dragon788** [comment]
Just ran into the same issue on a different model of laptop with a 4K screen, so the 4K test should probably be disabled/manual opt-in until they fix that.

**Comment by dragon788** [comment]
I also ran into a strange case where running `phoronix-test-suite debug-run openarena` and selecting only the 4K resolution hung as described, but when I `killed` it using sigterm 15 via `top` from a virtual terminal, it continued to try and run, and if I selected failsafe it completed a run and then automatically started another run at 4K after the failsafe run. It also ended up running way more than the default 3 times, the last run where I tried to kill the script from the terminal (and only ended up killing the prompt for failsafe mode) it was reporting `OpenArena (Run 9 of 3)`.

**Comment by michaellarabel** [comment]
Apologies for the late reply. Unfortunately there isn't an easy workaround. OpenArena is the only graphical test I've run into that hangs at certain resolutions. That list of resolutions is always dynamically generated on the client system based upon the user's GPU/monitor with what resolution the monitor is running at, etc. Unfortunately no way via the test profile XML right now to place any restrictions on auto-generated option lists. Will keep this report open though as hope to be able to come up with such capability in the future if finding any other test profiles that would benefit from that functionality.

**Comment by michaellarabel** [comment]
pts/openarena-1.5.4 has switched over to using a static list (i.e. just 800 x 600 / 1024 x 7680 / 1920 x 1080 / 2560 x 1440) to avoid people accidentally selecting ~4K or higher where the game locks up. Unfortunately it's not clear if/when there will be a new OpenArena release where the fundamental issue might be properly rectified.
