### ISSUE TITLE
TEST_EXEC_PREPEND not working

### ISSUE THREAD

**Issue by carcinoma** [phoronix-test-suite/phoronix-test-suite#230]
Due to a glitch in https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/pts-core/objects/client/pts_test_execution.php#L231 using the TEST_EXEC_PREPEND environment variable will not work. All tests will fail starting up. Debug outputs:

> [26062.407818] [ERROR]Error running "exec": No such file or directory
> 
> Result Key: #_RESULT_#

**Comment by michaellarabel** [comment]
What are you trying to set in your TEST_EXEC_PREPEND? It's worked for intended use-cases expressed so far, but may need to be expanded to support other use-cases/formats.

**Comment by carcinoma** [comment]
I try to run `TEST_EXEC_PREPEND=optirun ./phoronix-test-suite debug-run openarena`

**Comment by michaellarabel** [comment]
Ah, okay. Mostly TEST_EXEC_PREPEND to now has been used for passing environment variables prior to test, etc.

https://github.com/phoronix-test-suite/phoronix-test-suite/commit/3382e8c76b1e9f4311d1081010798d7cf253e65d should fix this issue where if TEST_EXEC_PREPEND is a binary, don't call exec following it.

Please reopen if this doesn't fix your issue.
