### ISSUE TITLE
Comments in scripts interpreted by phoroscript_interpreter without space(s) after "#" are not ignored as comments

### ISSUE THREAD

**Issue by Eliasvan** [phoronix-test-suite/phoronix-test-suite#231]
Title explains the problem.

Example of a script where "`#command1`" and "`#command3`" are actually executed even though they should be ignored:

    # Note: some comments
    #       more comments
    #command1
    command2
    #command3
    # command4

When using Windows, this internally generates, e.g.:

    Can't recognize '#command1' as an internal or external command, or batch script.

**Comment by michaellarabel** [comment]
The comment line behavior in Phoroscript interpreter should be fixed up by https://github.com/phoronix-test-suite/phoronix-test-suite/commit/0258ae8930362aa8ddf8f9cec3e4a8ec03f511a8
