### ISSUE TITLE
Commands in scripts interpreted by phoroscript_interpreter are not executed in a context where the current working directory is set as requested by the script

### ISSUE THREAD

**Issue by Eliasvan** [phoronix-test-suite/phoronix-test-suite#232]
Title explains the problem.

Example of a (*.sh) script exhibiting the problem:

    cd C:\\
    start cmd /C "echo %cd% && pause"

When using Windows, this will popup a cmd window with:

    C:\phoronix-test-suite-master
    Press any key to continue...

instead of the following expected behaviour: popup a cmd window with:

    C:\
    Press any key to continue...

This can be worked around by modifying the script to:

    cd C:\\
    start cmd /C "call echo ^%cd^% && pause"

but that's not ideal since a *.bat script similar to the original *.sh script (see top of this issue description) will behave as expected, without needing the workaround.

**Comment by michaellarabel** [comment]
It turns out this change breaks unigine-heaven and unigine-valley test profiles on Windows. Going to take a look to see if there is an easy fix for both, but not sure at the moment.

**Comment by Eliasvan** [comment]
Is it possible those profiles themselves are incorrect and relying on the old incorrect behaviour of phoroscript_interpreter?
