### ISSUE TITLE
pts/x264 failure

### ISSUE THREAD

**Issue by pascaloettli** [phoronix-test-suite/phoronix-test-suite#235]
**Error message:**

    $ ./phoronix-test-suite install pts/x264

    Phoronix Test Suite v7.6.0

        To Install:    pts/x264-2.2.1

        Determining File Requirements ..........................................
        Searching Download Caches ..............................................

        1 Test To Install
            3 Files To Download [350MB]
            353MB Of Disk Space Is Needed

        pts/x264-2.2.1:
            Test Installation 1 of 1
            3 Files Needed [350 MB / 39 Minutes]
            Downloading: x264-snapshot-20170908-2245.tar.bz2             [0.72MB]
            Estimated Download Time: 1m .........................................
            Downloading: nasm-2.13.01.tar.bz2                            [0.92MB]
            Estimated Download Time: 1m .........................................
            Downloading: soccer_4cif.y4m                                  [349MB]
            Estimated Download Time: 37m ........................................
                Checksum Failed: http://media.xiph.org/video/derf/y4m/soccer_4cif.y4m
        Try downloading the file again (Y/n):

**Possible reason:**
xiph-media.net requires a manual verification (reCAPTCHA) before downloading the file, with the following justification:
> To reduce wasted bandwidth from poorly-behaved scrapers and web crawlers, please verify below that you intend to download a very large file.

**Comment by michaellarabel** [comment]
Unfortunately I am not aware of any other mirrors for soccer_4cif.y4m and unfortunately we don't have any extra bandwidth allocated for hosting that file. So for the time being unless there happens to be another mirror to use would be having to manually download it from the URL and drop it into ~/.phoronix-test-suite/download-cache/ or /var/lib/phoronix-test-suite/download-cache/ and from there PTS would automatically make use of it when installing x264 test profile.

**Comment by pascaloettli** [comment]
Yes, this is my current solution too. It was also to advertise users about this issue.

**Comment by michaellarabel** [comment]
pts/x264-2.3.0 is now available and with updating the x264 upstream program also switches to using a new video file with hopefully a more reliable mirror for a video source.

https://openbenchmarking.org/test/pts/x264-2.3.0
