### ISSUE TITLE
Confusing errors when openbenchmarking.org is down

### ISSUE THREAD

**Issue by dyfrgi** [phoronix-test-suite/phoronix-test-suite#236]
Looks like openbenchmarking.org is down right now. As a result, phoromatic is continually outputting errors like the following:
[PROBLEM] Network support is needed to obtain pts/openssl-1.9.0 data.

Given that the problem in openbenchmarking being down and not lack of network support, this is confusing. Some more detail in the error message such as "Cannot reach $server" would have made this problem easier to debug, instead of needing to see what server it was trying to reach and then load it myself in order to see that it's down.

**Comment by michaellarabel** [comment]
Hmm OpenBenchmarking.org isn't down right now nor is there any maintenance going on right now. Are you able to check your network connection otherwise send me your IP address so I can make sure the firewall didn't block it for some reason?

Anyhow, can work on improving the network error messages.

**Comment by michaellarabel** [comment]
https://github.com/phoronix-test-suite/phoronix-test-suite/commit/4705db7e5f9c3bacef4ca18763120e8b49ccfb56 has improved the error output in this case while working towards more informative network error reporting shortly.

OpenBenchmarking.org is still behaving fine right now so if your network issue persists, you can let me know your IP via michael at phoronix.com and I can check to make sure it's not hitting any firewall issues, etc.

**Comment by dyfrgi** [comment]
Thanks for the quick response! I was wondering about that since downforeveryoneorjustme made the same claim. It seems to be working now - not sure what the issue was unfortunately. If it starts misbehaving again, I'll drop you a line with my IP, thanks.

**Comment by jbhanks** [comment]
I'd just like to say that on several occasions over the past few months (including at the moment) I could not access openbenchmarking.org via my browser, and PTS gives errors too. When I try downforeveryoneorjustme (or similar sites), they always say it is up. Usually, I can access openbenchmarking.org again after waiting some time (a few minutes to an hour).
