### ISSUE TITLE
"phoronix-test-suite benchmark vpxenc" captcha in download link breaks benchmark install's download

### ISSUE THREAD

**Issue by jebsolutions** [phoronix-test-suite/phoronix-test-suite#237]
to duplicate:
Install Phoronix test suite from .deb file
phoronix-test-suite benchmark vpxenc 

expected result:
Install works and test runs.

actual result:
Download fails with no clear indication of why.

Temp Work around:
Manually copy-paste the download link show in in the installer error into a browser.  Reply to the captcha proving your a human who loves downloading 389mb files.  :)

Move the downloaded file into
/var/lib/phoronix-test-suite/installed-tests/pts/vpsenc-1.40

re-run "phoronix-test-suite benchmark vpxenc" and it will work.

**Comment by jebsolutions** [comment]
failing url with captacha on it is:
https://xiph-media.net/video/derf/y4m/soccer_4cif.y4m

**Comment by michaellarabel** [comment]
Yep aware of it, that mirror recently implemented CAPTCHA requirement. Unfortunately not aware of any other public mirrors of that file and unfortunately I don't have the extra bandwidth on current servers for being able to host it on our side. So for now unfortunately not aware of a solution.

FYI though can just download the file to /var/lib/phoronix-test-suite/download/cache or ~/.phoronix-test-suite/download-cache/ and that file will automatically be picked up when needed.

**Comment by jebsolutions** [comment]
Thanks for your quick reply.  

I know how it goes with mirrors and bandwidth.  Glad it's not my $.  :)

On an unrelated note, I am testing Ubuntu 18.04 beta.  If I spot an 18.04 specific issue would you like me to report it or no bother since it's a beta?

**Comment by michaellarabel** [comment]
You are more than welcome to report any Ubuntu 18.04 issues. I am already running it on some of my boxes and haven't encountered any issues but if you encounter any problems, feel free to report. (I hope you are using the latest PTS stable release. Unfortunately in the Ubuntu repo still the phoronix-test-suite package is years outdated.)

**Comment by jebsolutions** [comment]
I am using the latest 7.6 stable .deb file from the pts website.

Will report if I spot anything.

**Comment by michaellarabel** [comment]
Great thanks!

**Comment by michaellarabel** [comment]
Great thanks!

**Comment by michaellarabel** [comment]
pts/vpxenc-2.0.0 is now available [ http://openbenchmarking.org/test/pts/vpxenc-2.0.0 ] and along with upgrading the latest libvpx upstream and other changes, a new source video is used to avoid this file mirror issue.

**Comment by michaellarabel** [comment]
The pts/x264-2.3.0 test profile update pulls in the latest x264 upstream program and in the process switches to a different video source with hopefully a more stable/open mirror for the future.

https://openbenchmarking.org/test/pts/x264-2.3.0
