### ISSUE TITLE
pts/mcperf                     

### ISSUE THREAD

**Issue by SuryaPractise** [phoronix-test-suite/phoronix-test-suite#238]
Hi Team,

I am trying to install pts/mcperf on CentOS 7.3X and "The installed exited with a non-zero exit status" as in the attached error screenshot..

![pts - mcperf installation issue](https://user-images.githubusercontent.com/12717052/35261992-9e7382da-0038-11e8-8800-0b9d793d80e0.jpg)

As per the error message, we went ahead and installed libevent manually but getting agin the same error when tried to install the mcperf in Phoronix Test Suite.

Kindly help us ASAP.

Regards!
Surya

**Comment by SuryaPractise** [comment]
Hi Team,

Any update?
Thanks,
Surya

**Comment by michaellarabel** [comment]
You are still getting a libevent error even after installing the development dependencies for it? Have you tried installing the mcperf upstream program manually? This sounds like an upstream program with mcperf on your platform outside the scope of the Phoronix Test Suite, so difficult to debug based upon the information available.
