### ISSUE TITLE
how to create batch setup for individual tests 

### ISSUE THREAD

**Issue by yogeshVU** [phoronix-test-suite/phoronix-test-suite#241]
How to create batch setup for individual tests  and let all the different tests run in the batch mode

**Comment by michaellarabel** [comment]
First setup batch mode: `phoronix-test-suite batch-setup`

Then specify all the tests/suites:

`phoronix-test-suite batch-run encode-mp3 x264 ffmpeg ... <all the different tests to run>`

Or is there an oversight somewhere?

**Comment by yogeshVU** [comment]
Yes 
``
batch-run
`` will let me run the same configuration for all the tests.

What I am looking for is can one select different configuration setups for different tests. 
so one may just want to run read performance testing for a disk io test and some other option for other tests. How can one select/configure such options and still run all kinds of tests in the batch mode

**Comment by michaellarabel** [comment]
Run `phoronix-test-suite build-suite`, select all the tests you want from there and configure it how you want and then run `phoronix-test-suite batch-run <the custom suite name>`

**Comment by yogeshVU** [comment]
cool will give that a try... and update

**Comment by yogeshVU** [comment]
I don't think the `build-suite` is the right command here. As you can see for the example below `pts/cachebench` there are 4 options. but When I try to run the `build-suite` it does not present these 4 options... So I am searching for some other command here if there is any.

```root@56efc94c2119:/# phoronix-test-suite run pts/cachebench    


CacheBench:
    pts/cachebench-1.1.0
    Processor Test Configuration
        1: Read
        2: Write
        3: Read / Modify / Write
        4: Test All Options
        Test: ^C
root@56efc94c2119:/# phoronix-test-suite build-suite       

Phoronix Test Suite v6.0.1
Test Suite Creation


Enter name of suite: pts/cachebench

1: System
2: Processor
3: Disk
4: Graphics
5: Memory
6: Network
7: Other
Select test type: 7

Enter suite maintainer name: yo

Enter suite description: yo

Available Options:

1: Add Test
2: Add Sub-Suite
3: Save & Exit
Select next operation: s

1: Add Test
2: Add Sub-Suite
3: Save & Exit
Select next operation: 3


Saved To: /var/lib/phoronix-test-suite/test-suites/local/ptscachebench/suite-definition.xml
To run this suite, type: phoronix-test-suite benchmark ptscachebench


```

**Comment by michaellarabel** [comment]
It is the correct command. When you ran build-suite, you need to go to "add Test" and then select pts/cachebench. Don't name the suite pts/cachebench. E.g.

` ./phoronix-test-suite  build-suite

Phoronix Test Suite v7.8.0m2
Test Suite Creation


Enter name of suite: testsuite

1: System
2: Processor
3: Disk
4: Graphics
5: Memory
6: Network
7: Other
Select test type: 1

Enter suite maintainer name: t

Enter suite description: fddsf

Available Options:

1: Add Test
2: Add Sub-Suite
3: Save & Exit
Select next operation: 1

1:   pts/aio-stress
2:   pts/apache
.....
279: system/redis
280: system/sqlite
281: eliasvan/supertuxkart
Enter test name: pts/cachebench


CacheBench:
    pts/cachebench-1.1.0
    Processor Test Configuration
        1: Read
        2: Write
        3: Read / Modify / Write
        4: Test All Options
        Test: 1,3


Available Options:

1: Add Test
2: Add Sub-Suite
3: Save & Exit
Select next operation: 1

1:   pts/aio-stress
2:   pts/apache
3:   pts/apitest
4:   pts/apitrace
.....
278: system/openssl
279: system/redis
280: system/sqlite
281: eliasvan/supertuxkart
Enter test name: xonotic

1:   pts/aio-stress
2:   pts/apache
....
280: system/sqlite
281: eliasvan/supertuxkart
Enter test name: pts/xonotic


Xonotic 0.8.2:
    pts/xonotic-1.5.0
    Graphics Test Configuration
        1:  800 x 600
        2:  1440 x 480
        3:  1024 x 768
        4:  1440 x 576
        5:  1280 x 800
        6:  1280 x 960
        7:  1440 x 900
        8:  1280 x 1024
        9:  1680 x 1050
        10: 1920 x 1080
        11: 2560 x 1440
        12: 2560 x 1600
        13: 3840 x 2160
        14: 3840 x 4320
        15: Test All Options
        Resolution: 4,9


        1: Low
        2: High
        3: Ultra
        4: Ultimate
        5: Test All Options
        Effects Quality: 3


Available Options:

1: Add Test
2: Add Sub-Suite
3: Save & Exit
Select next operation: 3


Saved -- to run this suite, type: phoronix-test-suite benchmark testsuite
`

And then run `phoronix-test-suite batch-run testsuite`

**Comment by yogeshVU** [comment]
Thanks for the detailed information @michaellarabel 
It works now!
