### ISSUE TITLE
[patch] PTS overcommits the cores by 2x

### ISSUE THREAD

**Issue by dblueman** [phoronix-test-suite/phoronix-test-suite#244]
PTS 8.0.0m1 still runs twice as many processes than cores in certain tests. This creates scheduler overcommitting, producing higher variance and not testing as a test would be typically be executed.

Please consider fixing it, since version 8 will be the only change until version 9 I guess:

```
diff --git a/pts-core/objects/client/pts_client.php b/pts-core/objects/client/pts_client.php
index a14485c..95f7af3 100644
--- a/pts-core/objects/client/pts_client.php
+++ b/pts-core/objects/client/pts_client.php
@@ -246,7 +246,7 @@ class pts_client
                        'PHP_BIN' => PHP_BIN,
                        'NUM_CPU_CORES' => phodevi::read_property('cpu', 'core-count'),
                        'NUM_CPU_NODES' => phodevi::read_property('cpu', 'node-count'),
-                       'NUM_CPU_JOBS' => (phodevi::read_property('cpu', 'core-count') * 2),
+                       'NUM_CPU_JOBS' => (phodevi::read_property('cpu', 'core-count')),
                        'SYS_MEMORY' => phodevi::read_property('memory', 'capacity'),
                        'VIDEO_MEMORY' => phodevi::read_property('gpu', 'memory-capacity'),
                        'VIDEO_WIDTH' => pts_arrays::first_element(phodevi::read_property('gpu', 'screen-resolution')),

```

**Comment by michaellarabel** [comment]
That logic was in place from ~10 years ago when commonly was recommended for -j of (cores * 2) or (cores * 2) - 1. But with the increasing core count of today's systems, perhaps could run into some scheduler issues... So will go ahead and merge this for 8.0.

**Comment by michaellarabel** [comment]
Actually on second thought and reverting that change, the better approach used will be when test profiles are updated that make use of $NUM_CPU_JOBS, to transition them to the $NUM_CPU_CORES instead, that way will result in avoiding any confusion or potentially incomparable results, etc.
