### ISSUE TITLE
Please consider python as a replacement for current shell operations

### ISSUE THREAD

**Issue by alexandrul** [phoronix-test-suite/phoronix-test-suite#248]
Hi,

I've had the pleasure of investigating a strange behavior on Windows Server 2012 R2:

- `pts/compress-7zip-1.7.0` was installed without any issues
- running the test resulted in no output
- attempting to run `7z.exe` manually was not possible due to a permission error

It seems that my Cygwin installation breaks some ACL things, even if the installation was performed from scratch using its installer.

While I was able to find a fix, could you please consider moving all shell operations to python 3? It works just fine under both Windows and Linux and it will make very easy to expand the current set of features.

**Comment by michaellarabel** [comment]
Thanks for the suggestion but at this point with around one thousand different tests, it would be extremely labor intensive to move all shell operations to be based on Py3 with little gain at this point. In the future _optional_ Py3 shell support might be considered for officially supporting if an enterprise customer need arises, but there are no plans at this time to change the current shell operations as to not break all existing test profiles.
