### ISSUE TITLE
php_openssl.dll path is too specific

### ISSUE THREAD

**Issue by alexandrul** [phoronix-test-suite/phoronix-test-suite#249]
`microsoft_dependency_handler.php` checks for a specific `php_openssl.dll` location instead of deriving it from the `PHP_BIN` env var used by `phoronix-test-suite.bat`:

https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/pts-core/external-test-dependencies/dependency-handlers/microsoft_dependency_handler.php#L28

**Comment by michaellarabel** [comment]
The php_openssl.dll should now be handled better in latest Git. Thanks.
