### ISSUE TITLE
Some tests failed to install on ubu16.04, e.g. pts/padman-1.1.0 & pts/postmark-1.1.0

### ISSUE THREAD

**Issue by meinazhou** [phoronix-test-suite/phoronix-test-suite#250]
Host: Ubuntu16.04
Installed test suite: phoronix-test-suite-7.8.0.tar.gz

Some tests failed to install, e.g. pts/padman-1.1.0 & pts/postmark-1.1.0

Steps:
1. pts/cpu tests: pts/padman-1.1.0 & pts/compress-pbzip2-1.5.0 failed to install

$ phoronix-test-suite run pts/cpu

Multiple tests are not installed:

- pts/padman-1.1.0
- pts/compress-pbzip2-1.5.0
    Would you like to stop and install these tests now (Y/n): y

Phoronix Test Suite v7.8.0

    To Install:    pts/padman-1.1.0
    To Install:    pts/compress-pbzip2-1.5.0

    Determining File Requirements .........................................................................................................
    Searching Download Caches .............................................................................................................

    2 Tests To Install
        5 Files To Download [746MB]
        1259MB Of Disk Space Is Needed

    pts/padman-1.1.0:
        Test Installation 1 of 2
        3 Files Needed [620 MB / 18 Minutes]
        Downloading: worldofpadman.run                                                                                              [551MB]
            Download Failed: http://thilo.kickchat.com/download/worldofpadman.run
            Attempting to download from alternate mirror.
        Downloading: worldofpadman.run                                                                                              [551MB]
            Download Failed: ftp://ftp.bm.kernel.org/pub/mirrors/gentoo/source/distfiles/worldofpadman.run
            Attempting to download from alternate mirror.
        Downloading: worldofpadman.run                                                                                              [551MB]
            Download Failed: ftp://ftp.snt.utwente.nl/pub/games/worldofpadman/linux/worldofpadman.run
            Downloading of needed test files failed.
    pts/compress-pbzip2-1.5.0:
        Test Installation 2 of 2
        3 Files Needed [127 MB / 4 Minutes]
        File Found: bzip2-1.0.6.tar.gz                                                                                             [0.75MB]
        Downloading: pbzip2-1.1.12.tar.gz                                                                                          [0.05MB]
            Download Failed: https://launchpad.net/pbzip2/1.1/1.1.12/+download/pbzip2-1.1.12.tar.gz
            Downloading of needed test files failed.

2. pts/disk tests: pts/dbench-1.0.0 and pts/postmark-1.1.0 failed to install

$ phoronix-test-suite run pts/disk

Multiple tests are not installed:

- pts/dbench-1.0.0
- pts/postmark-1.1.0
    Would you like to stop and install these tests now (Y/n): y

Phoronix Test Suite v7.8.0

    To Install:    pts/dbench-1.0.0
    To Install:    pts/postmark-1.1.0

    Determining File Requirements .........................................................................................................
    Searching Download Caches .............................................................................................................

    2 Tests To Install
        2 Files To Download [1.97MB]
        48MB Of Disk Space Is Needed

    pts/dbench-1.0.0:
        Test Installation 1 of 2
        1 File Needed [1.96 MB / 1 Minute]
        Downloading: dbench-4.0.tar.gz                                                                                             [1.96MB]
            Download Failed: http://samba.org/ftp/tridge/dbench/dbench-4.0.tar.gz
            Attempting to download from alternate mirror.
        Downloading: dbench-4.0.tar.gz                                                                                             [1.96MB]
            Download Failed: ftp://ftp.ussg.iu.edu/linux/gentoo/distfiles/dbench-4.0.tar.gz
            Attempting to download from alternate mirror.
        Downloading: dbench-4.0.tar.gz                                                                                             [1.96MB]
            Download Failed: ftp://ftp.tu-ilmenau.de/Mirrors/gentoo/distfiles/dbench-4.0.tar.gz
            Downloading of needed test files failed.
    pts/postmark-1.1.0:
        Test Installation 2 of 2
        1 File Needed [0.01 MB / 1 Minute]
        Downloading: postmark_1.51.orig.tar.gz                                                                                     [0.01MB]
            Download Failed: http://ftp.gva.es/mirror/debian/pool/main/p/postmark/postmark_1.51.orig.tar.gz
            Attempting to download from alternate mirror.
        Downloading: postmark_1.51.orig.tar.gz                                                                                     [0.01MB]
            Download Failed: ftp://ftp.nz.freebsd.org/pub/debian-amd64/debian-amd64/pool/main/p/postmark/postmark_1.51.orig.tar.gz
            Attempting to download from alternate mirror.
        Downloading: postmark_1.51.orig.tar.gz                                                                                     [0.01MB]
            Download Failed: ftp://ftp.uk.debian.org/debian/pool/main/p/postmark/postmark_1.51.orig.tar.gz
            Downloading of needed test files failed.

Host Details info:
$ phoronix-test-suite system-info

Phoronix Test Suite v7.8.0
System Information

  PROCESSOR:          Intel Core i5-6200U @ 2.80GHz
    Core Count:       2
    Thread Count:     4
    Extensions:       SSE 4.2 + AVX2 + AVX + RDRAND + FSGSBASE
    Cache Size:       3072 KB
    Microcode:        0xc2
    Scaling Driver:   intel_pstate powersave

  GRAPHICS:           Intel HD 520 3072MB
    Frequency:        1000MHz
    OpenGL:           4.5 Mesa 17.2.8
    Display Driver:   intel 2.99.917
    Screen:           1366x768

  MOTHERBOARD:        HP 8101
    BIOS Version:     N78 Ver. 01.09
    Chipset:          Intel Sky Lake
    Audio:            Conexant CX20724
    Network:          Realtek RTL8111/8168/8411 + Broadcom BCM43228 802.11a/b/g/n

  MEMORY:             12288MB

  DISK:               1000GB TOSHIBA MQ01ABD1
    File-System:      ext4
    Mount Options:    data=ordered errors=remount-ro relatime rw
    Disk Scheduler:   DEADLINE

  OPERATING SYSTEM:   Ubuntu 16.04
    Kernel:           4.4.0-119-generic (x86_64)
    Desktop:          Unity 7.4.0
    Display Server:   X Server 1.18.4
    Compiler:         GCC 5.4.0 20160609 + Clang 3.8.0-2ubuntu4
    Security:         KPTI + OSB (observable speculation barrier Intel v6) + Full generic retpoline IBPB (Intel v4) Protection

Other info:
1. pts/cpu tests list:
android@hpNotebook:~/Downloads/phoronix-test-suite$ phoronix-test-suite install pts/cpu

Phoronix Test Suite v7.8.0

    To Install:    pts/padman-1.1.0
    Installed:     pts/etqw-demo-1.1.0
    Installed:     pts/photo-sample-1.0.1
    Installed:     pts/graphics-magick-1.7.0
    Installed:     pts/john-the-ripper-1.6.2
    Installed:     pts/ttsiod-renderer-1.6.1
    To Install:    pts/compress-pbzip2-1.5.0
    Installed:     pts/compress-7zip-1.7.0
    Installed:     pts/timed-audio-encode-1.0.0
    Installed:     pts/encode-mp3-1.7.0
    Installed:     pts/encode-flac-1.6.0
    Installed:     pts/x264-2.3.2
    Installed:     pts/ffmpeg-2.7.2
    Installed:     pts/openssl-1.10.0
    Installed:     pts/gcrypt-1.0.4
    Installed:     pts/himeno-1.2.0
    Installed:     pts/pgbench-1.8.4
    Installed:     pts/apache-1.7.1
    Installed:     pts/c-ray-1.1.1
    Installed:     pts/povray-1.2.1
    Installed:     pts/smallpt-1.0.3
    Installed:     pts/tachyon-1.1.1
    Installed:     pts/crafty-1.4.2
    Installed:     pts/tscp-1.2.1
    Installed:     pts/mafft-1.5.0
    Installed:     pts/npb-1.2.4
    Installed:     pts/stream-1.3.1

2. pts/disk tests list:

android@hpNotebook:~/Downloads/phoronix-test-suite$ phoronix-test-suite install pts/disk

Phoronix Test Suite v7.8.0

    Installed:     pts/compress-gzip-1.2.0
    Installed:     pts/sqlite-2.0.1
    Installed:     pts/apache-1.7.1
    Installed:     pts/pgbench-1.8.4
    Installed:     pts/compilebench-1.0.2
    Installed:     pts/iozone-1.9.4
    To Install:    pts/dbench-1.0.0
    Installed:     pts/fs-mark-1.0.1
    Installed:     pts/fio-1.11.2
    Installed:     pts/tiobench-1.3.1
    To Install:    pts/postmark-1.1.0
    Installed:     pts/aio-stress-1.1.1
    Installed:     pts/unpack-linux-1.1.1

**Comment by HaHoYou** [comment]
Hello? Why these file download fails, either address does not exist, or just only fail?

**Comment by michaellarabel** [comment]
The Padman test profile has been effectively deprecated for a while with there not being a new upstream Padman game release since circa 2011.

The other test you mentioned, Postmark, has now been updated to pts/postmark-1.1.1 with various new download URLs that are currently working.
