### ISSUE TITLE
Export result to JSON not working correctly

### ISSUE THREAD

**Issue by frestok** [phoronix-test-suite/phoronix-test-suite#251]
JSON Export shows only last result in test

**Comment by michaellarabel** [comment]
Can you please elaborate on the issue you are encountering as well as specifying the version of PTS you are on? Thanks.

**Comment by frestok** [comment]
Latest 8m3

**Comment by frestok** [comment]
phoronix-test-suite result-file-to-csv test

`
Test

 ,"Test"
Processor,Intel Core i5-7300HQ @ 2.50GHz (1 Core)
Motherboard,Oracle VirtualBox v1.2
Chipset,Intel 440FX- 82441FX PMC
Memory,1024MB
Disk,3 x 11GB VBOX HDD + 2 x 11GB HDD
Graphics,InnoTek VirtualBox
Audio,Intel 82801AA AC 97 Audio
Network,Intel 82540EM Gigabit
OS,Ubuntu 16.04
Kernel,4.4.0-116-generic (x86_64)
Compiler,GCC 5.4.0 20160609
File-System,ext4
Screen Resolution,800x600
System Layer,Oracle VirtualBox

 ,,"Test"
"pts/fio-1.11.2 - randread posixaio 1 0 4m /mnt/disk1",HIB,665
"pts/fio-1.11.2 - randwrite posixaio 1 0 4m /mnt/disk1",HIB,283
"pts/fio-1.11.2 - read posixaio 1 0 4m /mnt/disk1",HIB,732
"pts/fio-1.11.2 - write posixaio 1 0 4m /mnt/disk1",HIB,293
`

root@ubuntu:~/phoronix-test-suite# phoronix-test-suite result-file-to-json test
`{
    "title": "Test",
    "results": {
        "pts\/fio-1.11.2": {
            "arguments": "Type: Sequential Write - IO Engine: POSIX AIO - Buffered: Yes - Direct: No - Block Size: 4MB - Disk Target: \/mnt\/disk1",
            "units": "MB\/s",
            "results": {
                "Test": {
                    "value": "293"
                }
            }
        }
    }
}
`

**Comment by michaellarabel** [comment]
@frestok apologies for the latest reply. Previously the JSON just exported the final result, while with the latest Git there is now also an "all_results" entry to show all of the data, e.g.

>         "pts\/compilebench-1.0.2": {
            "arguments": "Test: Initial Create",
            "units": "MB\/s",
            "results": {
                "None": {
                    "value": "399.28",
                    "all_results": "397.84:400.01:399.98"
                },
                "MQ-Deadline": {
                    "value": "398.38",
                    "all_results": "392.24:397.82:405.09"
                },
                "BFQ low_latency": {
                    "value": "395.96",
                    "all_results": "396.4:397.84:393.64"
                },
                "BFQ": {
                    "value": "401.96",
                    "all_results": "397.15:404.37:404.37"
                },
                "Kyber": {
                    "value": "400.59",
                    "all_results": "405.87:392.27:403.62"
                }
            }

**Comment by jamieluckett** [comment]
I'm still having this issue in 8.6.1 and 8.8.0

**Comment by michaellarabel** [comment]
What issue are you having? Can you post what your JSON output looks like?

**Comment by jamieluckett** [comment]
@michaellarabel I'm not 100% sure this is the same issue looking in to it, but my JSON results are missing values from the CSV one.

```
$ phoronix-test-suite result-file-to-csv 2019-03-25-1548

2019-03-25-1548

 ,,"2019-03-25 15:48"
Processor,,Intel Xeon E5-2676 v3 (2 Cores)
Motherboard,,Xen HVM domU (4.2.amazon BIOS)
Chipset,,Intel 440FX 82441FX PMC
Memory,,4096MB
Disk,,8GB
Graphics,,Cirrus Logic GD 5446
OS,,Ubuntu 16.04
Kernel,,4.4.0-1075-aws (x86_64)
Compiler,,GCC 5.4.0 20160609
File-System,,ext4
System Layer,,Xen HVM domU 4.2.amazon

 ,,"2019-03-25 15:48"
"pts/sockperf-1.0.0 - throughput",HIB,343386
"pts/sockperf-1.0.0 - ping-pong",LIB,14.75
"pts/sockperf-1.0.0 - under-load",LIB,13.33
```

```
 $ phoronix-test-suite result-file-to-json 2019-03-25-1548

{
    "title": "2019-03-25-1548",
    "results": {
        "pts\/sockperf-1.0.0": {
            "arguments": "Test: Latency Under Load",
            "units": "usec",
            "results": {
                "2019-03-25 15:48": {
                    "value": "13.33",
                    "all_results": "13.021:13.082:13.453:14.041:13.043"
                }
            }
        }
    }
}
```

**Comment by michaellarabel** [comment]
In that code snippet you are saying that's your entire JSON output? Or are you referring to that all_results is ':' delimited?

**Comment by jamieluckett** [comment]
@michaellarabel The JSON code snippet is my entire JSON output, results for Ping Pong and Throughput are missing

**Comment by michaellarabel** [comment]
If you pull from latest Git now is it fine?

**Comment by jamieluckett** [comment]
@michaellarabel Perfect! Many thanks :)
```
$ phoronix-test-suite result-file-to-json 2019-03-25-1548

{
    "title": "2019-03-25-1548",
    "results": [
        {
            "test": "pts\/sockperf-1.0.0",
            "arguments": "Test: Throughput",
            "units": "Messages Per Second",
            "results": {
                "2019-03-25 15:48": {
                    "value": "343386",
                    "all_results": "349708:341020:340970:342902:342328"
                }
            }
        },
        {
            "test": "pts\/sockperf-1.0.0",
            "arguments": "Test: Latency Ping Pong",
            "units": "usec",
            "results": {
                "2019-03-25 15:48": {
                    "value": "14.75",
                    "all_results": "14.873:14.752:14.762:14.692:14.675"
                }
            }
        },
        {
            "test": "pts\/sockperf-1.0.0",
            "arguments": "Test: Latency Under Load",
            "units": "usec",
            "results": {
                "2019-03-25 15:48": {
                    "value": "13.33",
                    "all_results": "13.021:13.082:13.453:14.041:13.043"
                }
            }
        }
    ]
}
```
