### ISSUE TITLE
pts-core: enable testing of android devices

### ISSUE THREAD

**Issue by lramage94** [phoronix-test-suite/phoronix-test-suite#253]
I would like to connect to hundreds of android tablets via adb (via network or usb) and run tests from a central location. I would also like to see F-Droid used for package management.

At my current job, I have approximately 1000 tablets deployed to users in the facility. The devices have a soft phone and are used for phone calls among other tasks. Users have headsets and are frequently complaining that they cannot be heard. I have also had many defective headphone jacks on these tablets.

    adb install -r com.danielkim.soundrecorder_130.apk # from [F-Droid](https://f-droid.org/packages/com.danielkim.soundrecorder/)
    adb shell start -n com.danielkim.soundrecorder/.activities.MainActivity
    # then I record a few seconds of audio to see if the microphone jack is working
    # this is done manually for now. I then replay the audio to listen for any issues.
    adb uninstall com.danielkim.soundrecorder

I also use [OgreSampleBrowser](https://f-droid.org/en/packages/org.ogre.browser/) as a test for 3D Graphics Performance. These tablets should be able to play most android games but I have had a high failure rate related to this as well.

I spend hours a week troubleshooting these devices and I RMA dozens of these devices a month.

**Comment by lramage94** [comment]
I have begun implementing changes here,

https://github.com/lramage94/phoronix-test-suite/tree/feature_android

Termux Support
https://github.com/lramage94/phoronix-test-suite/commit/ad1fec6fd3230e3684a0647c23425a1f6606291b

ADB (WIP)
https://github.com/lramage94/phoronix-test-suite/commit/94652fb7bb279613293ad637ec51ee74a22029a9

**Comment by michaellarabel** [comment]
Hi, just wanted to check in to see how this work was going? Thanks.

**Comment by lramage94** [comment]
I was busy at work last week so I didn't have a ton of time to work on this. But I was able to launch Ogre via `adb shell am start -n <packagename>/.<activityname>`.

https://github.com/OGRECave/ogre/blob/master/Samples/AndroidJNI/MainActivity.java

 I also looked into controlling multiple tablets at once. I was using bash to parse `adb devices` and loop through each one.

I still need to figure out how to programmatically test the headphone jack.

**Comment by lramage94** [comment]
downloads.xml
```xml
<?xml version="1.0"?>
<!--Phoronix Test Suite v8.0.0m0-->
<PhoronixTestSuite>
  <Downloads>
    <Package>
      <URL>https://f-droid.org/repo/org.ogre.browser_9.apk</URL>
      <MD5>ebbde3ba5747d9d846188acd8494ae57</MD5>
      <SHA256>4076eda3b8956b56efdd0313c4af5ee10e18ea8e066f62869d118d5e51cf6d4c</SHA256>
      <FileSize>61594014</FileSize>
    </Package>
  </Downloads>
</PhoronixTestSuite>
```

test-definition.xml
```xml
<?xml version="1.0"?>
<!--Phoronix Test Suite v8.0.0m0-->
<PhoronixTestSuite>
  <TestInformation>
    <Title>OgreSampleBrowser</Title>
    <AppVersion>1.10.11 </AppVersion>
    <Description>This is a test profile to run OgreSampleBrowser on Android.</Description>
    <TimesToRun>1</TimesToRun>
  </TestInformation>
  <TestProfile>
    <Version></Version>
    <SupportedPlatforms>Android</SupportedPlatforms>
    <SoftwareType>Game</SoftwareType>
    <TestType>System</TestType>
    <License>MIT</License>
    <Status></Status>
    <SupportedArchitectures>armv7a</SupportedArchitectures>
    <EnvironmentSize></EnvironmentSize>
    <ProjectURL>https://www.ogre3d.org</ProjectURL>
    <Maintainer>Lucas Ramage</Maintainer>
  </TestProfile>
</PhoronixTestSuite>
```

**Comment by lramage94** [comment]
I'm leaving github pretty soon so I'm closing this.

I will reach out to you via email soon with a patch, but for now you can follow my progress at,

https://gitlab.com/lramage94/phoronix-test-suite/issues/1

**Comment by michaellarabel** [comment]
Okay, feel free to email me at michael at phoronix.com if you will be off GitHub but wish to submit patches. Or via the forums @ https://www.phoronix.com/forums/
