### ISSUE TITLE
Phoromatic: Suite Editor resets test-profile entries to default values

### ISSUE THREAD

**Issue by swarth100** [phoronix-test-suite/phoronix-test-suite#260]
When editing an existing test suite via Phoromatic (note the existing suite should have at least a toggleable test option/entry), existing options are not preserved after saves.

Example:

1. Generate a new test suite and choose the `pts/stream` test-profile, select "Test All Options".
1. Create the Suite. This will generate a Test Suite with 4 Stream tests, each having a different option entry. (Namely `Copy`, `Scale` `Add` and `Triad`)
1. Edit the newly created suite to add a new test (any new test will do)
1. Hit on "Create new Suite" (to actually save the changes).
1. The four stream tests now all will default to option entry 0 (namely `Copy`), instead of preserving their 4 original distinct choices. [NOTE: New tests with multiple options are preserved].
- - - 
Speculations:
What I believe is happening is within the post request to update an existing test-suite, there is no information regarding the values to assign to existing tests, and hence they are defaulted to their default value.

- - -
EDIT:
For anyone experiencing this issue I suggest editing directly the test suite definition file (`suite-definition.xml`), which can be found under:
```
# User installation
~/phoronix-test-suite/phoromatic/accounts/_ACCOUNT_ID_/suites/_SUITE_NAME_/suite-definition.xml

# Root installation
/var/lib/phoronix-test-suite/phoromatic/accounts/_ACCOUNT_ID_/suites/_SUITE_NAME_/suite-definition.xml
```

**Comment by michaellarabel** [comment]
Apologies for the oversight in not noticing this thread... Anyhow, I've committed a fix to Git and can confirm the issue and that it is indeed resolved now by the latest Git ahead of PTS 8.2.
