### ISSUE TITLE
Phoromatic: Editing System Variables

### ISSUE THREAD

**Issue by swarth100** [phoronix-test-suite/phoronix-test-suite#264]
Once a System Variable is generated, it seems like it cannot be edited from the UI of the System Variables section.

A workaround I found was to inspect the HTML source, manually change the value, and then click "Update". This will actually propagate and save the changes.

**Comment by michaellarabel** [comment]
This issue should be fixed now in Git master and will be found in an 8.0.1 point release due out later this month.
