### ISSUE TITLE
Mov file not valid input for vpxenc test

### ISSUE THREAD

**Issue by luctrudeau** [phoronix-test-suite/phoronix-test-suite#267]
As posted on https://openbenchmarking.org/test/pts/vpxenc

> The test is attempting to encode a .mov file but that is not valid input for vpxenc. It is treating it as raw yuv input. Try watching the output to verify this.
> 
> vpxenc needs a yuv or y4m file as input.
> 
> Post by johann on 31 May 2018, 16.16.

After chatting with Johann, one possible solution could be to use ffmpeg to convert the .mov to a y4m

Another solution would be to download a y4m directly. I asked maintainers of xiph.media.org if they could remove the captcha on one y4m file. It does not appear to be feasible at this time. Other source of y4m are rare.  A possible alternative could be TRACE http://trace.eas.asu.edu/yuv/, they host zipped yuv files. Which would require zip to be installed.

I'm not sure how dependencies are managed, probably other tests require zip. The idea of using ffmpeg is also interesting.

**Comment by michaellarabel** [comment]
Hmm, looks like it was an oversight made earlier in that test profile's development PTS already has a hard dependency on ZIP, so that isn't an issue. There is separately an FFmpeg test profile but would prefer not to have to introduce that as a requirement for the vpxenc test. Do you happen to know of any good, well-mirrored YUV/Y4M files you would recommend? Otherwise I'll do some checking again for recent YUV/Y4M high quality files that are well mirrored. Thanks.

**Comment by luctrudeau** [comment]
Another source of high quality Y4M/YUV files is http://ultravideo.cs.tut.fi/#testsequences

**Comment by michaellarabel** [comment]
A new source file is now used by pts/vpxenc-2.1 

http://openbenchmarking.org/test/pts/vpxenc-2.1.0
http://openbenchmarking.org/innhold/5301a115870ec4b3ce94a0663de6123c5fbaeeba

Thanks for the pointer on the sources for some high quality Y4M/YUV files.

**Comment by luctrudeau** [comment]
Thanks for fixing this. Can't wait to see some results :)

**Comment by luctrudeau** [comment]
I would like to propose some changes to the encoding parameters, where do I find vpxenc-2.1.0?

The changes I would like to make are:

- You don't need to set width and height with a y4m (already encoded in the file)
- -cpu-used=1 or 2. 1 is what Google recommends (see http://wiki.webmproject.org/ffmpeg/vp9-encoding-guide). If that's too slow, 2 is also very popular. Default is 0, this might make the test very long.

**Comment by michaellarabel** [comment]
Tests are versioned outside of Git but just refreshed the Git export so it's viewable here:

You can submit a pull request via https://github.com/phoronix-test-suite/test-profiles for ease of submitting. https://github.com/phoronix-test-suite/test-profiles/tree/master/pts/vpxenc-2.1.1
