### ISSUE TITLE
Phoronix: RH7.5 - su authentication failure

### ISSUE THREAD

**Issue by swarth100** [phoronix-test-suite/phoronix-test-suite#268]
Issue is present when attempting to run phoronix-test-suite from command line on multiple servers all running RedHat 7.5

```
$  uname -r
3.10.0-862.3.2.el7.x86_64
$  cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core)
```

Attempting to install dependencies from within a `phoronix-test-suite` command, will prompt for password, yet it will fail to authenticate.

Example:

```
$ phoronix-test-suite install pts/rodinia

The following dependencies are needed and will be installed: 

- opencl-headers
- pocl

This process may take several minutes.
Please enter your root password below:
Password: 
su: Authentication failure

There are dependencies still missing from the system:
- OpenCL

1: Ignore missing dependencies and proceed with installation.
2: Skip installing the tests with missing dependencies.
3: Re-attempt to install the missing dependencies.
4: Quit the current Phoronix Test Suite process.
Missing dependencies action: 3

The following dependencies are needed and will be installed: 

- opencl-headers
- pocl

This process may take several minutes.
Please enter your root password below:
Password: 
su: Authentication failure
```

Same commands work corectly on Ubuntu16.04 and Ubuntu 18.04 on same master commits.

**Comment by swarth100** [comment]
I am sorry, this is actually incorrect.
Had a wrong setup where I had sudo enabled users, though I did realise phoronix will actively try to acquire su, hence requiring the *root* password, and not simply the sudo password.

**Comment by michaellarabel** [comment]
The logic where this is being handled at on RHEL systems is: https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/pts-core/external-test-dependencies/scripts/install-fedora-packages.sh

su has historically been used in that case for the best out-of-the-box support on RHEL/Fedora/CentOS/Scientific, but may be time to evaluate. Or if any improvements you wish to make to that script to help improve the workflow such as prompting for sudo if su authentication fails, etc, that would probably be useful as well.
