### ISSUE TITLE
Rise Of Tomb Raider benchmark still open automatically with PTS removed

### ISSUE THREAD

**Issue by mariojuniorjp** [phoronix-test-suite/phoronix-test-suite#271]
Hi. I have a little problem here: the RoTR benchmark still open automatically when i start the game. If i try to run the game benchmark manually, when finished, game close automatically.

I can't see the benchmark result because of this. I already uninstalled PTS suite, removed the hidden folder but the benchmark still run automatically.

I running on Ubuntu 18.04.

**Comment by michaellarabel** [comment]
You can modify the preferences file in ~/.local/share/feral-interactive/Rise of the Tomb Raider as the benchmark string is still likely left in there.
