### ISSUE TITLE
gcrypt test has zero error handling

### ISSUE THREAD

**Issue by rossburton** [phoronix-test-suite/phoronix-test-suite#273]
```
Gcrypt Library 1.4.4:
    pts/gcrypt-1.0.4
    Test 1 of 1
    Estimated Trial Run Count:    3
    Estimated Time To Completion: 3 Minutes [15:46 UTC]
        Started Run 1 @ 15:44:00
        The test quit with a non-zero exit status.
        Started Run 2 @ 15:44:01
        The test quit with a non-zero exit status.
        Started Run 3 @ 15:44:02
        The test quit with a non-zero exit status.
```

That would be because the test is running `./libgcrypt-1.4.4/tests/benchmark` which doesn't exist, because configure errored out due to libgpg-error not being present.

```
checking for GPG Error - version >= 1.4... ./configure: line 23308: /var/lib/phoronix-test-suite/installed-tests/pts/gcrypt-1.0.4//gpgerror/bin/gpg-error-config: No such file or directory
no
configure: error: libgpg-error is needed.
```

All of the install and test scripts should actually check exit codes occasionally...

**Comment by michaellarabel** [comment]
pts/gcrypt-1.0.5 is now available that adds the install-exit-status trigger (http://openbenchmarking.org/innhold/34c4b91bbd4e91256337304e1986aa3b4b32d145) for reporting the exit status of the make command. This should now raise the error when needed and PTS should generally be able to then also detect that error string from the log and report it to the user.

For a majority of the tests (or effectively all, for the modern relevant tests) there is this error handling in place, just for some tests that are seldom used these days or fly under my radar they might not have the exit status bit in place.
