### ISSUE TITLE
phoromatic.connect with no arguments reboots the system

### ISSUE THREAD

**Issue by cloyce** [phoronix-test-suite/phoronix-test-suite#278]
I'm testing a new (isolated) Phoromatic setup.  I ran 'phoronix-test-suite phoromatic.connect' without any arguments so I could get it to tell me what it expected.  It did, so that's good.
What's less good is that it also rebooted the system where I ran it.  I tested a second time, and same deal.  This is not okay:

~~~~
# ./phoronix-test-suite phoromatic.connect

You must pass the Phoromatic Server information as an argument to phoromatic.connect, or otherwise configure your network setup.
      e.g. phoronix-test-suite phoromatic.connect 192.168.1.2:5555/I0SSJY

Connection to ansible.sppo closed by remote host.
Connection to ansible.sppo closed.
% ssh root@ansible.sppo                   
root@ansible.sppo's password: 
Last login: Tue Jul  3 12:51:13 2018 from 10.224.11.123
# w
 13:13:58 up 0 min,  1 user,  load average: 0.00, 0.00, 0.00
~~~~

This is with 8.0.1 plus commits up to f5359531558a34724020e2e121a06a318cc9ad1a.

**Comment by michaellarabel** [comment]
Hi cloyce, was this system ever setup previously to a Phoromatic server? Trying to debug how  that would be happening... If you set the PTS_NO_REBOOT_ON_NETWORK_FAILURE=1 environment variable prior to running the command, does the system still reboot?

**Comment by cloyce** [comment]
This is a brand new system.  I've been looking at the code and I see the PTS_NO_REBOOT_ON_NETWORK_FAILURE exclusion.   Setting that does indeed keep the reboot from happening.  I just found it very surprising that reboot was the default, and that PTS doesn't distinguish between "couldn't connect" and "no network details were specified".

Regardless, I don't think PTS_IS_DAEMONIZED_SERVER_PROCESS should be set, though, since I didn't ask it to start a Phoromatic server (that's on another system).  AFAICT from `pts_define_directories` that's getting set based solely on whether /var/lib and /etc are writable, which is true in my case (running as root).  I think that logic is perhaps a little incomplete.  Shouldn't it be based on other criteria as well?

I see that it only gets set if PTS_IS_CLIENT is also set; that seems confusing to me but I haven't backtracked that through the code yet, so I'm not claiming that it doesn't make sense.

**Comment by michaellarabel** [comment]
The logic for the reboot-on-network-down could certainly be improved upon... The main purpose of that was for some cases where the network gets messed up and the system not dynamically/gracefully recovering but working well after reboot. That code has mostly grown organically over time as various people have reported different problems in their use-cases they have encountered.

(The PTS_IS_DAEMONIZED_SERVER_PROCESS define is a bit poorly named remnant against something that has evolved over time... Mostly for indicating if root in this context but will clear it up to help out future people looking at the code.)

If you comment out the first check (or just apply this patch https://github.com/phoronix-test-suite/phoronix-test-suite/commit/8d6d9ccc5852f359c09e620b46abc5cc16cf211d ) does it work fine on your setup now?

It should behave better then. There still is a reboot possibility further down the stack if the system fails connecting 10 times to the server, etc, but will work on improving that check until having some better network handling checks that work nicely across all supported operating systems.

**Comment by cloyce** [comment]
Yes, that patch would also do the trick.

I've read through the code a bit more now and I understand what's going on.  Mostly I was just very surprised, so maybe this is better addressed in the documentation.

Anyway, since this is intended behavior, I'll go ahead and close the ticket.  Sorry for the churn.

**Comment by michaellarabel** [comment]
Okay, great. Yeah the documentation could certainly be improved upon and the code comments. Thanks for the feedback on the few questions/areas raised when looking at the code, will work on addressing that for helping others understand.
