### ISSUE TITLE
failed tests cause of missing deps on centos7

### ISSUE THREAD

**Issue by dahabakuk** [phoronix-test-suite/phoronix-test-suite#279]
running pts 8.0.1 2 on CentOS7 dependencies are not installed/suggested when running benchmark pts/disk:

for tiobench and apache:
bzip2
for apache
expat-devel

**Comment by michaellarabel** [comment]
Thanks for the report. The latest Git should now have the external dependency coverage you mentioned for RHEL/Fedora-based Linux distributions.
