### ISSUE TITLE
Incorrect error message if binaries are in a noexec mounted directory

### ISSUE THREAD

**Issue by jackwasey** [phoronix-test-suite/phoronix-test-suite#283]
Many will have 'noexec' mount flag on their home directory, so running binaries in `~/.phoronix-test-suite` will fail. The error message I get in this situation said that the test binary "could not be located." In fact, it was located but could not be executed. I suggest testing for this possibility and giving an appropriate message.

**Comment by michaellarabel** [comment]
Thanks for the feedback. This issue should now be corrected by https://github.com/phoronix-test-suite/phoronix-test-suite/commit/31d7ee84bd552e357ed18a64c6f8387f74c0a14f with checks in place both at install-time and run-time if the test installation path is on a file-system that is mounted with 'noexec'
