### ISSUE TITLE
Show what packages were installed by Phoronix

### ISSUE THREAD

**Issue by abitrolly** [phoronix-test-suite/phoronix-test-suite#284]
I hope Phoronix doesn't mark packages as manually installed when installing `gcc` and friends, so that when `phoronix-test-suite` package is removed, the dependencies could be cleaned automatically. However from #163 it looks like the compatibility with various package managers to cleanup after benchmarking is not a priority, but it helps if Phoronix could just record and show dependencies what were installed manually. It helps if dependencies could be requested manually and it helps if test suite reports these dependencies when standard cleanup procedure is invoked (test cleanup and no tests left after).

**Comment by FabioLolix** [comment]
I guess part of this can be done (not the automatically cleanup), depending on package managers, with installation options (i.e. see #274 ) and improving PTS packaging for distributions

**Comment by abitrolly** [comment]
Well, `dnf` can not do this - https://ask.fedoraproject.org/en/question/124469/dnf-mark-package-as-dependency/ - I need to file a bug report to add this functionality. `dnf` has a transaction log, which may contain info who added package and when. Maybe that can be used to revert the transaction.

**Comment by abitrolly** [comment]
```
# dnf history
ID     | Command line             | Date and time    | Action(s)      | Altered
-------------------------------------------------------------------------------
   271 | -y install glibc.i686 li | 2018-08-11 11:51 | Install        |   57   
   270 | install phoronix-test-su | 2018-08-11 08:52 | Install        |    6   
...
# dnf history info 271
Transaction ID : 271
Begin time     : Sat 11 Aug 2018 11:51:22 AM +08
Begin rpmdb    : 2693:1774376faeb5fc204fc8d25ba36b02abb9a70b90
End time       : Sat 11 Aug 2018 11:51:36 AM +08 (14 seconds)
End rpmdb      : 2750:041aa12e55f56875fc29e7facd5260189662eb99
User           : anatoli <anatoli>
Return-Code    : Success
Command Line   : -y install glibc.i686 libstdc++.i686 libX11.i686 libXext.i686 libXrandr.i686 libXinerama.i686 mesa-libGL.i686 openal-soft.i686 SDL-devel SDL_gfx-devel SDL_image-devel SDL_net-devel SDL_sound-devel SDL_ttf-devel gcc gcc-c++ make autoconf automake glibc-static patch gtk2-devel qt4-devel
Transaction performed with:
    Installed     dnf-2.7.5-12.fc28.noarch @fedora
    Installed     rpm-4.14.1-9.fc28.x86_64 @updates
Packages Altered:
    Install SDL-devel-1.2.15-30.fc28.x86_64          @fedora
    Install SDL_gfx-2.0.25-8.fc28.x86_64             @fedora
    Install SDL_gfx-devel-2.0.25-8.fc28.x86_64       @fedora
...
```
So it is possible to use `dnf history undo 271` to revert test suite transactions. The only problem is that it reverts all packages there even if I try to install them explicitly after test suite. Because `dnf` doesn't make a record in transaction log in this case.
```
# dnf install SDL-devel
Last metadata expiration check: 0:00:00 ago on Sun 12 Aug 2018 01:52:26 AM +08.
Package SDL-devel-1.2.15-30.fc28.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by abitrolly** [comment]
Bug report for `dnf` - https://bugzilla.redhat.com/show_bug.cgi?id=1615045

**Comment by mhalano** [comment]
Any news about that? I'm having bad times cleaning my system (Ubuntu 21.10). The phoronix-test-suite says the dependencies, but in a generic form, not the exactly package. It is easier to know what is the package for some dependencies, like "Git", but not for others, like "OpenGL Extension Wrangler".
