### ISSUE TITLE
pts/mrbayes download fails due to location change

### ISSUE THREAD

**Issue by adatum** [phoronix-test-suite/phoronix-test-suite#286]
Installing `pts/mrbayes` test fails because the download locations are no longer valid:

``` 
File Not Found: http://kent.dl.sourceforge.net/sourceforge/mrbayes/mrbayes-3.1.2.tar.gz
            Attempting to download from alternate mirror.

Download Failed: ftp://ftp.mirrorservice.org/sites/downloads.sourceforge.net/m/mr/mrbayes/mrbayes/3.1.2/mrbayes-3.1.2.tar.gz

            Downloading of needed test files failed.
```

The [SourceForge page](https://sourceforge.net/projects/mrbayes/files/) now mentions the project has moved to GitHub:

> The source is available for download at https://github.com/NBISweden/MrBayes

**Comment by michaellarabel** [comment]
When next running PTS, pts/mrbayes-1.3.2 is now used and that has updated the download URLs to my own mirror of the file to circumvent this issue.

**Comment by adatum** [comment]
>   When next running PTS

Do you mean a future version?

**Comment by michaellarabel** [comment]
As long as you have an Internet connection, PTS obtains the test profile meta-data via OpenBenchmarking.org... Well, can remain cached on local system up to 24~48 hours. If you try running mrbayes again and it's still using -1.3.1. Run `phoronix-test-suite openbenchmarking-refresh` to obtain the latest test profile data that will then make the latest-1.3.2 to force the refresh of the cache.
