### ISSUE TITLE
phoronix-test-suite run fails if test is not yet installed

### ISSUE THREAD

**Issue by lsandoval** [phoronix-test-suite/phoronix-test-suite#287]
In case test is not installed, 'phoronix-test-suite run' should install (prompting the user, as it is right now) and executed the test. However, the executing phase never happens, because run parameters are somehow already consumed  by the installation phase.

For example, I have no pts/multichase installed:

% phoronix-test-suite run pts/multichase

[PROBLEM] pts/multichase-1.0.2 is not installed. 
    Would you like to stop and install these tests now (Y/n): Y

Phoronix Test Suite v8.0.1

    To Install:    pts/multichase-1.0.2

    Determining File Requirements ........................................................................................................................................................................................................
    Searching Download Caches ............................................................................................................................................................................................................

    1 Test To Install
        1 File In Cache [0.02MB]
        5MB Of Disk Space Is Needed

    pts/multichase-1.0.2:
        Test Installation 1 of 1
        1 File Needed [0.02 MB / 1 Minute]
        Copying From Cache: multichase-1.tar.bz2                                                                                                                                                                                  [0.02MB]
        Installation Size: 5 MB
        Installing Test @ 12:12:17

\[PROBLEM\] You must enter at least one test, suite, or result identifier to run.

**Comment by lsandoval** [comment]
Easy fix: return non-zero if test is not installed (so user needs to install it first)
Better fix (for the user): install it and run it. 

I wait for others to comment it.

**Comment by michaellarabel** [comment]
This issue should be fixed by https://github.com/phoronix-test-suite/phoronix-test-suite/commit/a5b88d5f48b5568bc2ce72132444f905eee00330, a small behavioral regression now fixed ahead of PTS 8.2. When `run` on a test not installed and opting for installing it, the run process will properly continue after the test installation.

**Comment by lsandoval** [comment]
Great, thanks @michaellarabel
