### ISSUE TITLE
Docker container phoronix/pts needs CPU with SSE4.1

### ISSUE THREAD

**Issue by hejnm1am** [phoronix-test-suite/phoronix-test-suite#288]
Docker image phoronix/pts is crashing on AMD APU processor (PC Engines APU machine) because of illegal instruction. This is because underlying Linux distro needs SSE4.1 instruction set.

It would be nice if you would remove this constraint.

Standalone pts is running just fine.

from **/proc/cpuinfo**
```
model name      : AMD G-T40E Processor
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf pni monitor ssse3 cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch ibs skinit wdt hw_pstate vmmcall arat npt lbrv svm_lock nrip_save pausefilter

```
**Steps to reproduce**
`docker run -it phoronix/pts`
will crash and **core** file is created inside the docker container

**Steps to show the instruction:**
```
gdb
(gdb) set solib-absolute-prefix phoronix_img/lib64
(gdb) set solib-search-path phoronix_img/lib64
(gdb) file ./bash
Reading symbols from ./bash...(no debugging symbols found)...done.
(gdb) core-file ./core
warning: core file may not match specified executable file.
[New LWP 1]
Core was generated by `/bin/sh'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00007f61df348d6d in ?? () from phoronix_img/usr/lib64/libc-2.28.so

layout asm

   +-------------------------------------------------------------------------------------------------------------------------------------------------+
  >|0x7f61df348d6d  pmovsxdq %xmm0,%xmm1                                                                                                             |
   |0x7f61df348d72  paddq  %xmm4,%xmm1                                                                                                               |
   |0x7f61df348d76  psrldq $0x8,%xmm0                                                                                                                |
   |0x7f61df348d7b  psllq  $0x3,%xmm1         

```

pmovsxdq is SSE4.1 instruction in dynamic library **libc-2.28.so**

**Comment by michaellarabel** [comment]
There are no plans at this point to support SSE4.1-less CPUs with the PTS Docker image unless a commercial need arises or similar, given the prevalence of SSE4.1 hardware and all of our validation machines having SSE4.1 and the SSE version being supported by Intel CPUs for over a decade.

The Phoronix Test Suite itself can obviously run fine on CPUs lacking SSE4 and if desiring to user Docker you can use the ubuntu/arch/opensuse or any number of other Linux distributions on Docker Hub and then just run the Phoronix Test Suite script from there.
