### ISSUE TITLE
Installing dependencies fails if no 'sudo' is installed

### ISSUE THREAD

**Issue by bperel** [phoronix-test-suite/phoronix-test-suite#293]
I'm running Phoronix from inside an Ubuntu Docker container where no 'sudo' is installed.

I'm trying to install a suite that requires dependencies cmake, curl, git and opencv.

Here is the log :
```
The following dependencies are needed and will be installed: 

- libcurl3
- curl
- libcurl4-openssl-dev
- cmake
- cmake-data
- libopencv-dev
- git-core
- mesa-utils
- unzip
- apt-file
- unzip

This process may take several minutes.
E: Unable to correct problems, you have held broken packages.
/usr/share/phoronix-test-suite/pts-core/external-test-dependencies/scripts/install-ubuntu-packages.sh: 24: /usr/share/phoronix-test-suite/pts-core/external-test-dependencies/scripts/install-ubuntu-packages.sh: --: not found
Reading package lists...
Building dependency tree...
Reading state information...
unzip is already the newest version (6.0-21ubuntu1).
mesa-utils is already the newest version (8.4.0-1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cmake : Depends: libcurl4 (>= 7.16.2) but it is not going to be installed
 curl : Depends: libcurl4 (= 7.58.0-2ubuntu3.2) but it is not going to be installed
 libcurl4-openssl-dev : Depends: libcurl4 (= 7.58.0-2ubuntu3.2) but it is not going to be installed

There are dependencies still missing from the system:
- CMake
- Curl
- Git
- OpenCV
```

I think that wrapping [install-ubuntu-packages.sh](https://github.com/phoronix-test-suite/phoronix-test-suite/blob/7b2446ee52c0f9cf00dff8f31bd9a3182713c794/pts-core/external-test-dependencies/scripts/install-ubuntu-packages.sh#L24) with an if/else and run the command without $ROOT if that variable isn't set should fix the issue.

**Comment by michaellarabel** [comment]
What version of PTS are you using? If you are using phoronix-test-suite from Ubuntu repositories, it's years outdated and would recommend not using it.

But the install-ubuntu-packages script in the past number of recent versions has that if [ `whoami` = "root" ] right away in the script and will then call apt-get straight-away, which was added to workaround sudo not being present. Or are you trying to run it from Docker as a non-root user?

**Comment by bperel** [comment]
I'm using version 8.0.1 and running Docker as root.

You're right that there is a `if [ whoami = "root" ]` condition at the beginning of the script, but line 24 is executed afterwards in any case and will fail if the user is root since `$ROOT` is not defined in that case.

So I would say that either line 24 should be moved after line 11 (it doesn't make sense to use the `$ROOT` variable in the other cases), or it should be wrapped like I suggested in my previous message.

**Comment by michaellarabel** [comment]
Ah right I see what you are saying now. Will get that cleaned up for the next release. Thanks.

**Comment by michaellarabel** [comment]
This should be fixed with the latest Git, thanks.
