### ISSUE TITLE
auto-disk-mount-points path error

### ISSUE THREAD

**Issue by ilciko** [phoronix-test-suite/phoronix-test-suite#294]
Hello,
on fio, the test-definition setting:
<Identifier>auto-disk-mount-points</Identifier>
try to run test on "Default Test Directory" as path,
        **1: Default Test Directory**
        2: /
        3: /raid1
        4: Test All Options

removing lines: 309-310
```
					$option_values[] = '';
					$option_names[] = 'Default Test Directory';
```
seems to prevent this error.

**Comment by ilciko** [comment]
This occur running test as batch-run cleary.

**Comment by michaellarabel** [comment]
What error are you getting with fio?
