### ISSUE TITLE
dev vs stable version comparison issue

### ISSUE THREAD

**Issue by yurikoles** [phoronix-test-suite/phoronix-test-suite#296]
Hi @michaellarabel 
I had tried to [add devel version](https://github.com/Homebrew/homebrew-core/pull/30344) to brew formula but it was rejected due to version comparison issue, e.g. `8.2.0m1` is seems to be newer than `8.2.0` in Ruby. Could you please fix that in future releases?

**Comment by michaellarabel** [comment]
Hi @yurikoles what are you looking for as far as a fix? In your packaging are you able to have it marked as 8.2.0-m1 or something? (Don't really touch Ruby much so not sure how it's version comparisons work...)

**Comment by yurikoles** [comment]
One of workarounds is to use odd/even for unstable/stable like GNOME and others.

**Comment by yurikoles** [comment]
@ilovezfs could you suggest something on this issue?

**Comment by yurikoles** [comment]
Anyway, `brew` had deprecated devel releases, so for now we have stable and HEAD, which is current master.
