### ISSUE TITLE
Where can I found why these cases fail? 

### ISSUE THREAD

**Issue by HaHoYou** [phoronix-test-suite/phoronix-test-suite#301]
Some case fails without error message: 
![fail](https://user-images.githubusercontent.com/34019119/47279540-5fc8ab80-d604-11e8-8a05-ff62da11f0ad.png)
And there is no this case error message in the log folder: ~\.phoronix-test-suite\test\results\df\
![log](https://user-images.githubusercontent.com/34019119/47279542-60614200-d604-11e8-9ecc-f3a9b506bd90.jpg)
Where can I found why these cases fail?

**Comment by michaellarabel** [comment]
You can use `phoronix-test-suite debug-run` and also look in ~/.phoronix-test-suite/installed-tests/

A guess is that you have some libssl*-dev issues, as on Ubuntu some libssl1.0-dev vs. libssl-dev package collission can cause some build issues for John The Ripper.

**Comment by HaHoYou** [comment]
![image](https://user-images.githubusercontent.com/34019119/47346288-6710b780-d6df-11e8-9a9b-23fc8d71da4d.png)
Here is the detail. Is that because in the guest OS?

**Comment by HaHoYou** [comment]
Hello? There is no libssl* collission. And the details only have "segmentation fault".

**Comment by michaellarabel** [comment]
As the segmentation fault is from the program under test (John The Ripper) and not Phoronix Test Suite, you would need to manually debug that segmentation fault using GDB or similar to see why it's producing a segmentation fault on your system.
