### ISSUE TITLE
Misidentified PROCESSOR

### ISSUE THREAD

**Issue by jurobystricky** [phoronix-test-suite/phoronix-test-suite#302]
When running PTS on Linux/arm64v8:

PTS_VERSION = 8.0.1
PTS_CORE_VERSION = 8010
PTS_CODENAME = AREMARK
PTS_RELEASE_DATE = 20180605
PTS_IS_CLIENT = 1
PTS_IS_WEB_CLIENT = 
PTS_IS_DEV_BUILD = 
PTS_PHP_VERSION = 7.2.9

$ phoronix-test-suite diagnostics

identifies CPU incorrectly as:
PROCESSOR = SiFive RISC-V (4 Cores)

These are correct, though:
MOTHERBOARD = AMD Seattle v1.0 (10:18:39 BIOS)
CHIPSET = AMD Device 1a00

FWIW, cat /proc/cpuinfo  shows:
processor       : 0
BogoMIPS        : 500.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

processor       : 1
BogoMIPS        : 500.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

processor       : 2
BogoMIPS        : 500.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

processor       : 3
BogoMIPS        : 500.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

**Comment by michaellarabel** [comment]
If you pull from PTS Git is it correct? I uncovered an issue a few weeks ago after the introduction of the SiFive check that some ARM boards got misidentified, should have been fixed in Git though.

**Comment by jurobystricky** [comment]
Thanks, I will get back to you once I test it.

**Comment by jurobystricky** [comment]
With 
PTS_VERSION = 8.2.0

I get correct CPU:
PROCESSOR = ARMVv8 Cortex-A57 (4 Cores)

Thanks!
