### ISSUE TITLE
CSGO benchmark doesn't seem to work with latest update

### ISSUE THREAD

**Issue by egee-irl** [phoronix-test-suite/phoronix-test-suite#304]
CSGO got a big update recently that updated the UI, among other things. I'm not 100% sure if the update caused the breakage but the CSGO benchmark totally does not work for me. Running the benchmark will launch CSGO but all 3 test runs will fail before the game actually launches.

Specs:
```
  OPERATING SYSTEM:   openSUSE 15.0
    Kernel:           4.12.14-lp150.12.19-default (x86_64)
    Desktop:          GNOME Shell 3.26.2
    Display Server:   X Server 1.19.6
    Compiler:         GCC 7.3.1 20180323 [gcc-7-branch revision 258812]
```

**Comment by michaellarabel** [comment]
A recent CS:GO update broke the reporting. pts/csgo-1.6.0 is now available that works around this reporting and also makes use of a new time demo, etc.
