### ISSUE TITLE
set don't down the lastest package from openbenchmarking

### ISSUE THREAD

**Issue by ayiyaliing** [phoronix-test-suite/phoronix-test-suite#306]
Hi, 
I want to update the pts.index and keep the old package, I set as follows, but it doesnt' work, how?
` /var/lib/phoronix-test-suite/pts-core/static/user-config-defaults.xml

<OpenBenchmarking>

                        <AnonymousUsageReporting>TRUE</AnonymousUsageReporting>

                        <IndexCacheTTL>0</IndexCacheTTL>

                        <AlwaysUploadSystemLogs>FALSE</AlwaysUploadSystemLogs>

                </OpenBenchmarking>`

Thanks

**Comment by michaellarabel** [comment]
You can run `phoronix-test-suite openbenchmarking-refresh` to initiate a manual update of your test metadata.

**Comment by ayiyaliing** [comment]
Is there a way if I use batch-benchmarking ,also don’t pull the latest package




| |
李婧
邮箱：ayiyalijing@126.com
|

签名由 网易邮箱大师 定制

On 11/12/2018 18:29, Michael Larabel wrote:

You can run phoronix-test-suite openbenchmarking-refresh to initiate a manual update of your test metadata.

**Comment by michaellarabel** [comment]
You could just run phoronix-test-suite openbenchmarking-refresh as part of your script prior to any batch* command. The Phoronix Test Suite will download all of the test profiles as need be but doesn't preemptively download all test profiles since there are more than a thousand combinations. But if you desire the test packages to be cached locally you can also run `phoronix-test-suite make-openbenchmarking-cache`

**Comment by michaellarabel** [comment]
Right when IndexCacheTTL is set to 0, it will only query a new index from OpenBenchmarking.org when manually told to do so `phoronix-test-suite openbenchmarking-refresh`

**Comment by ayiyaliing** [comment]
Michael,  I found this function that it doesn’t work when I set 0 for value , it still can update the pets.index when running batch-benchmarking in old version




| |
李婧
邮箱：ayiyalijing@126.com
|

签名由 网易邮箱大师 定制

On 11/12/2018 21:34, Michael Larabel wrote:

Right when IndexCacheTTL is set to 0, it will only query a new index from OpenBenchmarking.org when manually told to do so phoronix-test-suite openbenchmarking-refresh

**Comment by michaellarabel** [comment]
Ah good catch, the latest Git has now added a change so `openbenchmarking-refresh` should always force an update even if the index TTL is 0.

**Comment by ayiyaliing** [comment]
I mean it can update the pts.index when I set TTL as 0 with batch-benchmarking not or openbenchmarking-refresh in old versions. I think it should not update it when set to 0 for TTL with batch-benchmarking.




| |
李婧
邮箱：ayiyalijing@126.com
|

签名由 网易邮箱大师 定制

On 11/12/2018 22:33, Michael Larabel wrote:

Ah good catch, the latest Git has now added a change so openbenchmarking-refresh should always force an update even if the index TTL is 0.

**Comment by michaellarabel** [comment]
A fix was pushed to Git today for allowing openbenchmarking-refresh to always work when the TTL is 0. But if not using that sub-command, 0 is the intended behavior to never automatically update to the index.

**Comment by ayiyaliing** [comment]
Yes ,the pts.index won’t be update when TTL is 0 in latest git ,but the pts.index is updated in old version. Do you notice this


| |
李婧
邮箱：ayiyalijing@126.com
|

签名由 网易邮箱大师 定制

On 11/12/2018 23:20, Michael Larabel wrote:

A fix was pushed to Git today for allowing openbenchmarking-refresh to always work when the TTL is 0. But if not using that sub-command, 0 is the intended behavior to never automatically update to the index.

**Comment by michaellarabel** [comment]
I am not sure I understand then or you may be experiencing some sort of network issues, on the latest Git (or released copies, if ignoring the 0 TTL), I am not having any issues fetching the latest tests from OpenBenchmarking.org.

**Comment by ayiyaliing** [comment]
Hi Michael, 

>   Installed: pts/gcrypt-1.0.5
    Installed: pts/john-the-ripper-1.6.2
    To Install: pts/x264-2.5.0
    Installed: pts/photo-sample-1.0.1
    To Install: pts/graphics-magick-1.8.0
    Installed: pts/himeno-1.2.0
    Installed: pts/compress-7zip-1.7.0
    Installed: pts/build-apache-1.5.1
    Installed: pts/build-php-1.4.0
    To Install: pts/c-ray-1.2.0
    Installed: pts/compress-pbzip2-1.5.0
    To Install: pts/smallpt-1.1.0
    Installed: pts/bullet-1.2.2
    Installed: pts/compress-gzip-1.2.0
    Installed: pts/crafty-1.4.3
    To Install: pts/openssl-1.11.0
    Installed: pts/pybench-1.1.2
    Installed: pts/nginx-1.2.1
    Installed: pts/apache-1.7.1
    Installed: pts/phpbench-1.1.5
    Installed: pts/sunflow-1.1.2

    Determining File Requirements ...........................................................................................................................................................................................................
    Searching Download Caches ...............................................................................................................................................................................................................

    5 Tests To Install
        6 Files To Download [663MB]
        2677MB Of Disk Space Is Needed

    pts/x264-2.5.0:
        Test Installation 1 of 5
        3 Files Needed [648 MB / 57 Minutes]
        File Found: x264-snapshot-20180925-2245.tar.bz2                                                                                                                                                                              [0.74MB]
        File Found: nasm-2.13.01.tar.bz2                                                                                                                                                                                             [0.92MB]
        Downloading: Bosphorus_1920x1080_120fps_420_8bit_YUV_Y4M.7z                                                                                                                                                                   [646MB]
        Estimated Download Time: 57m 


I set the  <IndexCacheTTL>0</IndexCacheTTL>, but pts still download the package from internet.  in fact, keep the old record in pts.index, shouldn't update from internet, could you have a look the code?

**Comment by ayiyaliing** [comment]
I installed the old version in installed directory, don't want to down the package from internet again, but it doesn't work when I set TTL as 0.

**Comment by michaellarabel** [comment]
The IndexTTL is just about the OpenBenchmarking.org test metadata. From the output you are posting about, it's in reference to downloading a file needed for the test. PTS will download those files when needed if it's not found in the local download-cache, on a Phoromatic Server, etc. If you don't want files downloaded from the Internet at all, you need to set NoInternetCommunication in the XML file, but then you must have the files locally available via one of the many options.

**Comment by ayiyaliing** [comment]
Michael,
The pts.index metadate is like as  version[2.3.2], I also set TTL as 0, but when I run batch-beachmark pts/x264, 

> pts/x264-2.5.0:
    Test Installation 1 of 5
    3 Files Needed [648 MB / 57 Minutes]
    File Found: x264-snapshot-20180925-2245.tar.bz2                                                                                                                                                                              [0.74MB]
    File Found: nasm-2.13.01.tar.bz2                                                                                                                                                                                             [0.92MB]
    Downloading: Bosphorus_1920x1080_120fps_420_8bit_YUV_Y4M.7z                                                                                                                                                                   [646MB]
    Estimated Download Time: 57m 

The lastest packega info updated my pts.index. I think I set TTL as 0, the pts.index shouldn't be update, the version of x264 should be 2.3.2

**Comment by michaellarabel** [comment]
For your benchmark command are you running just "benchmark x264" or "benchmark x264-2.3.2" ?

**Comment by ayiyaliing** [comment]
batch-benchmark pts/x264




| |
李婧
邮箱：ayiyalijing@126.com
|

签名由 网易邮箱大师 定制

On 11/14/2018 17:56, Michael Larabel wrote:

For your benchmark command are you running just "benchmark x264" or "benchmark x264-2.3.2" ?

**Comment by michaellarabel** [comment]
If you use 'batch-benchmark pts/x264-2.3.2' (or any other version number) you can always bind the version used regardless of whether the metadata gets updated or any other outside updates/changes, it will always enforce the version desired.

**Comment by ayiyaliing** [comment]
so even though TTL=0 can’t also control the pts.index not updated,right ?




| |
李婧
邮箱：ayiyalijing@126.com
|

签名由 网易邮箱大师 定制

On 11/14/2018 22:21, Michael Larabel wrote:

If you use 'batch-benchmark pts/x264-2.3.2' (or any other version number) you can always bind the version used regardless of whether the metadata gets updated or any other outside updates/changes, it will always enforce the version desired.

**Comment by michaellarabel** [comment]
I'm not sure I understand your question but if you want to always run a specific version of a test, it's always best you just run TEST-VERSION such as x264-2.3.2 (or pts/x264-2.3.2) to ensure the version is specified will ensure that version is run, regardless of what may be in your OpenBenchmarking.org metadata or future updates to it.

**Comment by ayiyaliing** [comment]
I saw your code ,TTL=0 won’t be updated from internet, is there some wrong thing I understood 


| |
李婧
邮箱：ayiyalijing@126.com
|

签名由 网易邮箱大师 定制

On 11/14/2018 23:15, lijing wrote:
so even though TTL=0 can’t also control the pts.index not updated,right ?




| |
李婧
邮箱：ayiyalijing@126.com
|

签名由 网易邮箱大师 定制

On 11/14/2018 22:21, Michael Larabel wrote:

If you use 'batch-benchmark pts/x264-2.3.2' (or any other version number) you can always bind the version used regardless of whether the metadata gets updated or any other outside updates/changes, it will always enforce the version desired.

**Comment by ayiyaliing** [comment]
Yes I think so ,but you saw my example I pasted above , the x264 version is 2.3.2 in my pts.index but I run the testing again with batch-benchmark after setting TTL as 0 , actually the pts.index is updated from OR, ask for installing to x264-2.5.0
| |
李婧
邮箱：ayiyalijing@126.com
|

签名由 网易邮箱大师 定制

On 11/14/2018 23:27, Michael Larabel wrote:

If you set IndexTTL it won't automatically refresh the OpenBenchmarking.org metadata unless manually forced to OR when updating the PTS client there is also a forced refresh in case any of the data structure changed and to query new tests that might (or not) available in that new version.

**Comment by michaellarabel** [comment]
You can use batch-run if you prefer to only run the version currently installed on the system (over batch-benchmark). But as stated if you want to bind the version running, postfixing it with the -VERSION is the intended workflow. The index metadata will be updated from OpenBenchmarking.org either on timed basis or if set to 0 will be when you upgrade PTS or manually force a refresh. There doesn't appear to be any bug exhibited, just a misunderstanding about the workflow or features.

**Comment by ayiyaliing** [comment]
I understood it , thanks , TTL control automatically action 


| |
李婧
邮箱：ayiyalijing@126.com
|

签名由 网易邮箱大师 定制

On 11/14/2018 23:27, Michael Larabel wrote:

If you set IndexTTL it won't automatically refresh the OpenBenchmarking.org metadata unless manually forced to OR when updating the PTS client there is also a forced refresh in case any of the data structure changed and to query new tests that might (or not) available in that new version.
