### ISSUE TITLE
Installing Phoronix latest version

### ISSUE THREAD

**Issue by nehajkps** [phoronix-test-suite/phoronix-test-suite#308]
Hello,

I'm running a centos 6 VM where I'd like to run the phoronix test benchmarking. I'm not sure how to install that on my VM/what commands to use to install the latest release of 8.4.0. I believe I have 8.2.0 right now. But I'm not sure how to install the latest one so as to avoid running into problems while testing. Thank you for help in advance.

**Comment by michaellarabel** [comment]
The easiest way to avoid any possible collisions with an existing install would just be to:

git clone https://github.com/phoronix-test-suite/phoronix-test-suite.git
cd phoronix-test-suite
./phoronix-test-suite <commands>

It's as easy as that. With having already been using 8.2, the necessary dependencies should already be installed.

**Comment by nehajkps** [comment]
Thank you for your help Michael.
