### ISSUE TITLE
Phoronix Test Results

### ISSUE THREAD

**Issue by nehajkps** [phoronix-test-suite/phoronix-test-suite#310]
Hello, I'm just curious to know that when looking at the phoronix test results on openbenchmarking.org website, the graph that we get of our test result states something like "seconds, less is better" or "seconds, more is better" - this just means that whichever is less/more in that comparison is better correct? So if you're testing different VM's performance and run a networking test, let's say, and whoever's numbers come out to be low, that system would be better than the other? Just wanted to confirm this is how it is. Thank you

**Comment by michaellarabel** [comment]
Yes, "less is better" means the lower the score is faster than a number with higher score. The opposite for "higher is better" with higher score means better performance.
