### ISSUE TITLE
luajit test downloads incorrect version for aarch64

### ISSUE THREAD

**Issue by swalk-cavium** [phoronix-test-suite/phoronix-test-suite#311]
$ ./phoronix-test-suite run luajit
...
        Installation Size: 1 MB
        Installing Test @ 16:01:56
            The installer exited with a non-zero exit status.
            ERROR: lj_arch.h:294:2: error: #error "No target architecture defined"
            LOG: ~/.phoronix-test-suite/installed-tests/pts/luajit-1.0.1/install-failed.log

luajit is only ported to aarch64 on the v2.1 branch.

**Comment by michaellarabel** [comment]
The test profile will be updated against LuaJIT 2.1.0 as soon as the stable 2.1 release occurs, thanks.

**Comment by swalk-cavium** [comment]
There is some strangeness with this particular package.  I don't know if your
configuration information can capture this level of detail, but the aarch64 port
has been available for quite a while.  Some distributions have taken to deploying the
beta version or even forking the repo.

This site was pointed out to me by myfreeweb and is useful for which version is shipped with
various flavors of linux.

https://repology.org/metapackage/luajit/versions

**Comment by michaellarabel** [comment]
With unfortunately no LuaJIT 2.1.0 release yet or even any new test release, I've gone ahead and updated the test profile against the current LuaJIT v2.1 development code, which has the AArch64 support.

The new test profile is pts/luajit-1.1.0 that has the support and I've verified it works at least with my AArch64 hardware locally.
