### ISSUE TITLE
blogbench fails on aarch64

### ISSUE THREAD

**Issue by swalk-cavium** [phoronix-test-suite/phoronix-test-suite#313]

**Comment by swalk-cavium** [comment]
./phoronix-test-suite run blogbench
...
    pts/blogbench-1.0.1:
        Test Installation 1 of 1
        1 File Needed [0.12 MB / 1 Minute]
        File Found: blogbench-1.0.tar.gz                                                                            [0.12MB]
        Installation Size: 1 MB
        Installing Test @ 14:19:02
            The installer exited with a non-zero exit status.
            ERROR: cannot guess build type; you must specify one
            LOG: ~/.phoronix-test-suite/installed-tests/pts/blogbench-1.0.1/install-failed.log


    [PROBLEM] pts/blogbench-1.0.1 is not installed.

**Comment by michaellarabel** [comment]
The AArch64 support should be working in pts/blogbench-1.1.0 which updates against the latest BlogBench upstream release and also added in an explicit check allowing it to build and run on AArch64 (at least with my initial testing on Ampere + RHEL7).
