### ISSUE TITLE
compress-lzma fails to install on aarch64

### ISSUE THREAD

**Issue by swalk-cavium** [phoronix-test-suite/phoronix-test-suite#314]
./phoronix-test-suite run compress-lzma

    pts/compress-lzma-1.3.0:
        Test Installation 1 of 1
        2 Files Needed [119 MB / 1 Minute]
        Downloading: lzma-4.32.7.tar.gz                                                                     [0.46MB]
        Estimated Download Time: 1m ................................................................................
        Downloading: linux-4.0.1.tar.gz                                                                      [119MB]
        Estimated Download Time: 1m ................................................................................
        Installation Size: 0.7 MB
        Installing Test @ 07:56:05
            The installer exited with a non-zero exit status.
            ERROR: cannot guess build type; you must specify one
            LOG: ~/.phoronix-test-suite/installed-tests/pts/compress-lzma-1.3.0/install-failed.log

UNAME_MACHINE = aarch64
UNAME_RELEASE = 4.4.0-138-generic
UNAME_SYSTEM  = Linux
UNAME_VERSION = #164-Ubuntu SMP Tue Oct 2 17:15:48 UTC 2018
configure: error: cannot guess build type; you must specify one
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
~/.phoronix-test-suite/installed-tests/pts/compress-lzma-1.3.0/install-failed.log

**Comment by michaellarabel** [comment]
The upstream lzma sources appear to still have troubles building for AArch64. However, I have now flagged the compress-lzma test profile as deprecated as of v1.3.1, so it will no longer show up by default in the Phoronix Test Suite / OpenBenchmarking.org listings, etc. As there are much better options like compress-zstd, compress-xz, and even compress-gzip for being more relevant, more aggressive for today's hardware, etc than LZMA. (Those other compression programs should also play nicely on AArch64.)
