### ISSUE TITLE
Dbench not installing on Centos6.10

### ISSUE THREAD

**Issue by nehajkps** [phoronix-test-suite/phoronix-test-suite#315]
Hello,
I'm not able to install pts/dbench on my machine running Centos6.9. I'm getting the following error on running the command: phoronix-test-suite debug-install pts/dbench : 

========================================
Installing Test: pts/dbench-1.0.0
========================================

========================================
Downloading Files: pts/dbench-1.0.0
========================================

dbench-4.0/
dbench-4.0/COPYING
dbench-4.0/INSTALL
dbench-4.0/Makefile.in
dbench-4.0/README
dbench-4.0/autogen.sh
dbench-4.0/child.c
dbench-4.0/client.txt
dbench-4.0/config.h.in
dbench-4.0/configure.in
dbench-4.0/dbench.1
dbench-4.0/dbench.c
dbench-4.0/dbench.h
dbench-4.0/fileio.c
dbench-4.0/install-sh
dbench-4.0/io.c
dbench-4.0/mkproto.pl
dbench-4.0/proto.h
dbench-4.0/snprintf.c
dbench-4.0/sockio.c
dbench-4.0/socklib.c
dbench-4.0/system.c
dbench-4.0/tbench_srv.c
dbench-4.0/util.c
./autogen.sh: /home/linuxbrew/.linuxbrew/bin/autoheader: /usr/bin/perl: bad interpreter: No such file or directory
/home/centos/.phoronix-test-suite/test-profiles/pts/dbench-1.0.0/install.sh: line 8: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.

The installer exited with a non-zero exit status.

LOG: ~/.phoronix-test-suite/installed-tests/pts/dbench-1.0.0/install-failed.log

**Comment by michaellarabel** [comment]
Do you have perl installed on your system?

**Comment by nehajkps** [comment]
no. is that the only dependency i would need?

**Comment by michaellarabel** [comment]
Well that is the only error output so far... "/usr/bin/perl: bad interpreter: No such file or directory" So you can install perl and then see if it works successfully or if some other error is output.
