### ISSUE TITLE
Phoronix test suite crash

### ISSUE THREAD

**Issue by SLMatlabUser** [phoronix-test-suite/phoronix-test-suite#319]
Hi,

I just installed the Phoronix Test Suite on a SL7.5 system. But when I try to run any test, I get an error like this (it may happen right away or after 5-10-15min of download time):

[Data@localhost phoronix-test-suite]$ sudo phoronix-test-suite benchmark c-ray

Phoronix Test Suite v8.4.0

    To Install:    pts/c-ray-1.2.0

    Determining File Requirements .......................................................................................................................
    Searching Download Caches ...........................................................................................................................

    1 Test To Install
        1 File To Download [0.22MB]
        6MB Of Disk Space Is Needed

    pts/c-ray-1.2.0:
        Test Installation 1 of 1
        1 File Needed [0.22 MB]
        Downloading: c-ray-1.1.tar.gz                                                                                                            [0.22MB]
        Downloading ..................................................................................................................................../bin/phoronix-test-suite: line 279: 11752 Segmentation fault      (core dumped) $PHP_BIN pts-core/phoronix-test-suite.php $@

The error appears to stem from the 'php-cli-5.4.16-46.el7' package. It says 'php killed by SIGSEVG'.

I tried updated the  php package(s) or downgrading them, nothing works.

How do I fix this error ?

Thanks,

2) [root@localhost Downloads]# phoronix-test-suite network-info

Local IP:                          192.168.1.65
Interface:                         enp5s0
Network MAC:                       10:7b:44:93:b3:20
Wake On LAN:                       enp5s0: pumbg
Can Reach Phoronix-Test-Suite.com: YES
Can Reach OpenBenchmarking.org:    YES
Can Reach Phoronix.net:            YES

3) the output of 

[root@localhost Downloads]# phoronix-test-suite php-conf

PHP:             5.4.16
PHP VERSION ID:  50416
PHP BINARY:      php

MAIN CAPABILITY CHECK: 
PRESENT - DOM       The Document Object Model is required for XML operations.
PRESENT - ZIP       ZIP support is required for file compression.
PRESENT - JSON      JSON support is required for OpenBenchmarking.org.
PRESENT - SimpleXML SimpleXML is required for XML operations.
PRESENT - OpenSSL   OpenSSL support is recommended to support HTTPS traffic.
PRESENT - GD        The GD library is recommended for improved graph rendering.
PRESENT - Zlib      The Zlib extension can be used for greater file compression.
PRESENT - Bzip2     The bzcompress/bzip2 support can be used for greater file compression.
PRESENT - SQLite3   SQLite3 is required when running a Phoromatic server.
PRESENT - PCNTL     PCNTL is highly recommended as it is required by some tests.
PRESENT - POSIX     POSIX support is highly recommended.
PRESENT - CURL      CURL is recommended for an enhanced download experience.
PRESENT - Sockets   Sockets is needed when running the Phoromatic Server.
PRESENT - Readline  Readline support is useful for tab-based auto-completion support.

OPTIONAL FUNCTION CHECKS: 
cli_set_process_title     MISSING
ctype_alnum               PRESENT
ctype_digit               PRESENT
curl_init                 PRESENT
filter_var                PRESENT
finfo_open                PRESENT
gzcompress                PRESENT
gzdeflate                 PRESENT
gzinflate                 PRESENT
hash_file                 PRESENT
imageantialias            PRESENT
imagecreatefromgif        PRESENT
imagecreatefrompng        PRESENT
imagecreatefromstring     PRESENT
imagepng                  PRESENT
imagettftext              PRESENT
json_decode               PRESENT
pcntl_fork                PRESENT
pcntl_signal              PRESENT
posix_getpid              PRESENT
posix_getpwuid            PRESENT
posix_getuid              PRESENT
posix_isatty              PRESENT
posix_kill                PRESENT
posix_setsid              PRESENT
preg_replace              PRESENT
simplexml_load_string     PRESENT
socket_create_listen      PRESENT
sqlite_escape_string      MISSING
ssh2_connect              MISSING
stream_context_set_params PRESENT
timezone_name_from_abbr   PRESENT
zip_open                  PRESENT

**Comment by michaellarabel** [comment]
This is due to a bug introduced in upstream RHEL7.6 that is now part of the SL/CentOS packages... The bug is due to an issue in its PHP CURL support causing a segmentation fault.

If you pull from Phoronix Test Suite Git, there is a workaround in place (basically avoiding the CURL codepath if the OS has a " 7" in it...) So that works around the problem until Red Hat has fixed the issue. PTS 8.4.1 will be out today if you prefer using a tagged release instead, was just finishing up preparations for that point release.

**Comment by SLMatlabUser** [comment]
So I should install PTS 8.4.1 instead and that will fix the bug ?

Could you please tell me exactly what steps I should follow, I am completely new to this.

**Comment by michaellarabel** [comment]
Yes if you upgrade to PTS Git or 8.4.1, the issue is worked around (it just uses a different code path to avoid the RHEL bug). The 8.4.1 packages will be available shortly so you can set it up however you originally deployed PTS.

**Comment by SLMatlabUser** [comment]
1) Do I need to remove PTS 8.4.0 first and if yes, what are the commands on SL7 ?

2) What is the difference between PTS Git and PTS 8.4.1 ?

Many thanks,

Victor

**Comment by michaellarabel** [comment]
You can install over 8.4.0 fine. 8.4.1 and Git are the same right now sans just needing to push the updated documentation that relabels 8.4.0 -> 8.4.1.
