### ISSUE TITLE
Installation of test pts/crafty-1.4.3 failed in aarch64 platform

### ISSUE THREAD

**Issue by ossdev07** [phoronix-test-suite/phoronix-test-suite#320]
While installing test pts/crafty-1.4.3 in aarch64 platform facing below issues:
 pts/crafty-1.4.3:
        Test Installation 1 of 1
        1 File Needed [0.41 MB / 1 Minute]
        File Found: crafty-25.2.zip                                                                                                   [0.41MB]
        Installation Size: 6 MB
        Installing Test @ 13:34:17
            The installer exited with a non-zero exit status.
            ERROR: gcc: error: unrecognized command line option '-mpopcnt'
            LOG: /var/lib/phoronix-test-suite/installed-tests/pts/crafty-1.4.3/install-failed.log

In x86-64 platform it is successfully installed. Referred link https://www.cleancss.com/explain-command/gcc/5691 , it suggests that -mpopcnt is for i386 or x86-64 platform. Please suggest a way on installing this test in aarch64 platform.

**Comment by rhenwood-arm** [comment]
hi @ossdev07,

As you've discovered popcnt does not make sense for Arm as you telling the compiler to use the "popcnt" instruction in SSE4.2 for x86.

This is a good reference as well: http://man7.org/linux/man-pages/man1/gcc.1.html

I suggest you remove this flag at the moment.

**Comment by ossdev07** [comment]
@rhenwood-arm Thanks for the suggestion. Will remove and run it again.

**Comment by ossdev07** [comment]
Removed mpopcnt flag and re-ran again , facing below issue:

**pts/crafty-1.4.3:**
Test Installation 1 of 1
1 File Needed [0.41 MB / 1 Minute]
File Found: crafty-25.2.zip [0.41MB]
Installation Size: 6 MB
Installing Test @ 15:22:13
The installer exited with a non-zero exit status.
ERROR: lock.h:66:3: error: impossible constraint in 'asm'
LOG: /var/lib/phoronix-test-suite/installed-tests/pts/crafty-1.4.3/install-failed.log 

Please suggest on this issue. Thanks in advance.

**Comment by markku63** [comment]
I hit this issue while benchmarking my new Pi4. Crafty uses inline x86_64 assembly code in files lock.h, tbprobe.c and vcinline.h. This makes it unusable on ARM or any other non-Intel architecture. Does the Phoronix Test Suite have any mechanism to indicate architecture compatibility of  test profiles? The documentation doesn't mention anything about that.

**Comment by michaellarabel** [comment]
I've been waiting to see if Crafty upstream would add support for ARM or other architectures, but considering now, pts/crafty-1.4.5 is now set that limits the test for showing up on x86/x86_64. Thanks and sorry for the delay.
