### ISSUE TITLE
Windows: does not handle whitespce in path

### ISSUE THREAD

**Issue by Ejdesgaard** [phoronix-test-suite/phoronix-test-suite#321]
Running Windows 10 1809 x86_64
Phoronix test suite 8.4.1

1: Run A Test / Benchmark
2: Run A Suite      [A Collection Of Tests]
3: Run A Stress Test      [Concurrent Benchmarks For Heavy System Load]
4: Show System Hardware / Software Information
5: Show Available System Sensors
6: List Available Tests
7: List Recommended Tests
8: Search Tests / Suites / Results
9: Exit
Select Task: 1

1:  Apache Benchmark    -
2:  Caffe               -
3:  Darktable           - System
4:  Diskspd             - Disk
5:  Ethereum Ethminer   - System
6:  Euler3D             - System
7:  GIMP                - System
8:  IOzone              - Disk
9:  LZMA Compression    -
10: OpenSSL             -
11: OpenSSL             - Processor
12: PBZIP2 Compression  -
13: Redis               -
14: Redis               - System
15: SQLite              -
16: Tesseract OCR       - System
17: WinSAT              - System
18: Zstd Compression    - Processor
** Multiple items can be selected, delimit by a comma. **
Select Test(s): 4
    To Install:    windows/diskspd-1.0.0

    Determining File Requirements ..................................................................................
    Searching Download Caches ......................................................................................

    1 Test To Install
        1 File To Download [1.69MB]
        53MB Of Disk Space Is Needed

    windows/diskspd-1.0.0:
        Test Installation 1 of 1
        1 File Needed [1.69 MB / 1 Minute]
        Downloading: Diskspd-v2.0.17.zip                                                                    [1.69MB]
            Download Failed: http://gallery.technet.microsoft.com/DiskSpd-a-robust-storage-6cd2f223/file/152702/1/Diskspd-v2.0.17.zip
            Downloading of needed test files failed.

    [PROBLEM] windows/diskspd-1.0.0 is not installed.
The system cannot find the file file:///C:/Users/foo.

Fails because path is "file:///C:/Users/foo bar" instead of the above.

**Comment by michaellarabel** [comment]
As of https://github.com/phoronix-test-suite/phoronix-test-suite/commit/0a7b4d5423d3d30d9f8939adbe4cc664b9027561 for PTS 8.6, the Phoronix Test Suite should be working fine on Windows when there are spaces in the path. There are a few test profile specific issues I've come across and now updating, but in terms of the Phoronix Test Suite Git itself should now behave better with the whitespaces in the path. Thanks.
