### ISSUE TITLE
Create a Snap package

### ISSUE THREAD

**Issue by vanillajonathan** [phoronix-test-suite/phoronix-test-suite#326]
This can be done using the `snapcraft` command by running `snapcraft init`.
https://docs.snapcraft.io/snapcraft-overview/8940

**Comment by michaellarabel** [comment]
Not sure there would be any benefit to packaging as Snap? It would just complicate the handling of external dependencies, different test profiles would need different rights, including some tests needing to run as root, so the app confinement would be limited, etc.

**Comment by vanillajonathan** [comment]
I see. Good point.
It could run unconfined though.
You're right though, it might not be much benefit to package it as a Snap.
Perhaps users consider Snap a convenient way to install applications. But I am not even sure of that either.
