### ISSUE TITLE
Create a Flatpak package

### ISSUE THREAD

**Issue by vanillajonathan** [phoronix-test-suite/phoronix-test-suite#327]
http://docs.flatpak.org/

**Comment by vanillajonathan** [comment]
PTS doesn't come with any docker file though.

Perhaps this generator could be of use?
https://phpdocker.io/generator

Maybe PTS could come with a Docker file instead?
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Comment by michaellarabel** [comment]
There is the official `phoronix/pts` Docker image. It's on a TODO list to provide a sample Docker file but given the number of different use-cases and workflows for the Phoronix Test Suite, there are already many different PTS Docker setups available by different users/organizations on GitHub and elsewhere. It's quite easy to configure for a desired workflow.

**Comment by aenertia** [comment]
Flatpaks are useful for immutable distros such as silverblue/kinoite etc. Yes I could run it in a distrobox, but it would be far easier to manage i.e versioning from a flatpak and provide a much easier way of shipping plugins/providing a baseline set of libraries.

Podman/docker images are pretty easy to convert, but flatpak provides all the integrations with running systems as well as the 'App store' single click install experience.
