### ISSUE TITLE
pts/fs-mark install failed because of mirror site 

### ISSUE THREAD

**Issue by elly84** [phoronix-test-suite/phoronix-test-suite#332]
Hello.
I tried to install fs-mark 
but I got below message. 
please check below message and mirror site address. 
and  plz let me know how to install fs-mark 

kyumin@kyumin-System-Product-Name:~$ sudo phoronix-test-suite install pts/fs-mark

========================================================================
Phoronix Test Suite v8.4.1

    To Install:    pts/fs-mark-1.0.1

    Determining File Requirements ..........................................
    Searching Download Caches ..............................................

    1 Test To Install
        1 File To Download [0.01MB]
        1MB Of Disk Space Is Needed

    pts/fs-mark-1.0.1:
        Test Installation 1 of 1
        1 File Needed [0.01 MB / 1 Minute]
        Downloading: fs_mark-3.3.tar.gz                             [0.01MB]
            Download Failed: http://download2.polytechnic.edu.na/pub4/sourceforge/f/project/fs/fsmark/fsmark/3.3/fs_mark-3.3.tar.gz
            Attempting to download from alternate mirror.
        Downloading: fs_mark-3.3.tar.gz                             [0.01MB]
            Download Failed: http://www.mirrorservice.org/sites/downloads.sourceforge.net/f/fs/fsmark/fsmark/3.3/fs_mark-3.3.tar.gz
            Downloading of needed test files failed.

**Comment by michaellarabel** [comment]
This was fixed yesterday, actually. If you run `phoronix-test-suite openbenchmarking-refresh` and then run your fs-mark benchmark command instead, it should update to pts/fs-mark-1.0.2 with updated URLs.
