### ISSUE TITLE
Unresolved dependencies on Ubuntu 18.04

### ISSUE THREAD

**Issue by pabloab** [phoronix-test-suite/phoronix-test-suite#334]
Steps to reproduce the bug

1. Ubuntu 18.04 fresh install, updated
1. `sudo apt install phoronix-test-suite`, then run and

> The following PHP extensions are REQUIRED by the Phoronix Test Suite:
>
> DOM      The PHP Document Object Model (DOM) is required for XML operations.
> 
> The following PHP extensions are OPTIONAL but recommended:
> 
> GD       The PHP GD library is recommended for improved graph rendering.
> SQLite3  The PHP SQLite3 extension is required when running a Phoromatic server.
> CURL     PHP CURL is recommended for an enhanced download experience.
> PHP FPDF PHP FPDF is recommended if wishing to generate PDF reports.

Seems a compatibility issue with `php --version`: _PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )_. 

Packages already present but on that PHP version: `php-xml`, `php7.2-xml` (_Note, selecting 'php7.2-xml' instead of 'php-dom'_), `php7.2-gd`, also `libxml` (`php -i | grep libxml`). [Documentation](https://www.phoronix-test-suite.com/documentation/phoronix-test-suite.html) is incomplete and outdated.

**Comment by michaellarabel** [comment]
This is an Ubuntu issue. The `phoronix-test-suite` packages found in the Ubuntu archive are vastly outdated and unmaintained. You can install the Phoronix Test Suite official Debian packages @ http://phoronix-test-suite.com/?k=downloads and will work fine with Ubuntu PHP5/PHP7.

**Comment by pabloab** [comment]
Thank you very much @michaellarabel . There is any plan to offer a PPA? Either way maybe is a good idea to contact Ubuntu maintainers to ask them to remove that (broken) package.

**Comment by michaellarabel** [comment]
No plans to offer a PPA right now. Recently the Ubuntu maintainers did drop the unmaintained package but it's only a change for Ubuntu 19.04 and moving forward but didn't remove it for the existing releases.
