### ISSUE TITLE
Can't login to openbenchmarking.org

### ISSUE THREAD

**Issue by atomsymbol** [phoronix-test-suite/phoronix-test-suite#335]
Hello. I cannot login with the `openbenchmarking-login` command. https://openbenchmarking.org/ login in Google Chrome works fine.

    $ pts openbenchmarking-login
    If you have not already registered for your free OpenBenchmarking.org account, you can do so at https://openbenchmarking.org/
    
    Once you have registered your account and clicked the link within the verification email, enter your log-in information below.
    
    OpenBenchmarking.org User-Name: atomsymbol

    OpenBenchmarking.org Password: 
        [PROBLEM] Account Not Found

**Comment by Calinou** [comment]
With phoronix-test-suite 10.0.1, it works here:

```
❯ phoronix-test-suite openbenchmarking-login



If you have not already registered for your free OpenBenchmarking.org account, you can do so at https://openbenchmarking.org/

Once you have registered your account and clicked the link within the verification email, enter your log-in information below.


OpenBenchmarking.org User-Name: calinou

OpenBenchmarking.org Password: 

The Account Has Been Setup.
```

@atomsymbol Can you still reproduce this with the latest phoronix-test-suite version?.

**Comment by atomsymbol** [comment]
> @atomsymbol Can you still reproduce this with the latest phoronix-test-suite version?

Sorry, I forgot to close this bug. phoronix-test-suite v10.2.0m3 login works fine.
