### ISSUE TITLE
pts/iozone What does the 'iozne' result mean?

### ISSUE THREAD

**Issue by mscraigloewen** [phoronix-test-suite/phoronix-test-suite#336]
Hello,

I'm running a test using the pts/iozone suite. Each result gives me a comparison to: 'iozne', like the following:

```
OpenBenchmarking.org Dynamic Comparison:
MB/s > Higher Is Better
iozne ... 658.01 |======
Result .. 766.70 |=========
Result Perspective: https://openbenchmarking.org/result/1807054-AR-MACH8978670
```

I've tried to look online to find out what the 'iozne' is referring to. I assume it's some kind of standard machine somewhere? I wasn't able to find anything about it.

**What does iozne refer to in these results?**

Thank you!
-Craig

**Comment by mscraigloewen** [comment]
@michaellarabel thank you for your blindingly quick and informative answer! 

So to check my understanding:
**The result seen: 'iozne' is just a similar machine to compare my result towards.**

My only other question is, is there anyway to find out the specs or any other details of this 'iozne' machine?

**Comment by michaellarabel** [comment]
@mscraigloewen yes, your understanding is correct. Albeit in this particular case with iozone not being the most popular/best test, the comparison point is rather poor in just being one system and poorly named, etc.

If clicking on that "result perspective" URL you should be able to see that system's details, e.g. https://openbenchmarking.org/result/1807054-AR-MACH8978670

**Comment by mscraigloewen** [comment]
Ahhh I see. The root of my misunderstanding was seeing: `SAMSUNG MZVLW256HEHP-00000` inside the results as well, and now I can see that in this case it was referring to the disk on the machine (I thought it was the machine name) 

Thanks again for your help! 👍
