### ISSUE TITLE
[pts/fio] fio-run not accepting raw block devices

### ISSUE THREAD

**Issue by devster31** [phoronix-test-suite/phoronix-test-suite#337]
I'm trying to run a `pts/fio` test using raw block devices, which is possible with `fio`, for example like so:
```
fio --filename=/dev/disk/by-id/ata-HGST_HUH728080ALE600_R5G2DRGV --direct=1 --sync=1 --rw=write --bs=4k --numjobs=2 --iodepth=1 --runtime=60 --time_based --group_reporting
```

However it seems the `fio-run` script does not accept them as arguments.
```
Test Run Command: cd /var/lib/phoronix-test-suite/installed-tests/pts/fio-1.11.4/ && ./fio-run randread libaio 0 1 2m /dev/disk/by-id/ata-HGST_HUH728080ALE600_VLHMNLBY 2>&1

fio: /dev/disk/by-id/ata-HGST_HUH728080ALE600_VLHMNLBY is not a directory
fio: failed parsing directory=/dev/disk/by-id/ata-HGST_HUH728080ALE600_VLHMNLBY
fio: job global dropped
```
This seems mainly linked to
```
filename=fiofile
$DIRECTORY_TO_TEST
```

**Comment by michaellarabel** [comment]
At this point the fio test profile is just designed to test folders. If you or anyone wants to extend the test profile to accommodate the configuration for raw block devices, I am happy to accept said patches upstream as long as they don't break the existing support.

**Comment by devster31** [comment]
The combination of `directory` and `filename` in the config seems a bit redundant.
I'm running inside a container, so it's not a particular issue doing the following:
```diff
--- fio-run.bak	2019-02-08 00:19:14.672089983 +0000
+++ fio-run	2019-02-08 00:15:20.704608142 +0000
@@ -3,7 +3,7 @@

 if [ ! "X$6" = "X" ]
 then
-DIRECTORY_TO_TEST="directory=$6"
+DIRECTORY_TO_TEST="$6"
 fi

 echo "[global]
@@ -27,8 +27,7 @@
 disable_lat=1
 disable_clat=1
 disable_slat=1
-filename=fiofile
-$DIRECTORY_TO_TEST
+filename=$DIRECTORY_TO_TEST

 [test]
 name=test
```
seems to work just fine.
I'd be happy to run tests to check whether it breaks anything.

**Comment by michaellarabel** [comment]
Thanks, the pts/fio-1.11.5 test profile is now uploaded and makes those changes.
