### ISSUE TITLE
centos7 - pts/numpy did not produce result

### ISSUE THREAD

**Issue by ifelsefi** [phoronix-test-suite/phoronix-test-suite#338]
Hi

I am not able to produce a result with `pts/numpy`

I opened an issue on [project github site](https://github.com/serge-sans-paille/numpy-benchmarks/issues/8).

```
========================================
Numpy Benchmark (Run 1 of 1)
========================================


Test Run Command: cd /var/lib/phoronix-test-suite/installed-tests/pts/numpy-1.0.5/ && ./numpy  2>&1

Test name :   Avg time ( nanoseconds )

Result Key: #_RESULT_#


Template Line: Total avg time (nanoseconds): #_RESULT_#


Result Parsing Search Key: "Total avg time (nanoseconds):"


Result Line: Total avg time (nanoseconds): 0.00


Test Result Parser Returning: 0


The test run did not produce a result.


Log File At: /var/lib/phoronix-test-suite/installed-tests/pts/numpy-1.0.5/numpy-1.0.5-1551026620-1.log



The following tests failed to properly run:

        - pts/numpy-1.0.5
```

I tested this with python 2.6, 2.7, and various versions of 3.

Has anyone experience the same problem?

**Comment by michaellarabel** [comment]
All the test profile (https://openbenchmarking.org/innhold/cdced17b0e57464787bcc00ca2672de114fc9dc4) is doing is effectively just running the Numpy Python benchmark. So if you are having issues running it on CentOS 7 it's either a CentOS/EL 7 bug or issue within Numpy benchmark code itself. The test does work fine on Ubuntu and various other Linux distributions.

**Comment by ifelsefi** [comment]
My mistake!
