### ISSUE TITLE
Download failed for padman on 8.6.1

### ISSUE THREAD

**Issue by gnthibault** [phoronix-test-suite/phoronix-test-suite#339]
I see something like this:
phoronix-test-suite benchmark pts/cpu
[...]
Download Failed: http://zock-server.de/WoP_1.6/wop-1.5-unified.zip
[...]

**Comment by michaellarabel** [comment]
The World of Padman test profile has been deprecated for over a year now as the game isn't really updated these days and its graphics capabilities haven't been relevant for a decade or more now.

If still interested in running Padman, you can download the files from an alternative mirror (such as outlined https://worldofpadman.net/en/download/ ) and drop it in ~/.phoronix-test-suite/download-cache/ and re-run the benchmark command and it should then get picked up.
