### ISSUE TITLE
Provide an official Docker documentation

### ISSUE THREAD

**Issue by stkac** [phoronix-test-suite/phoronix-test-suite#342]
Hi, I'm looking around for test my linux based machine whit docker but don't see the 'how to' anywhere, someone know how to run the official test suite?

http://www.phoronix-test-suite.com/documentation/

thanks in advance,

**Comment by michaellarabel** [comment]
You should be able to run:

`docker run -it phoronix/pts`

To use the official PTS Docker image and there are also a variety of other unofficial spins out there. Or is there something more specific you are wondering about?

**Comment by stkac** [comment]
I'm looking for work whit it for general propose, and run it as ad-hoc commands like:

`docker run -it phoronix/pts [ad-hoc commands]`

and retrieve info about the command.... But I don't fount anywhere it. I mean, the list of possibles command to append to docker...

Thanks in advance @michaellarabel, your project looks great!

**Comment by michaellarabel** [comment]
You should be able to append any commands that you normally would use for passing to the Phoronix Test Suite, all the standard commands outlined in the documentation.

**Comment by stkac** [comment]
So you mean start using something like this to know all possible test? it's my first time using PST.

```
docker run -it phoronix/pts list-available-tests
docker run -it phoronix/pts auto-compare
```

**I get in each of case:**
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"list-available-tests\": executable file not found in $PATH": unknown.

docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"auto-compare\": executable file not found in $PATH": unknown.
```

**Comment by TeamLinux01** [comment]
It might also be a good idea to create a docker branch, have docker hub point to that branch to auto-build. That way it can pull the README.md from github and put it on hub.docker.com.

Something like what this project does:
https://hub.docker.com/r/adolfintel/speedtest/builds
https://hub.docker.com/r/adolfintel/speedtest/builds

**Comment by h3po** [comment]
+1 from because damn do I want to know why that image is 2.8GB. That is the largest docker image I have ever seen. If I could get the Dockerfile, I might be able to contribute some improvements

**Comment by michaellarabel** [comment]
The Docker build script for the current container (Ubuntu based rather than the prior Clear Linux container that was much larger) has been available via - https://github.com/phoronix-test-suite/phoronix-test-suite/tree/master/deploy/docker

Any pull requests welcome or bug reports for specific issues. Thanks.
