### ISSUE TITLE
Cannot run graphics tests in docker

### ISSUE THREAD

**Issue by adamcavendish** [phoronix-test-suite/phoronix-test-suite#350]
I am trying to install and run graphics tests in docker via command as following:

```
docker run -it --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix phoronix/pts \
  phoronix-test-suite/phoronix-test-suite benchmark pts/unigine-heaven
```

But it threw out the issue that:

```
No display server was found, skipping pts/unigine-heaven-1.6.4
```

Please provide the official Dockerfile so that we may modify based on it.

**Comment by adamcavendish** [comment]
```
docker run -it --privileged -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix phoronix/pts \
  phoronix-test-suite/phoronix-test-suite benchmark pts/unigine-heaven
```

Even with privileged mode, pts also gives `No display server was found` error.

**Comment by michaellarabel** [comment]
There isn't X11 support currently shipped as part of the phoronix/pts docker image. There are though a number of unofficial/third-party PTS Docker images some of which may offer X11 support.
