### ISSUE TITLE
PTS in Android

### ISSUE THREAD

**Issue by 1kapilgupta1** [phoronix-test-suite/phoronix-test-suite#352]
Hi,
I wanted to start work on this for android.
Can you please give me a pointer on that PTS client port done to android? I want to check what all profiles will work on Android.

Thank you.

**Comment by michaellarabel** [comment]
You would need the PHP APK package on an Android device and to run PTS would likely still require a rooted device. I don't believe there is any documentation currently on it and if so would be around a decade old so likely quite outdated.
