### ISSUE TITLE
Batman-origins benchmark stuck at the first run.

### ISSUE THREAD

**Issue by dubigrasu** [phoronix-test-suite/phoronix-test-suite#358]
The phoronix benchmark starts properly, but instead of stopping after the first run and do its multiple runs series, it just hangs after the in-game benchmark stops. Basically the game continues running indefinitely.

Looking at the shell, is supposed to do a "killall -9 BatmanOrigins.exe" so it can be started again. The killall command is indeed executed, but after running the debug benchmark I can see that the "BatmanOrigins.exe" process can not be found, although I can clearly see it running with htop. Even when executing manually the same killall command I receive the same message.

However, if I do a "ps", I notice that the Batman process is listed truncated, more exactly as "**BatmanOrigins.e**".
So if I edit the shell with the truncated name, this time the benchmarks works properly, the game is closed properly and the following runs are executed. The same if do "pkill -9 BatmanOrigins".

I'm running this on Clear Linux, don't know what exactly is at fault, I'm just reporting it here.

**Comment by michaellarabel** [comment]
Yeah something changed recently with SteamPlay~Proton causing this regression as previously it worked fine. Hope to have the time to verify more soon. Thanks.

**Comment by michaellarabel** [comment]
There is a workaround in place with pts/batman-origins-1.6.1 that should now behave nicely with the latest Steam (Play) / Proton. Thanks.
