### ISSUE TITLE
stress-run doesn't support silent runs or batching logic

### ISSUE THREAD

**Issue by seandhaynes** [phoronix-test-suite/phoronix-test-suite#360]
I'm currently using version 8.8.0 of Phoronix:
```
Phoronix Test Suite v8.8.0 (Hvaler)
```

On Debian Stretch with the following tests:
```
build-linux-kernel
c-ray
fio
```

My goal is to run the above tests in a silent/automated operation for long periods of time (potentially days) to stress-test new hardware. 

Looking at documentation and testing options, ```stress-run``` seems perfect. Though  unlike a ```batch-run``` (after a ```batch-setup```, I don't seem to be able to tell the test run manager to use test defaults, and I'm presented with test options on every run:

```
$ TOTAL_LOOP_TIME=120 PTS_CONCURRENT_TEST_RUNS=8 phoronix-test-suite stress-run build-linux-kernel fio c-ray



STRESS-RUN ENVIRONMENT VARIABLES:

PTS_CONCURRENT_TEST_RUNS set; running 8 tests concurrently.


TOTAL_LOOP_TIME set; running tests for 120 minutes



Flexible IO Tester 3.1:
    pts/fio-1.11.5
    Disk Test Configuration
        1: Random Read
        2: Random Write
        3: Sequential Read
        4: Sequential Write
        5: Test All Options
        ** Multiple items can be selected, delimit by a comma. **
        Type:
```

Could you confirm that ```stress-run``` doesn't support being executed silently like ```batch-run```? If so, is this something that could be added? I'm happy to contribute.

**Comment by michaellarabel** [comment]
Hi Sean,

I'm certainly interested in seeing it be fully-automated and should be actually. At last check, it already should be if passing it a suite rather than the individual tests.

If you first run `phoronix-test-suite build-suite` with all the tests you want and then run `TOTAL_LOOP_TIME=120 PTS_CONCURRENT_TEST_RUNS=8 phoronix-test-suite stress-run <your-new-suite-name>` does it behave as desired?

**Comment by seandhaynes** [comment]
Hey @michaellarabel, thanks for coming back so quickly! 

I will attempt to build a suite shortly and let you know how things look.

**Comment by seandhaynes** [comment]
Hi Michael,

So running stress-run with a suite does indeed complete silently, so thanks for that!

Entirely up to you whether you close this or not. I'm happy to look at adding a section in the docs about this, or try and make stress-run

**Comment by seandhaynes** [comment]
Apologies, accidentally hit the "close and comment button".

**Comment by michaellarabel** [comment]
@seandhaynes there is also now a `phoronix-test-suite stress-batch-run` command that will accept tests passed to it and not prompt users about test options but behave like batch mode and run without prompts. Feel free to reopen or new ticket if any issues with that.

**Comment by seandhaynes** [comment]
That's great, I'll give it a try. Thanks very much, @michaellarabel!
