### ISSUE TITLE
Configuration on test results

### ISSUE THREAD

**Issue by Young768** [phoronix-test-suite/phoronix-test-suite#363]
Hi,

Currently, I submit batch run with FORCE_TIMES_TO_RUN =10. It will output the average values of those 10 rounds results. If I want to give up the result from the first test, the final output will only averages the remaining 9 rounds. Can I configure this? Or is there any related file that can help me do this?

Thanks

**Comment by michaellarabel** [comment]
At the moment it's only exposed at the test profile specific level of "IgnoreRuns" toggle to be able to basically drop/discard say the first run or X run. I can see about adding an environment variable to control this at a global run-time level for all test profiles, just never had the use-case previously. Should be fairly trivial to add so long as I find the time in the next day or two. To confirm, basically a IGNORE_RUNS=x where x is relative offset of each run to drop, presumably x=1 most often but could also be a comma delimited list of runs, would that suit your needs?

**Comment by Young768** [comment]
Yep. Because we are concerned that the first test is not stable yet. So we dont want the result from the first run. Where is IGNORE_RUNS=x variable located? I could not find it.

**Comment by michaellarabel** [comment]
"IGNORE_RUNS" is what I should be able to get in Git shortly, just wanted to confirm the intended functionality matches what you would be after.

**Comment by Young768** [comment]
Yep. Many thanks!

**Comment by Young768** [comment]
Hi Michael,

If i want to add some label into the log information, where I can change the code to achieve this? I have a simple solution to get my desire results. I want to also add run # before the final output. For my case, I just write a script to read these output from the screen and ignore the results with run 1.

Estimated Trial Run Count:    6                    
    Estimated Time To Completion: 1 Minute [19:14 UTC] 
        Started Run 1 @ 19:14:23
        Started Run 2 @ 19:14:39
        Started Run 3 @ 19:14:52
        Started Run 4 @ 19:15:05
        Started Run 5 @ 19:15:19
        Started Run 6 @ 19:15:34

    Test: Random Write:
        3584.61
        3584.88
        3621.5
        3638.78
        3631.17
        3607.37

**Comment by Young768** [comment]
@michaellarabel Or can I save these screen results into a local file? So that I can process it. Thanks!

**Comment by michaellarabel** [comment]
In PTS git is now the IGNORE_RUNS functionality.

Regarding your other question, not sure what you mean since the results are always presented in chronological order?
