### ISSUE TITLE
export OMP_NUM_THREADS for all tests with default num_cpus

### ISSUE THREAD

**Issue by jnettlet** [phoronix-test-suite/phoronix-test-suite#365]
Rather than tracking each individual test that supports OpenMP and tweaking the environment per each test, set OMP_NUM_THREADS globally for the entire test run, checking to verify if the user hasn't already set it themselves.  This would simplify maintenance from version to version of tests.

**Comment by michaellarabel** [comment]
Sure thing, should be set by https://github.com/phoronix-test-suite/phoronix-test-suite/commit/6d3c67c5e5f51cbf926066428a94ce7db979a5c0 thanks.
