### ISSUE TITLE
Test run prompts

### ISSUE THREAD

**Issue by Young768** [phoronix-test-suite/phoronix-test-suite#366]
Hi when I ran pts/ffte test, there are prompts:

There are dependencies still missing from the system:
- OpenMPI

1: Ignore missing dependencies and proceed with installation.
2: Skip installing the tests with missing dependencies.
3: Re-attempt to install the missing dependencies.
4: Quit the current Phoronix Test Suite process.
Missing dependencies action: 3

The following dependencies are needed and will be installed: 

- openmpi-devel
- openmpi
- mpich2-devel

This process may take several minutes.
Unable to detect release version (use '--releasever' to specify release version)
Error: There are no enabled repos.

However, it can still produce results. Are there results correct? It seems that the required packages have not been installed.

FFTE 6.0:
    pts/ffte-1.1.0 [Test: N=256, 1D Complex FFT Routine]
    Test 1 of 1
    Estimated Trial Run Count:    6                    
    Estimated Time To Completion: 1 Minute [21:17 UTC] 
        Started Run 1 @ 21:17:02
        Started Run 2 @ 21:17:08
        Started Run 3 @ 21:17:15
        Started Run 4 @ 21:17:21
        Started Run 5 @ 21:17:28
        Started Run 6 @ 21:17:34

    Test: N=256, 1D Complex FFT Routine:
        9038.3666683161
        9081.1521199069
        9086.1972210546
        9103.8634363049
        9057.1267221821
        9097.7258102456

**Comment by michaellarabel** [comment]
What distribution/version are you using? This just looks to be a case of needing to update the file names for the external dependency handling on that distribution.... A.k.a. PTS checking for a particular file for OpenMPI and seeing it's not there so wanting then to install it, but in fact MPI is already installed. So likely just a filename/folder check needing to be updated once knowing what OS/version you are using.

**Comment by Young768** [comment]
Im using Phoronix Test Suite v8.8.1
Running on Clear Linux with kernel 5.1.9

**Comment by Young768** [comment]
@michaellarabel So if i can see the test results, it means they are executed successfully?

**Comment by Young768** [comment]
Hi @michaellarabel a quick question, some tests have two prefix. Are they the same? For example, system/apache and pts/apache.

**Comment by michaellarabel** [comment]
@Young768 you should be able to do "apache" or say "pts/apache", let me know if one or the other isn't picking up.

**Comment by Young768** [comment]
@michaellarabel Hi michale, How can I configure the test running time? I want to monitor the system resource usage during the runtime. But some test is not long enough for me to do that. How can make the running time longer?

**Comment by Young768** [comment]
@michaellarabel I know we can pass FORCE_TIMES_TO_RUN to let it run multiple times. But I want to make it longer for per-run. So it does not waste time on switching.
