### ISSUE TITLE
PPC64 error: [NOTICE] A non well formed numeric value encountered in phodevi_cpu:373

### ISSUE THREAD

**Issue by awilfox** [phoronix-test-suite/phoronix-test-suite#367]
While installing a test on my Talos II:

```
    [NOTICE] A non well formed numeric value encountered in phodevi_cpu:373
```

It seems to have detected the speed properly anyway:

```
System Information


  PROCESSOR:          POWER9 @ 3.00GHz
    Core Count:       16               
    Thread Count:     64               
```

It seems that the issue is because the `clock` line in `/proc/cpuinfo` on ppc64 is formatted as so:

```
clock           : 3000.000000MHz
```

**Comment by michaellarabel** [comment]
https://github.com/phoronix-test-suite/phoronix-test-suite/commit/439d03646b1f632eacc2573e9e175ad043aea2e6 should fix the issue, thanks for reporting.
