### ISSUE TITLE
os-release parser seems to strip non-ASCII Latin characters

### ISSUE THREAD

**Issue by awilfox** [phoronix-test-suite/phoronix-test-suite#368]
I'm the lead of the Adélie Linux distribution, and our é seems to be [giving PTS a bit of an issue](https://openbenchmarking.org/result/1907184-HV-GITTESTTH34):

```
  OPERATING SYSTEM:   Adlie Linux 1.0-BETA3
    Kernel:           4.14.127-mc14-easy-power8 (ppc64)                                                         
    Desktop:          KDE Plasma 5.12.7                                                                         
    Display Server:   X Server 1.20.5                                                                           
    Compiler:         GCC 8.3.0 + Clang 8.0.0                                                                   
```

Our /etc/os-release file can be found [in the adelie-base Git repository](https://code.foxkit.us/adelie/adelie-base/blob/master/tree/etc/os-release):

```sh
NAME=Adélie
VERSION=1.0-beta3
ID=adelie
VERSION_CODENAME=endlesssummer
VERSION_ID=1.0-beta3
PRETTY_NAME="Adélie Linux 1.0-BETA3"
ANSI_COLOR="0;31"
HOME_URL=https://www.adelielinux.org/
SUPPORT_URL=https://support.adelielinux.org/
BUG_REPORT_URL=https://bts.adelielinux.org/post_bug.cgi
```

**Comment by michaellarabel** [comment]
A workaround should now be in place for at least bringing it to Adelie Linux. ASCII characters are just intended for that field to avoid any compatibility issues with the HTML presentation of the data and processing of the data on OpenBenchmarking.org that at least previously was just geared for handling ASCII characters and not properly dealing with non-ASCII characters for time/resource constraints.
