### ISSUE TITLE
Environment Variables can't be exported

### ISSUE THREAD

**Issue by dpdingtaoqb** [phoronix-test-suite/phoronix-test-suite#372]
As in /usr/bin/phoronix-test-suites，env will be exported by pts-core/hooks/startup/*.sh
The Environment Variables won't be exported  using '.' to execute shell script;
Yet using source wil do;

Forgive me for my poor English;

my version:
Phoronix Test Suite v8.8.1 (Hvaler)
centos7 with kernel version 4.14

        for file in pts-core/hooks/startup/*.sh
        do
                ./$file      ------------------> i think  'source ./$file' would be better
        done

**Comment by michaellarabel** [comment]
What sort of environment variables are you trying to pass to PTS from this context? Just trying to understand the best workflow for accomplishing what you are after. Thanks.

**Comment by dpdingtaoqb** [comment]
> What sort of environment variables are you trying to pass to PTS from this context? Just trying to understand the best workflow for accomplishing what you are after. Thanks.

Just want to add some function like "custom the name of merged result" by passing env; 
just thinking manage all my custom env here would be convient; 
In addition to my workflow , I just think the code i pasted can't accomplish to pass the env; 
but the annotation tell me that it will do; maybe source should be the right choice;
