### ISSUE TITLE
pts/fio broken for non-Windows platforms

### ISSUE THREAD

**Issue by paulie-g** [phoronix-test-suite/phoronix-test-suite#373]
```
Download Failed: http://brick.kernel.dk/snaps/fio-3.1.tar.gz
```

Host is down. You are already hosting the windows version on phoronix, which is why this breakage hasn't been discovered. However, for non-windows platforms, it's borked. The canonical download location is: https://github.com/axboe/fio/archive/fio-3.1.tar.gz

I haven't found a way to fix this locally and can't figure out how to submit a change to openbenchmarking.

**Comment by michaellarabel** [comment]
Actually this appears to just have been a temporary outage of the host. When trying that URL for me on multiple systems/connections, it's working fine this evening.

In the future if hitting a similar issue, you can download the file from an alternative mirror and drop it in ~/.phoronix-test-suite/download-cache/ and as long as the hashes match, it will be automatically picked up.
