### ISSUE TITLE
ffio test installation fails

### ISSUE THREAD

**Issue by vojtapolasek** [phoronix-test-suite/phoronix-test-suite#374]
I am running Phoronix Test Suite v8.8.1 (Hvaler)
I am trying to install     pts/fio-1.11.5. It fails with the following:
            ERROR: engines/glusterfs_sync.c:47:9: error: too few arguments to function ‘glfs_fdatasync’
I am running Arch Linux 64 bit.
The installation log is attached.
[install-failed.log](https://github.com/phoronix-test-suite/phoronix-test-suite/files/3613569/install-failed.log)

**Comment by michaellarabel** [comment]
Are you running on Gluster? Looks to be a bug with upstream FIO.

**Comment by vojtapolasek** [comment]
I have gluster installed because it is required by Libvirt but this is a physical machine. I use Libvirt to run virtual machines.  Well in worst case I will just skip this test, I want to do the pts/disk test suite.

**Comment by MauroMombelli** [comment]
I have a different error with PtS v9.0.0: ERROR: crc/../os/os-linux.h:124:19: error: static declaration of ‘gettid’ follows non-static declaration

**Comment by michaellarabel** [comment]
Try running:

phoronix-test-suite openbenchmarking-refresh
phoronix-test-suite benchmark fio

The fio test profile was just updated earlier today with the new version of FIO that looks to correct those build issues.

**Comment by MauroMombelli** [comment]
can confirm is fixed

**Comment by vojtapolasek** [comment]
Hi, unfortunately for Arch Linux it is not fixed. I get the followinig error:
            ERROR: crc/../os/os-linux.h:124:19: error: static declaration of ‘gettid’ follows non-static declaration
log attached.
Version 9.0.1
[install.log](https://github.com/phoronix-test-suite/phoronix-test-suite/files/3980381/install.log)
[install-failed.log](https://github.com/phoronix-test-suite/phoronix-test-suite/files/3980384/install-failed.log)
