### ISSUE TITLE
Docker for windows?

### ISSUE THREAD

**Issue by cagnulein** [phoronix-test-suite/phoronix-test-suite#377]
What about a docker for windows? I would like to make phoronix portable-like. What do you think?

**Comment by michaellarabel** [comment]
Have you tried running the "phoronix/pts" Linux Docker from Windows? Or what is your request?

**Comment by cagnulein** [comment]
@michaellarabel ops no, i didn't know that the Linux docker could work on Windows too :O
I'll give it a try and i'll give you a feedback if it's ok for my needs.
Thanks!

**Comment by cagnulein** [comment]
Ok i will use the linux docker on a livecd, i think it's the best way to make phoronix test suite portable. Thanks :)

**Comment by michaellarabel** [comment]
Okay, also be aware that PTS runs well under Windows Subsystem for Linux WSL2/WSL and the Phoronix Test Suite also runs natively on Windows (though under the native Windows support a smaller selection of tests is available).
