### ISSUE TITLE
john The Ripper installation fail

### ISSUE THREAD

**Issue by MauroMombelli** [phoronix-test-suite/phoronix-test-suite#379]
JtR installation fail with error:

> JtR requires libssl being installed

this looks like an issue with OpenSSL 1.1.0 and can be fixed by changing SSL_library_init with OPENSSL_library_init that should work with old version too

**Comment by michaellarabel** [comment]
This issue I don't believe occurs with newer versions of OpenSSL but rather is an upstream JtR issue anyhow.
