### ISSUE TITLE
For custom php, PHP_BIN environment variable might need to be set. Otherwise getting "PHP 5.2 or newer must be installed"

### ISSUE THREAD

**Issue by yuvilio** [phoronix-test-suite/phoronix-test-suite#38]
I ran into this error when running the main command:

``` bash
$ bin/phoronix-test-suite version

PHP 5.2 or newer must be installed for the Phoronix Test Suite
The PHP command-line package is commonly called php-cli, php5-cli, or php.
For more information visit: http://www.phoronix-test-suite.com/

The command to likely run for your operating system is: 
# apt-get install php5-cli php5-json php5-gd
```

my PHP was installed but it was a custom compiled one:

``` bash
$ which php
/home/yuvilio/apps/php/bin/php
$ php --version
PHP 5.6.2 (cli) (built: Oct 31 2014 20:55:57) 
```

Peeking at the export script I saw that it can use the PHP_BIN variable. Once I set that, it worked. Might be worth throwing that into the docs.

``` bash
$ export PHP_BIN=$(which php)
$ bin/phoronix-test-suite version
Phoronix Test Suite v5.4.0m5 (Lipki)
$ 
```

System tested on:

``` bash
$ uname -a
Linux jinbocho 3.16.0-25-generic #33-Ubuntu SMP Tue Nov 4 12:06:54 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.10
DISTRIB_CODENAME=utopic
DISTRIB_DESCRIPTION="Ubuntu 14.10"
$ 
```

**Comment by lramage94** [comment]
I am having a similar issue but with my machine, there is only the php-cli binary.

I intend to submit a patch for it but basically I just need to add something like,

elif which php-cli >/dev/null 2>&1 ; then export PHP_BIN="php-cli"

**Comment by michaellarabel** [comment]
@lramage94 does this patch take care of it for you? https://github.com/phoronix-test-suite/phoronix-test-suite/commit/253fc167af29339794e360453b22e44ce46ddcdc
