### ISSUE TITLE
Unable to run 'install-sh' (Windows 10)

### ISSUE THREAD

**Issue by pooky2483** [phoronix-test-suite/phoronix-test-suite#389]
I went throught the process of installing bash for windows (Ubuntu in the Windows Store).
I then completed installation of Ubuntu by entering user info & password.
I then went to CMD in Windows and changed to the directory where I downloaded the file.
'C:\Users\pete\Downloads\phoronix-test-suite-9.0.1', then in CMD I typed 'bash install-sh'
And I got the error;
'ERROR: /usr is not writable. Run this installer as root or specify a different directory prefix as the first argument sent to this script.'

I even tried 'root bash install-sh' & 'sudo bash install-sh' and all I for was errors.

How do I run the 'sh' file?

**Comment by michaellarabel** [comment]
That install file is only intended for Linux systems. With Windows you can simply drop the phoronix-test-suite folder wherever is desired.

**Comment by pooky2483** [comment]
Can you explain this then...
a Google search provided this site http://bit.ly/2Y38c69 
scroll down to 'Running The Phoronix Test Suite On Windows' and in that paragraph is 'http://bit.ly/34Dd0lh'

If what you're saying is true, what exactly do I click onto run the test suite?

**Comment by michaellarabel** [comment]
All you need to do is open PowerShell (Or Command Prompt even)

cd phoronix-test-suite
.\phoronix-test-suite <commands>

You are not required to run any 'install' script but can run fine from local directory.
