### ISSUE TITLE
Result viewer default message is not helpful

### ISSUE THREAD

**Issue by Michaelangel007** [phoronix-test-suite/phoronix-test-suite#390]
Running version v9.2.0m2 (from git) and trying to view one of the results in a browser. (`phoronix-test-suite show-result smalltestresults`)

The default message in `/pts-core/static/dynamic-result-viewer/index.php` [Line #65](https://github.com/phoronix-test-suite/phoronix-test-suite/blob/d7a61f371a91c219474e55edb7831319eee4a4e5/pts-core/static/dynamic-result-viewer/index.php#L65) isn't all that helpful.

```
echo '<p>You must configure result_viewer_config.php!</p>';
```

It should contain information on HOW to fix this issue (or at the very least some basic information / pointer for the next step on how to proceed.)

```
		echo '<p>You must configure result_viewer_config.php!</p>';
		echo '<p>Is "sqlite3" installed?</p>';
		echo '<p>You can view the PHP configuration via:</p><pre style="background-color:#F0F0F0">    phoronix-test-suite php-conf</pre>';
		echo '<p>You will probably want to configure files:</p>';
		echo '<pre style="background-color:#F0F0F0">    ~/.phoronix-test-suite/user-config.xml</pre>';
		echo '<p>and:</p>';
		echo '<pre style="background-color:#F0F0F0">    ~/.phoronix-test-suite/graph-config.json</pre>';
		echo '<p><b>NOTE:</b> You can <span style="background-color:#FFC0C0"><b>NOT</b></span> simply copy <span style="background-color:#FFC0C0">result_viewer_config.php.configure</span> to <span style="background-color:#C0FFC0">result_viewer_config.php</span> via:</p>';
		echo '<pre style="background-color:#F8F8F8">    cd /usr/share/phoronix-test-suite/pts-core/static/dynamic-result-viewer/;';
		echo ' sudo cp result_viewer_config.php.configure result_viewer_config.php</pre>';
```

Even with the above I'm _still_ not sure on what _exactly_ needs to be done to configure this?  (Searching the [HTML manual](https://www.phoronix-test-suite.com/documentation/phoronix-test-suite.html) and [PDF manual](http://www.phoronix-test-suite.com/documentation/phoronix-test-suite.pdf) for `result_viewer_config` shows no results.)

**Note.1:** I don't see an option to restart, or stop, the result-viewer?

e.g.

```
$ phoronix-test-suite start-result-viewer

    [PROBLEM] The result viewer is already running. 
```
**Note.2:** As a temporary work-around using `result-file-to-pdf` option instead.

**Comment by michaellarabel** [comment]
Hi @Michaelangel007 actually when using show-result or other built-in commands for launching the result viewer, it should be automatically configured. You shouldn't have to do any manual configuration in those scenarios (only when launching a result file on a standalone server outside of PTS, etc, should you have to configure paths manually).

Can you enlighten me on what Linux distribution you are using or other system details? I haven't seen this issue come up before when using PTS built-in commands. Thanks.

**Comment by Michaelangel007** [comment]
Fresh install of Ubuntu 18.04 LTS.  From `system-info`:

```
  OPERATING SYSTEM:   Ubuntu 18.04
    Kernel:           5.0.0-36-generic (x86_64)                                                                    
    Desktop:          GNOME Shell 3.28.4                                                                           
    Display Server:   X Server 1.20.4                                                                              
    Compiler:         GCC 7.4.0       
```

**Comment by michaellarabel** [comment]
Hmmm any extra security settings? I have used the new result viewer just fine on 18.04 LTS clean install without any issues. By chance could you try rebooting the system to see if it then works fine with `show-result` ?

**Comment by Michaelangel007** [comment]
Sadly, same result. :-/

Originally I installed PTS from `apt-get` before realizing it was the (ancient) 5.x.  I came across one of your posts to install the latest version from git which I did.  I don't believe I have any of the old 5.x cruft laying around as I also ran the `install-sh` script from the local git directory.

# Background

How this all came about is that I'm trying to benchmark blender via `phoronix-test-suite benchmark pts/blender`.  Unfortunately, I'm getting dependency errors:

```
The following dependencies are needed and will be installed: 

- freeglut3-dev
- xorg-dev

:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 freeglut3-dev : Depends: libgl1-mesa-dev but it is not going to be installed or
                          libgl-dev
                 Depends: libglu1-mesa-dev but it is not going to be installed or
                          libglu-dev
                 Depends: libxext-dev but it is not going to be installed
                 Depends: libxt-dev but it is not going to be installed
 xorg-dev : Depends: libdmx-dev but it is not going to be installed
```

Note: I've installed the latest nVidia 440 drivers.

Also, I know you have nothing to do with linuxconfig but you might see if you can shoot them an email to help get to update their installation instructions?
* https://linuxconfig.org/how-to-install-the-latest-phoronix-test-suite-on-ubuntu-18-04-bionic-beaver

The reason I mention it is that I did run `sudo apt install gdebi-core` before coming across the git repo -- but not sure if that is relevant
.

**Comment by Michaelangel007** [comment]
Do you need a copy of the `diagnostics` output?

**Comment by michaellarabel** [comment]
What if you do:

git clone https://github.com/phoronix-test-suite/phoronix-test-suite
cd phoronix-test-suite
./phoronix-test-suite show-result smalltestresults

Does it work? (a.k.a. without running the install script or anything, but just running it from the local directory, that would rule out any interference from the installation, etc.)

**Comment by Michaelangel007** [comment]
Making progress!

I blew away the old git directory, and ran the steps above.  I see the results now!

Chosing option3 for blender `3: Re-attempt to install the missing dependencies.` now properly completes -- however I don't see the results.

```
You must configure result_viewer_config.php!

Current debug values: PTS_VIEWER_RESULT_PATH = /home/michaelangel007/.phoronix-test-suite/test-results/ PTS_VIEWER_PTS_PATH = 
```

**Comment by michaellarabel** [comment]
Can you try with latest Git, I am quite sure the commit just made should now have everything squared away.

**Comment by Michaelangel007** [comment]
Awesome!  Seeing the results now for the blender test!

`git pull ; sudo ./install-sh; phoronix-test-suite show-result blenderbmw`

:+1: 

(I'm still getting the warnings for freeglut3 and xorg-dev but I'll open a new issue for that since this issues is working now.)

**Comment by michaellarabel** [comment]
Thanks, glad to hear to hear it worked out. The packaging issue seems like a weird packaging artifact of how your packaging configuration is setup. I think the Blender test in this instance actually no longer has the freeglut dependency but in any case will take a look here.

**Comment by michaellarabel** [comment]
Another commit has been made to PTS Git for improving the fallback handling that would have allowed the earlier state in your case to at least fall-back to the old PTS result viewer rather than showing the old error message, so should be more robust should any other issues come up.
