### ISSUE TITLE
Cachebench test not coming up on version 9.2.0

### ISSUE THREAD

**Issue by Bryno1234** [phoronix-test-suite/phoronix-test-suite#394]
Hello,

I have an earlier version of Phoronix on another pc (v8.8.1) and when I search for available tests cachebench comes up in the list.  However, I just installed v9.2.0 on a different pc and when I view all tests, cachebench is not available to download.  

Does anyone know what happened to this test?  Is there a way to install v8.8.1 instead of the latest that is on the phoronix test suite website?

Regards,

Bryon

**Comment by michaellarabel** [comment]
If you run `phoronix-test-suite openbenchmarking-refresh` and then `phoronix-test-suite benchmark cachebench` does it work as desired? Just uncovered an OpenBenchmarking.org-side bug/oversight that should now be corrected for that test and other older tests when running on 9.2.0+.

**Comment by Bryno1234** [comment]
Hello,

Thank you for the suggestion.

There were no issues with the refresh command.  It appeared to work.
List-all-tests command still does not have pts/cachebench listed as a test.

When entering the command benchmark cachebench, it returns an invalid argument.
$phoronix-test-suite benchmark cachebench
[PROBLEM] Invalid argument: cachebench.

I closed and restarted a shell and that did not help either.

Bryon

**Comment by michaellarabel** [comment]
Can you try `phoronix-test-suite benchmark cachebench` again in case the time you ran it after the OB refresh it happened to still be cached on the old version? On all my systems tried, the latest OpenBenchmarking.org metadata corrects the issue.

**Comment by Bryno1234** [comment]
Hello.

I tried it again and it works.  It dumped a lot of "new" tests available and I see the cachebench test present.  I installed and it is running.

Thank you for your help.

Bryon

**Comment by michaellarabel** [comment]
Cheers, great. The issue should then be resolved for all PTS users either after running that command or organically running after 48 hours when those caches otherwise automatically refresh themselves.
