### ISSUE TITLE
y-cruncher checksum failed

### ISSUE THREAD

**Issue by Bryno1234** [phoronix-test-suite/phoronix-test-suite#395]
Hello,

When I try to install y-cruncher to the windows version of phoronix-test-suite the following is displayed and sais the checksum failed.

  pts/y-cruncher-1.0.2:
        Test Installation 1 of 1
        1 File Needed [41.72 MB / 1 Minute]
        Downloading: y-cruncher-windows.zip                                                                [41.72MB]
        Estimated Download Time: 1m ................................................................................
            Checksum Failed: http://phoronix-test-suite.com/benchmark-files/y-cruncher%20v0.7.7.9501-static.tar.xz
            Attempting to download from alternate mirror.
        Downloading: y-cruncher-windows.zip                                                                [41.72MB]
            Download Failed: http://www.numberworld.org/y-cruncher/y-cruncher%20v0.7.7.9501.zip
            Downloading of needed test files failed.

Does anyone know why this would be happening?

Regards,

Bryon

**Comment by Bryno1234** [comment]
I am seeing that the installer is bringing up the incorrect version of y-cruncher.
When I try to install, the installer says that it is attempting to download from phoronix-test-suite.  When this fails it tries from a mirror site.  The mirror site is looking for the same version of y-cruncher which is 0.7.7.9501.zip.  When I navigate to the actual site, using the same path as the installer, the version on the site is 7.8.9503.zip.  Is there a way to force phoronix-test-suite to over-ride looking for the 0.7.7.9501 version and have it look for the 7.8.9503 version?

Regards,

Bryon

**Comment by michaellarabel** [comment]
The y-cruncher test profile has now been updated (pts/y-cruncher-1.1.0) that uses the latest upstream version -f Y-Cruncher. After running `phoronix-test-suite openbenchmarking-refresh` the new version should be used.
