### ISSUE TITLE
pts/luxmark-1.2.0 download failure

### ISSUE THREAD

**Issue by kingbeowulf** [phoronix-test-suite/phoronix-test-suite#398]
PTS-9.2.1 fails to download luxmark.
Slackware64-current (15.0) multlib
The message is:
`pts/luxmark-1.2.0:
        Test Installation 5 of 11
        1 File Needed [124 MB / 1 Minute]
        Downloading: luxmark-linux64-v3.1.tar.bz2                                                                                                                        [124MB]
        Estimated Download Time: 1m ............................................................................................................................................

    [8192] strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in pts_test_installer:435
            Checksum Failed: http://www.luxrender.net/release/luxmark/v3.1/luxmark-linux64-v3.1.tar.bz2
    Try downloading the file again (Y/n): y
 `

**Comment by michaellarabel** [comment]
Should be fixed now if running `phoronix-test-suite openbenchmarking-refresh` and then at next run pts/luxmark-1.2.1 should be pulled in that has updated download URLs.
