### ISSUE TITLE
pts/caffe-1.4.0 install.sh script fails to find opencv in Ubuntu 18.04

### ISSUE THREAD

**Issue by pawel-lmcb** [phoronix-test-suite/phoronix-test-suite#402]
when installing libopencv-dev on Ubuntu 18.04 it is installed in /usr/lib/x86_64-linux-gnu/ while the install.sh script looks in /usr/lib64/

https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/ob-cache/test-profiles/pts/caffe-1.4.0/install.sh#L30

Changing this worked fine.

**Comment by jaders-br** [comment]
Can you share more details? I tried your solution without success

**Comment by michaellarabel** [comment]
The Caffe test profile was recently overhauled and should now be in good shape on recent Linux distros.
