### ISSUE TITLE
Error downloading https://github.com/facebook/rocksdb/archive/v6.3.6.tar.gz

### ISSUE THREAD

**Issue by mulugetam** [phoronix-test-suite/phoronix-test-suite#403]
$ ./phoronix-test-suite install pts/rocksdb
Phoronix Test Suite v9.2.1

    To Install:    pts/rocksdb-1.0.2

    Determining File Requirements ...................................................................................................................................................................
    Searching Download Caches .......................................................................................................................................................................

    1 Test To Install
        1 File To Download [5.32MB]
        740MB Of Disk Space Is Needed

    pts/rocksdb-1.0.2:
        Test Installation 1 of 1
        1 File Needed [5.32 MB]
        Downloading: rocksdb-6.3.6.tar.gz                                                                                                                                                    [5.32MB]
            Download Failed: https://github.com/facebook/rocksdb/archive/v6.3.6.tar.gz
            Downloading of needed test files failed.

My proxy settings are just fine (I can download the file using wget).

**Comment by michaellarabel** [comment]
This file still appears to exist fine. Check that you have PHP OpenSSL support installed for downloading over HTTPS, as required by Github.com.

**Comment by mulugetam** [comment]
$ php -i | grep -i openssl
PHP Warning:  Unknown: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in Unknown on line 0
openssl
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL Header Version => OpenSSL 1.0.2k-fips  26 Jan 2017
Native OpenSSL support => enabled

Also,
Package php-common-5.4.16-46.1.el7_7.x86_64 already installed and latest version

**Comment by michaellarabel** [comment]
Is https://github.com/facebook/rocksdb/archive/v6.3.6.tar.gz accessible for you from a web browser? Otherwise it may be some IP/firewall issue or the like.

If it is accessible, you can always download https://github.com/facebook/rocksdb/archive/v6.3.6.tar.gz to ~/.phoronix-test-suite/download-cache/ as a workaround.

**Comment by mulugetam** [comment]
The workaround works.
