### ISSUE TITLE
Review test results returns blank page

### ISSUE THREAD

**Issue by mihainicu** [phoronix-test-suite/phoronix-test-suite#408]
Hi, 

I am using Phoronix Test Suite v9.2.1 (Hurdal) on CentOS Linux release 7.7.1908 (Core) with 

PHP 5.4.16 (cli) (built: Nov  1 2019 16:04:20)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
and PHP modules:
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
libxml
mhash
openssl
pcntl
pcre
PDO
pdo_sqlite
Phar
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]

In the log the following error is recorded while trying to review a test result:
[Wed Jan 22 12:44:10 2020] PHP Fatal error:  Cannot create references to elements of a temporary array expression in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_settings.php on line 89
[Wed Jan 22 12:44:10 2020] :56873 [500]: /?result/1yv422hotwu88wwgk8 - Cannot create references to elements of a temporary array expression in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_settings.php on line 89

Are you aware of this issue? Have I missed a certain dependency? 

Regards,

Mihai

**Comment by michaellarabel** [comment]
This is an issue due to the old version of PHP shipped by CentOS 7. 

In any case, the latest Git or this patch (https://github.com/phoronix-test-suite/phoronix-test-suite/commit/6c807367aa2a0a750db60f0347d0422fa75a8832) should satisfy the old PHP versions.
