### ISSUE TITLE
Windows: no output/error when comparing against an existing benchmark

### ISSUE THREAD

**Issue by aaronjwood** [phoronix-test-suite/phoronix-test-suite#416]
I'm using this as a comparison https://openbenchmarking.org/result/1306099-UT-INTELX26477 but when running `.\phoronix-test-suite benchmark 1306099-UT-INTELX26477` I just get an empty line printed out.

**Comment by aaronjwood** [comment]
I'm not sure if the benchmark is incompatible with Windows or if the entry is just too old/incompatible because `.\phoronix-test-suite benchmark 1911251-AS-R536001US09` works fine.

**Comment by michaellarabel** [comment]
Yes that version is too old. That result file is using pts/x264-1.5.0 but the Windows support was only added later on - https://openbenchmarking.org/test/pts/x264-1.5.0 Though will work on improving the verbage PTS reports in such scenarios.

**Comment by michaellarabel** [comment]
PTS Git / PTS 9.4.0 will now report unsupported test errors to avoid this issue. Thanks.
