### ISSUE TITLE
Benchmark gives orders of magnitudes larger speed on Ubuntu 18.04 Virtual Machine 

### ISSUE THREAD

**Issue by gitjuzer** [phoronix-test-suite/phoronix-test-suite#420]
Unfortunately I don't know the host OS and virtualization server, I only know the CPU is Intel Xeon Silver 4116. As far as I know the 2 physical cores of the host support 4 "physical" / 8 logical cores for the guest.

The result:
$ phoronix-test-suite benchmark 1805250-KH-TESTCPUTX12
...
	Processor: 4 x Intel Xeon (Skylake IBRS) (4 Cores / 8 Threads), Motherboard: OpenStack Foundation Nova v19.0.2 (1.11.0-2.el7 BIOS), Chipset: Intel 440FX 82441FX PMC, Memory: 16384 MB + 8192 MB RAM, Disk: 157GB, Graphics: Cirrus Logic GD 5446 11GB, Audio: NVIDIA GP102 HDMI Audio, Network: Red Hat Virtio device

	OS: Ubuntu 18.04, Kernel: 5.0.0-37-generic (x86_64), Display Server: X Server, Compiler: GCC 7.4.0 + CUDA 10.2, File-System: ext4, Screen Resolution: 1024x768, System Layer: vm-other

    Cpuminer-Opt 3.8.3.3
    Algorithm: sha256t
    Hash Speed > Higher Is Better
    sha256t .......... 15.88   |
    Xeon Silver 4116 . 5719.23

**Comment by michaellarabel** [comment]
This would be some bug with the cpuminer-opt program itself, but unfortunately due to the lack of information hard to decipher what could be going on.

Also note that it looks like you are still on a very outdated version of PTS, the latest version is the 9.2 series.
