### ISSUE TITLE
install faild in aarch64 Ubuntu16.04

### ISSUE THREAD

**Issue by TUT-jiayou** [phoronix-test-suite/phoronix-test-suite#421]
Hi，all
* install php and other php modules.
*  git clone the repository. execute 
```sudo ./install-sh```
* when i want to check out if  the success  of  installiation , I enter ```phoronix-test-suite system-info```, but i can't get any messages
![image](https://user-images.githubusercontent.com/21277368/74914177-ecec6200-53fc-11ea-832e-112948df6e02.png)

thanks for your help.

**Comment by michaellarabel** [comment]
What version of PHP are you installing? What version of the Phoronix Test Suite?

**Comment by TUT-jiayou** [comment]
The version of PHP is 7.2
![image](https://user-images.githubusercontent.com/21277368/75124080-d3dafe00-56e7-11ea-8abe-e008ae5289ad.png)

The version of Phoronix Test Suite is 9.4.0

thanks for your time.
