### ISSUE TITLE
Temperature/CPU Usage Statistic Populate in Phoromatic

### ISSUE THREAD

**Issue by ColbySawyer7** [phoronix-test-suite/phoronix-test-suite#423]
There is no easy way to get Temperature/CPU Usage/ etc. statistics included in phoromatic reporting. A simple setting to include those readings for client devices would be awesome

**Comment by michaellarabel** [comment]
I'll leave this open as a feature request, I might be able to get it for the next release.

(I'm sure you know outside of Phoromatic that such statistic reporting is easily obtainable from the MONITOR= environment variable setup, if not, check out the documentation.)

**Comment by ColbySawyer7** [comment]
Thank you!

**Comment by michaellarabel** [comment]
With PTS 10.8/Git is the ability to enable the sensor monitoring via the "Advanced Options" area, similar to MONITOR= environment variable on client.
