### ISSUE TITLE
Can't seem to install it on Windows 7

### ISSUE THREAD

**Issue by Joe23232** [phoronix-test-suite/phoronix-test-suite#424]
I can't get `phoronix-test-suite` to install properly on Windows 7. I downloaded the software package, unzipped it and I `cd` into the directory containing the package, and then I ran `phoronix-test-suite` which is supposed to initialise it or something and I get this error.

![image](https://user-images.githubusercontent.com/34926497/77387576-ebd69800-6de1-11ea-81f8-4455acbbb451.png)

**Comment by michaellarabel** [comment]
If running on Windows 7, first you need to update PowerShell and ensure other updates are in place.

**Comment by Joe23232** [comment]
Is powershell different to cmd? Because I am using cmd. So does Microsoft push updates to powershell on their website?

**Comment by michaellarabel** [comment]
I don't have a link handy as Windows 7 (and 8) are only loosely supported, but if you download the latest PowerShell (it's not via a Windows update mechanism), PTS should work fine on Windows 7 but otherwise recommend Windows Server / Windows 10.

**Comment by Joe23232** [comment]
Ok thanks man, but what is PTS and like if I update the powershell, can I still use cmd or do I specifically have to start powershell?

**Comment by michaellarabel** [comment]
You can still run from Cmd (though PowerShell will give you more options), PTS will simply invoke PowerShell from CMD.

**Comment by Joe23232** [comment]
@michaellarabel Hi man, so I managed to update powershell and it is executing without those issues.

But during the installation. phoronix wants to install cigwin.

![image](https://user-images.githubusercontent.com/34926497/77429750-341ba780-6e2e-11ea-9b75-97e61b099924.png)

It is prompting me to chose what to download but as you can see it is empty. I believe I can manually add a _User URL_ but like which url should I add?

**Comment by Joe23232** [comment]
@michaellarabel Hey man sorry to disturb you again.

![image](https://user-images.githubusercontent.com/34926497/77431557-f8361180-6e30-11ea-8995-c20bb1cb519e.png)

Over here, it seems to install the test but why does it keep showing this error, do you know how to solve this? I am running powershell.
