### ISSUE TITLE
pts/pmbench test missing RPM dependancy - libuuid-devel 

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [phoronix-test-suite/phoronix-test-suite#428]
Quite a simple issue with pts/pmbench

@chuwi ~]$ phoronix-test-suite run pts/pmbench

    [PROBLEM] pts/pmbench-1.0.2 is not installed. 
    Would you like to stop and install these tests now (Y/n): y
    Evaluating External Test Dependencies ................................................................................................................................................................................................

The following dependencies are needed and will be installed: 

- uuid-devel

This process may take several minutes.

Package uuid-devel-1.6.2-47.fc33.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

There are dependencies still missing from the system:
- UUID

1: Ignore missing dependencies and proceed with installation.
2: Skip installing the tests with missing dependencies.
3: Re-attempt to install the missing dependencies.
4: Quit the current Phoronix Test Suite process.
Missing dependencies action: 4

chuwi ~]$ sudo dnf install libuuid-devel 

then after runs fine. Using Fedora.

**Comment by michaellarabel** [comment]
libuuid-devel is added in latest Git. Thanks.
