### ISSUE TITLE
chmod of pts-core script files needed, permissions

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [phoronix-test-suite/phoronix-test-suite#429]
Hi,
I notice that some scripts and a php file need perms changing after installation of PTS. Can these files be set as follows like the rest then updated to the tarball ? Only these 3 files. Same in both latest milestone and the stable release. 

chmod +x pts-core/external-test-dependencies/scripts/install-macports-packages.sh
chmod +x pts-core/static/sample-pts-client-update-script.sh
chmod -x pts-core/objects/phodevi/sensors/network_usage.php

**Comment by michaellarabel** [comment]
The permissions should be fixed in PTS Git now and thus for the next round of releases. Thanks.
