### ISSUE TITLE
Call to undefined method pts_openbenchmarking_client::get_openbenchmarking_account()

### ISSUE THREAD

**Issue by karolherbst** [phoronix-test-suite/phoronix-test-suite#43]
After installing I get this error
```
PHP Fatal error:  Call to undefined method pts_openbenchmarking_client::get_openbenchmarking_account() in /usr/share/phoronix-test-suite/pts-core/objects/pts_openbenchmarking.php on line 349

Fatal error: Call to undefined method pts_openbenchmarking_client::get_openbenchmarking_account() in /usr/share/phoronix-test-suite/pts-core/objects/pts_openbenchmarking.php on line 349
```

Maybe I forget to do something or I have to configure it before, but such an error shouldn't happen nevertheless and a more meaningfull message shall appear.

**Comment by karolherbst** [comment]
I think this might be an packaging issue. I will close the issue for now

**Comment by michaellarabel** [comment]
What PTS version are you on? pts_openbenchmarking_client::get_openbenchmarking_account() has been around for a while.

**Comment by karolherbst** [comment]
yeah, I noticed that I used a very old version from gentoo-upstream. I am now on 5.4.1 and get this instead:

```
PHP Fatal error:  Call to undefined method pts_config::get_config_file_location() in /usr/share/phoronix-test-suite/pts-core/objects/nye_Xml/pts_config_nye_XmlReader.php on line 29

Fatal error: Call to undefined method pts_config::get_config_file_location() in /usr/share/phoronix-test-suite/pts-core/objects/nye_Xml/pts_config_nye_XmlReader.php on line 29
```

**Comment by michaellarabel** [comment]
What are you running when this issue occurs?

**Comment by karolherbst** [comment]
the function is also there for me. I guess there is some issue with the include paths or something. Actually the error happens everytime I invoke the phoronix-test-suite script.

**Comment by karolherbst** [comment]
seems it was caused by old files still there.
