### ISSUE TITLE
I can't run phoronix-test-suite in my arm64 device.

### ISSUE THREAD

**Issue by TUT-jiayou** [phoronix-test-suite/phoronix-test-suite#431]
Hi,all 
* my device info
```
os: ubuntu16.04
php: PHP 7.4.4 (cli)
phoronix-test-suite :  form the github download.
```
when I run the command``` phoronix-test-suite ``` , I can get any message.
when I try to debug, it can't run in the file``` phoronix-test-suite/pts-core/phoronix-test-suite.php ```
the code is 
```
        if(pts_client::read_env('PTS_IGNORE_MODULES') == false)
        {
    
                pts_client::module_framework_init(); // Initialize the PTS module system
                
        }

```
Thanks for your time.

**Comment by TUT-jiayou** [comment]
I also try the *.deb to install the software. But I can't  run and can't get any message.

**Comment by michaellarabel** [comment]
I would suggest try rebuilding your PHP or so as something is likely messed up there, PTS should be running fine on ARM64.

**Comment by TUT-jiayou** [comment]
But when I run ``` php 1.php``` , it can work. The 1.php is a so easy text file, just includes some characters.

**Comment by TUT-jiayou** [comment]
I can see the docker image about the phoronix-test-suite in the amd64 in docker hub, Is there a plan to release a docker image in the arm64 linux.

**Comment by TUT-jiayou** [comment]
The machine installed by phoronix-test-suite is required with a moniter ? Because I connect with the machine in my PC through ssh. The machine don't have a moniter to display.

**Comment by TUT-jiayou** [comment]
The php module  in my machine
```
[PHP Modules]
calendar
Core
ctype
date
dom
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

```
is there any module I should install ??
Thanks for your time.

**Comment by TUT-jiayou** [comment]
I'm try other version of php 7.0.33 by apt way ,but I also can't run phoronix-test-suite. The only way I can find is just to build php from source code. But,I don't sure that it work. would you give me some guide ?? Thanks for your time.

**Comment by TUT-jiayou** [comment]
I  build the PHP 7.2 and the PHP extensions. But  I also can't run the command in my machine.

**Comment by michaellarabel** [comment]
No monitor is required. It's likely something messed up with your system or PHP. The Phoronix Test Suite should always output something, PHP should always display a warning or error if there is a problem encountered, so if you are seeing nothing output at all is likely a system issue.

**Comment by TUT-jiayou** [comment]
OK，thanks for your time. I will check my machine environment about PHP and other condition. I will close the issue, thanks for your time again. I also hope that I can get the docker image about the aarch 64 platform.

**Comment by TUT-jiayou** [comment]
HI, all 
I'm so confused that what I should  do to check out the reason that PHP can't work in my machine. Could you give me some guide?

Thanks for your time.

**Comment by TUT-jiayou** [comment]
HI,all.
I find the code which make phoronix-test-suite can't run my machine.  When run the command```xscreensaver-command -exit```, I got the warnning, and it waited something. I can't resolve the problem, so, I comment the code in the function ``` pts-core/modules/toggle_screensaver.php 
::class toggle_screensaver::__startup()```
``` 
  if(($xscreensaver = pts_client::executable_in_path('xscreensaver-command')))
                {
                        // modified
                        echo "xscreensaver is $xscreensaver \n";
                        //shell_exec($xscreensaver . ' -exit ');
                        //shell_exec($xscreensaver . ' -exit 2>&1');
                }

```
Also, I command the code 
```
        public static function xdg_screensaver_reset()
        {
                if(!self::$screensaver_halted && self::$xdg_screensaver_available)
                {
                        shell_exec(self::$xdg_screensaver_available . ' reset 2>&1');
                }

                if(($xscreensaver = pts_client::executable_in_path('xscreensaver-command')))
                {
                        //modified
                        echo "exec the same command. \n";
                        //echo $xscreensaver . ' -deactivate 2>&1';
                        //shell_exec($xscreensaver . ' -deactivate 2>&1');
                        //shell_exec($xscreensaver . ' -deactivate ');
                }
        }

```
?? Is there a influence about the software phoronix-test-suite??
!! Anyone could give me some guide. Thanks for your time.

**Comment by TUT-jiayou** [comment]
HI,all.
I find the code which make phoronix-test-suite can't run my machine. When run the command```xscreensaver-command -exit```, I got the warnning, and it waited something. I can't resolve the problem, so, I comment the code in the function ```pts-core/modules/toggle_screensaver.php ::class toggle_screensaver::__startup()```
```
  if(($xscreensaver = pts_client::executable_in_path('xscreensaver-command')))
                {
                        // modified
                        echo "xscreensaver is $xscreensaver \n";
                        //shell_exec($xscreensaver . ' -exit ');
                        //shell_exec($xscreensaver . ' -exit 2>&1');
                }
```
Also, I command the code
```
        public static function xdg_screensaver_reset()
        {
                if(!self::$screensaver_halted && self::$xdg_screensaver_available)
                {
                        shell_exec(self::$xdg_screensaver_available . ' reset 2>&1');
                }

                if(($xscreensaver = pts_client::executable_in_path('xscreensaver-command')))
                {
                        //modified
                        echo "exec the same command. \n";
                        //echo $xscreensaver . ' -deactivate 2>&1';
                        //shell_exec($xscreensaver . ' -deactivate 2>&1');
                        //shell_exec($xscreensaver . ' -deactivate ');
                }
        }
```
?? Is there a influence about the software phoronix-test-suite??
!! Anyone could give me some guide. Thanks for your time.
