### ISSUE TITLE
I can't install any test-suite in aarch64 linux.

### ISSUE THREAD

**Issue by TUT-jiayou** [phoronix-test-suite/phoronix-test-suite#432]
Hi,all 
when I installed the phoronix-test-suite , I try some  test suites, but I can't install test suites.
* install system/blogbench-1.0.3
![Selection_024](https://user-images.githubusercontent.com/21277368/78757325-e9159e80-79ae-11ea-855c-0b04fe05f2f8.png)
* install pts/smallpt-1.2.1
![Selection_025](https://user-images.githubusercontent.com/21277368/78757394-00ed2280-79af-11ea-98aa-58fb0a89e0d9.png)
* install pts/c-ray-1.2.0
![Selection_026](https://user-images.githubusercontent.com/21277368/78757400-034f7c80-79af-11ea-9b4c-71f322bdfaf0.png)
* install pts/xsbench-1.0.0
![image](https://user-images.githubusercontent.com/21277368/78757655-6e00b800-79af-11ea-9687-702d36109b0c.png)

There is maybe a problem about my machine and my php environment, someone could give  some guide. 
Thanks for your time.

**Comment by TUT-jiayou** [comment]
About my PHP  Extension modules. There is some modules I should install. 
```php -m```
```
[PHP Modules]
Core
ctype
date
dom
fileinfo
filter
gd
hash
iconv
json
libxml
mysqlnd
openssl
pcntl
pcre
PDO
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

```

**Comment by darmac** [comment]
Hi, @TUT-jiayou is that issue fixed?
I met the same issue on my aarch64 platform.

**Comment by TUT-jiayou** [comment]
@darmac 
sorry, I also can not install in linux aarch64.
