### ISSUE TITLE
How to update pts/qmcpack?

### ISSUE THREAD

**Issue by ye-luo** [phoronix-test-suite/phoronix-test-suite#437]
Could you guide me to update the test cases?
The current benchmark uses too small problem size and thus spends most of its time not running computational intensive part but mostly overhead (intialization and all kinds of runtime, library overheads).

**Comment by michaellarabel** [comment]
Hi, do you have a new problem size in mind? The test profile itself can be seen in its current version @  https://openbenchmarking.org/innhold/5fb3ff681de6070a33137a232448f37b304f26d8
