### ISSUE TITLE
BRL-CAD test doesn't build with modern CMake

### ISSUE THREAD

**Issue by afzalarsalan** [phoronix-test-suite/phoronix-test-suite#439]
The version of BRL-CAD included with the Phoronix Test Suite doesn't currently build on systems with CMake 3.14+ due to a change in dependencies. The modern version of BRL-CAD 7.30.8 already has this fixed.

Pull Request #438 has the required fix

**Comment by michaellarabel** [comment]
Thanks, updated the test profile via https://github.com/phoronix-test-suite/test-profiles/
