### ISSUE TITLE
[Arch] phoronix-test-suite gui fails

### ISSUE THREAD

**Issue by CommanderAlchemy** [phoronix-test-suite/phoronix-test-suite#44]
I have tried all i can but cannot find out why it does not work. Is my configuration faulty here, Am I doing something wrong? Is this a bug?

When running ```phoronix-test-suite gui``` in terminal the output is:
```text
phoronix-test-suite gui

NOTICE: The php.ini configuration is using the "open_basedir" directive, which may prevent some parts of the Phoronix Test Suite from working. See the Phoronix Test Suite documentation for more details and to disable this setting.
To start server run new script: /tmp/tmp.TohieGxqiv/web-server-launcher

NOTICE: The php.ini configuration is using the "open_basedir" directive, which may prevent some parts of the Phoronix Test Suite from working. See the Phoronix Test Suite documentation for more details and to disable this setting.
PHP 5.6.4 Development Server started at Sat Jan 17 07:26:44 2015
Listening on http://localhost:5391
Document root is /usr/share/phoronix-test-suite/pts-core/web-interface
Press Ctrl-C to quit.
Launching Browser
WebSocket Server Active: localhost:5390
Created new window in existing browser session.
/tmp/tmp.TohieGxqiv/web-server-launcher: line 12: 17541 Terminated              cd /usr/share/phoronix-test-suite && PTS_MODE="CLIENT" php pts-core/phoronix-test-suite.php start-ws-server
/tmp/tmp.TohieGxqiv/web-server-launcher: line 12: 17542 Terminated              php -S localhost:5391 -t /usr/share/phoronix-test-suite/pts-core/web-interface/ 2> /dev/null
```

### Manually
from ```/usr/share/phoronix-test-suite/pts-core```
```PTS_MODE="CLIENT" phoronix-test-suite start-ws-server```
```php -S localhost:8080 -t web-interface```
_above results in no errors_

Then connecting to interface on 8080 using a browser shows the PTS intro and "connecting to websocket in the browser" But nothing happens. 

Opening debug in chrome shows errors spamming: 
```text
WebSocket connection to 'ws://127.0.0.1/start-user-session' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
``` 
and high CPU usage. 
No messages in WebSocket Server

Launching with sudo on:
```sudo PTS_MODE=CLIENT php phoronix-test-suite.php start-ws-server```
after some PHP: Fatal error seems to have loaded but is slow and sometimes unresponsive
```text
PHP Fatal error:  Call to undefined function posix_setsid() in /usr/share/phoronix-test-suite/pts-core/objects/client/pts_client.php on line 1784 
```

**Comment by michaellarabel** [comment]
Make sure you install the POSIX extensions for PHP5.

**Comment by CommanderAlchemy** [comment]
@michaellarabel 
Thanks for helping here, um I removed the commented posix.so in the php.ini file now i got graphs and didn't notice any errors from server. 

Though it still wont launch with the command (phoronix-test-suite gui)

Extensions so far enabled for pts: posix.so, sockets.so sqlite3.so; Anything missing?
