### ISSUE TITLE
Error in PDF Export in 9.6.1

### ISSUE THREAD

**Issue by jaders-br** [phoronix-test-suite/phoronix-test-suite#441]
I tried exporting test results as PDF in Edge, Chrome and Firefox without success. 
The attached diagnostics.txt has my whole system info.

[diagnostics.txt](https://github.com/phoronix-test-suite/phoronix-test-suite/files/4679817/diagnostics.txt)

**Comment by michaellarabel** [comment]
Unfortunately that diagnostics really isn't useful in regards to PDF. What are you seeing / errors when trying to export to PDF?

**Comment by jaders-br** [comment]
Hi Michel,

I go to results, then I click a result of a test. With the result loaded I click on Export Benchmark Data and then in Result File to PDF

It tries to open the following link: http://172.31.56.73:8088/?result/2y10rv66dkyscwk08&export=pdf& and I get error " Failed to load PDF document"  in Chrome (in edge and Firefox it says the PDF is corrupted).

Find screenshots attached.

Thanks in advance.

[cid:image003.png@01D63357.8D7D78B0]

[cid:image004.png@01D63357.8D7D78B0]

**Comment by michaellarabel** [comment]
If you run `phoronix-test-suite result-file-to-pdf <name of result file>` does it work? It should save a PDF into your home directory.

**Comment by jaders-br** [comment]
I have a question

I'm checking /var/lib/phoronix-test-suite/test-results but it is empty.

I found results stored in /var/lib/phoronix-test-suite/phoromatic/accounts/V8Z89J/results/1

If I run #phoronix-test-suite list-results the response is:

Phoronix Test Suite v9.6.1
0 Saved Results

Running phoronix-test-suite result-file-to-pdf system-logs.zip (from /var/lib/phoronix-test-suite/phoromatic/accounts/V8Z89J/results/1) returns:

    [PROBLEM] Invalid Argument: system-logs.zip phoronix-test-suite result-file-to-pdf system-logs.zip

Thanks again

Jader
