### ISSUE TITLE
www.cs.virginia.edu/~kw5na/lava/Rodinia/Packages/Current/rodinia_3.1.tar.bz2 403 (Forbidden) 

### ISSUE THREAD

**Issue by buckybits** [phoronix-test-suite/phoronix-test-suite#446]
The test suite tries to download, but fails:

pts/rodinia-1.3.0:
        Test Installation 1 of 1
        1 File Needed [344 MB]
        Downloading: rodinia_3.1.tar.bz2                                                                                                                                           [344MB]
            Download Failed: http://www.cs.virginia.edu/~kw5na/lava/Rodinia/Packages/Current/rodinia_3.1.tar.bz2
            Downloading of needed test files failed.

    [PROBLEM] pts/rodinia-1.3.0 is not installed. 

... a quick check on the website also does not allow access via HTML to ~kw5na's public(?) file, folder directory.

1. Are there any other repos or servers hosting this file? Or is this a one-man (prorietary) project, only?
2. A single user's university server user_dir ... is that not the definition of "Single-Point-of-failure"?

**Comment by michaellarabel** [comment]
Presumably it's just the host having a temporary issue. http://lava.cs.virginia.edu/Rodinia/download.htm still points to that location as the place for downloading Rodinia.

Unfortunately I don't have the resources (bandwidth) for mirroring every possible file used by PTS benchmarks (thousands of files) but encourage PTS users to run their own Phoromatic servers on their LANs to allow caching of these files on their intranet if frequently using PTS especially on multiple machines.

I am not aware of any other public Rodinia mirrors so perhaps just check in a day or two and hopefully their host is restored.

**Comment by buckybits** [comment]
Yep.

Btw, same just happend with an Unreal4 Engine "Elemental" Demo link, too (timed out). But that's easier to find & download.

I'll 'close' this, as it is not directly a coding/app issue. 

Cheers :)
