### ISSUE TITLE
Unable to run pts/pgbench on Phoronix docker hub image

### ISSUE THREAD

**Issue by Margretor** [phoronix-test-suite/phoronix-test-suite#450]
Version info:
Docker image from:
`https://hub.docker.com/r/phoronix/pts`

It's running on a Ubuntu VM with:
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```
Docker version:
`Docker version 19.03.11, build dd360c7`

command used from the phoronix shell: run pts/pgbench
```
MariaDB 10.5.2:
    pts/pgbench-1.9.1 [Scaling: Buffer Test - Test: Single Thread - Mode: Read Write]
    Test 1 of 1
    Estimated Trial Run Count:    3
    Estimated Time To Completion: 55 Minutes [16:23 UTC]
        Started Run 1 @ 15:29:02
        The test run did not produce a result.
        Started Run 2 @ 15:29:16
        The test run did not produce a result.
        Started Run 3 @ 15:29:30
        The test run did not produce a result.
        E: ./pgbench: 51: pg_/bin/pgbench: not found
```
further information, the instalation seems to fail:
```
Err:18 http://security.ubuntu.com/ubuntu focal-updates/main amd64 linux-libc-dev amd64 5.4.0-40.44
  404  Not Found [IP: 91.189.88.152 80]
```
As a side note the test was working fine with the same docker image on 17.07.2020. Ubuntu seems to dropped the package and an upgraded one might be available or an update to use the mirrors protocol for apt-get if that package is available on another mirror.
Let me know if any further information is needed.

**Comment by michaellarabel** [comment]
The next Docker image release will run apt update prior to calling for test installation. Thanks.
