### ISSUE TITLE
XDG Base Directory Standard

### ISSUE THREAD

**Issue by reevo1985** [phoronix-test-suite/phoronix-test-suite#453]
Hi it would be nice to move Phoronix out of the home directory and into a standardized location.
Is there a way to achieve this such as listed here?

https://wiki.archlinux.org/index.php/XDG_Base_Directory

**Comment by michaellarabel** [comment]
The Phoronix Test Suite if run as sudo/root will already use the standardized locations outside of the home directory for test files, etc. It's when there is only writable permissions inside the home directory that the home directory location is used.

**Comment by Henry-ZHR** [comment]
> The Phoronix Test Suite if run as sudo/root will already use the standardized locations outside of the home directory for test files, etc. It's when there is only writable permissions inside the home directory that the home directory location is used.

I think he didn't mean exactly "out of the home directory"

When using location in home directory, `$XDG_CONFIG_HOME` (usually `$HOME/.config`) and `$XDG_DATA_HOME` (usually `$HOME/.local/share`) should be used instead of creating a directory directly in `$HOME`

**Comment by 62832** [comment]
@michaellarabel With the clarification of the XDG base dir spec about keeping things within directories like `$XDG_CONFIG_HOME` (`~/.config/phoronix-test-suite`) and `$XDG_DATA_HOME` (`~/.local/share/phoronix-test-suite`), is this issue something you'd like to reconsider?
