### ISSUE TITLE
Phoromatic Comparision UI issue

### ISSUE THREAD

**Issue by miche1** [phoronix-test-suite/phoronix-test-suite#459]
The CSS of the comparison viewer seems to be broken with Phoromatic 9.8.0. We can not reproduce the issue with older versions of Phoromatic. 

I have attached an screenshot to visualize the issue.

![Screenshot_2020-08-11 Phoronix Test Suite 9 8 0 - Phoromatic - Result(1)](https://user-images.githubusercontent.com/25909385/89897804-e4bcf480-dbdf-11ea-8747-de6ab45f906c.png)

**Comment by michaellarabel** [comment]
Hi, are you installing PTS/Phoromatic or running it locally from a directory? Any other changes?  I haven't been able to reproduce this issue. Do you have the problem if trying PTS Git?

**Comment by miche1** [comment]
Hi, PTS is installed via your Debian package and the service is running via a specific Linux user. 

We have tried to reproduce the issue on a clean system again. On the the test system we have installed a clean Ubuntu 20.04.1 and have cloned the current PTS repository from Github. Unfortunately we the issue was occurred again. The issue was independent of the browser(Chrome/Firefox).

The attached screenshot are showing the clean installation (Phoronix Test Suite 10.0.0m1)
![screenshot](https://user-images.githubusercontent.com/25909385/92375822-eeb01580-f101-11ea-936f-a2b8ad408138.png)

**Comment by miche1** [comment]
Hi, the issue is still persist with the current debian package (10.0.1)

**Comment by miche1** [comment]
Hi Michael, 
there is the html code snippet of the "broken" result viewer in Phoromatic v10.0.1 .
![phoromatic_v1001_ISSUE](https://user-images.githubusercontent.com/25909385/100354710-d957d280-2ff0-11eb-9603-8c63a9f8e995.png)

This is a html code snippet of the result viewer in Phoromatic v9.4.1 . In version v9.4.1 we have not detected any issues.
![phoromatic_v941_OK](https://user-images.githubusercontent.com/25909385/100354712-d9f06900-2ff0-11eb-8021-099c4dac3ce8.png)

**Comment by michaellarabel** [comment]
@miche1 I was finally able to reproduce what you were seeing due to a difference from my Phoromatic testing server configuration... If you pull the latest Git (or 10.2.0 coming in the next few weeks), the issue should now be fixed up for that UI issue. Thanks and sorry about the delay.
