### ISSUE TITLE
Dynamic result viewer works only when RANDOM port is defined in configuration

### ISSUE THREAD

**Issue by kohoutovice** [phoronix-test-suite/phoronix-test-suite#460]
Hello,
I've encoutered a problem that when I'm trying to use dynamic result viewer, it is only possible when random port is defined in configuration. When I tried to define specific port on which the server should serve the server doesn't work. I've been trying to debug why it is happening but after many hours I don't know why it is happening. 
I'm trying to run it via systemd and found out that for some reason it loads the result server two times and the (config file specified) modules for three times.

```
Aug 11 17:18:11 localhost phoronix-test-suite[8638]: Port 8507 chosen as random port for this instance. Change the default port via the Phoronix Test Suite user configuration file.
Aug 11 17:18:11 localhost phoronix-test-suite[8638]: Launching with PHP built-in web server.
Aug 11 17:18:11 localhost phoronix-test-suite[8638]: Result Viewer: http://10.37.153.132:8507
Aug 11 17:18:11 localhost phoronix-test-suite[8638]: Phoronix Test Suite v9.8.0 (Nesodden) starting Phoromatic Server
Aug 11 17:18:11 localhost phoronix-test-suite[8638]: Phoronix Test Suite User-Data Directory Path: /var/lib/phoronix-test-suite/
Aug 11 17:18:11 localhost phoronix-test-suite[8638]: Phoronix Test Suite Configuration File: /etc/phoronix-test-suite.xml
Aug 11 17:18:11 localhost phoronix-test-suite[8638]: Phoromatic Server Log File: /var/log/phoromatic.log
Aug 11 17:18:11 localhost phoronix-test-suite[8638]: Launching with PHP built-in web server.
Aug 11 17:18:12 localhost phoronix-test-suite[8638]: Port 8011 chosen as random port for this instance. Change the default port via the Phoronix Test Suite user configuration file.
Aug 11 17:18:12 localhost phoronix-test-suite[8638]: Launching with PHP built-in web server.
Aug 11 17:18:12 localhost phoronix-test-suite[8638]: Result Viewer: http://10.37.153.132:8011
Aug 11 17:18:12 localhost phoronix-test-suite[8638]: WebSocket Server Active: localhost:8679
Aug 11 17:18:12 localhost phoronix-test-suite[8638]: The Phoromatic Web Interface Is Accessible At: http://localhost:8089
```
Actually the situation that can be seen in log produces functional phoromatic server and result viewer on port 8679, but its only for random result viewer port. When I try to set specific port the result viewer won't work.

Thanks for any advice.

**Comment by michaellarabel** [comment]
How are you running the dynamic result viewer via systemd or are you referring to accessing the result viewer while the Phoromatic Server is running? Via systemd would be just running the Phoromatic Server, which isn't the dynamic result viewer.

If you run outside of systemd with a custom port for the dynamic result viewer does it work fine?

**Comment by kohoutovice** [comment]
I am running phoromatic-server from systemd and as far as I know it should start (and its actually starting on random port) result viewer. But when specific port is defined it doesn't work.

If I try to run it outside of systemd, just with this command 
```
phoronix-test-suite start-result-viewer
```
It works fine even on specific port.

**Comment by kohoutovice** [comment]
Actually it seems that it works after pc reboot, but when `systemctl restart phoromatic-server` is run it stops working.
