### ISSUE TITLE
OpenSSL download fails on Windows

### ISSUE THREAD

**Issue by ftrebien** [phoronix-test-suite/phoronix-test-suite#463]
On Windows, PTS 9.8.0 tries to download OpenSSL from https://indy.fulgan.com/SSL/Archive/openssl-1.0.1g-x64_86-win64.zip , which no longer exists. As pointed out [here](https://opendec.wordpress.com/), the source for this component is now [this directory](https://github.com/IndySockets/OpenSSL-Binaries/tree/master/Archive). Please update when possible.

**Comment by michaellarabel** [comment]
windows/openssl-1.9.3 is now available with the updated mirror, thanks.
