### ISSUE TITLE
Installer fails on Windows when user name has spaces

### ISSUE THREAD

**Issue by ftrebien** [phoronix-test-suite/phoronix-test-suite#464]
The `install.bat` script fails when the Windows user name running it has spaces, eg.: "John Smith" instead of "JohnSmith". This can be fixed by editing this line:
``` bat
xcopy %cd% %destination% /E
```
Adding quotes around the current directory, this way:
``` bat
xcopy "%cd%" %destination% /E
```

**Comment by michaellarabel** [comment]
Thanks, fixed in latest Git.
