### ISSUE TITLE
Sites down only for me ;)

### ISSUE THREAD

**Issue by RobertBerger** [phoronix-test-suite/phoronix-test-suite#466]
When I try to access openbenchmarking.org or phoronix-test-suite.com directly (no vpn) they can not be reached.

Through a vpn (another country) everything works fine.

What happened?

Did I get blacklisted somehow?

If so how?

**Comment by RobertBerger** [comment]
BTW from generally speaking it does not seem to be down. I can access it from other countries - no problem.
Also services like downforeveryoneorjustme.com say it's up.

**Comment by michaellarabel** [comment]
Can you either post (or email michael at phoronix.com) your IP address and I can see if it got blocked by the firewall or some other issue.

**Comment by RobertBerger** [comment]
> Can you either post (or email michael at phoronix.com) your IP address and I can see if it got blocked by the firewall or some other issue.

It's dynamic IPs so here they are:

The one which does not work: 
2.86.237.227

The one which works (via vpn):
128.90.148.161

**Comment by michaellarabel** [comment]
Does it work now if you try?

**Comment by RobertBerger** [comment]
> Does it work now if you try?

Yep now it works. What was it?

**Comment by michaellarabel** [comment]
The IP was blocked by the firewall logic but has now been whitelisted. Sometimes depending upon traffic pattern if frequently using PTS to download new tests it will hit a false positive of a legitimate user and block the IP based on whatever peculiar behavior with the excessive traffic behavior,

**Comment by RobertBerger** [comment]
Anyways - Thanks for the quick help! 
BTW I am trying to run some interesting tests on ARM32/ARM64 native and in container. You might be interested once I ran a couple of tests.
