### ISSUE TITLE
pts/mkl-dnn-1.1.1 - checksum failed

### ISSUE THREAD

**Issue by stefanheijnen** [phoronix-test-suite/phoronix-test-suite#470]
pts/mkl-dnn-1.1.1:
        Test Installation 1 of 3
        1 File Needed [4.31 MB / 1 Minute]
        Downloading: mkl-dnn-1.1.tar.gz                                                                                                                                                        [4.31MB]
        Estimated Download Time: 1m ...................................................................................................................................................................
            Checksum Failed: https://github.com/intel/mkl-dnn/archive/v1.1.tar.gz

When manually opening the link it redirects to https://codeload.github.com/oneapi-src/oneDNN/tar.gz/v1.1 and gives me a file named oneDNN-1.1.tar.gz. I tried placing this in the download-cache, but obvious pts doesn't recognize this file. When I rename it, the checksum fails.

**Comment by michaellarabel** [comment]
Looks like Intel dropped the old files. In any case unless there is a reason you specifically want the 1.1 release, it would be recommended to use pts/onednn test profile instead. MKL-DNN was renamed to oneDNN and the onednn test profile contains the newer versions.
