### ISSUE TITLE
glmark2 installation fails with Python 3.7

### ISSUE THREAD

**Issue by paulmenzel** [phoronix-test-suite/phoronix-test-suite#471]
Python 3.7 as default

    $ python --version
    Python 3.7.7

causes the glmark2 installation to fail. That’s a known  [known Waf issue](https://github.com/glmark2/glmark2/issues/82) and [fixed](https://gitlab.com/ita1024/waf/-/commit/facdc0b).

**Comment by paulmenzel** [comment]
For the record, the logs: [`install-failed.log`](https://github.com/phoronix-test-suite/phoronix-test-suite/files/5225064/install-failed.log).

**Comment by michaellarabel** [comment]
pts/glmark2-1.2.0 is now available via PTS that updates against glmark2 Git and in turn fixes this issue. Thanks. Note you may need to run `phoronix-test-suite openbenchmarking-refresh` if last running PTS within 48 hours in order to see the new update.
