### ISSUE TITLE
Windows phoronix-test-suite-10.0.0m1 result_viewer_lock always causes red notice line

### ISSUE THREAD

**Issue by mirror176** [phoronix-test-suite/phoronix-test-suite#472]
"[NOTICE] unlink(C:\Users\user\.phoronix-test-suite\result_viewer_lock): Resource temporarily unavailable in pts_file_io:38" seems to appear at the end of every run in red. System is Windows 10 x64 v2004. Pts launched through powershell (v1.0?)

**Comment by michaellarabel** [comment]
Are you still seeing this error? I haven't been able to reproduce on recent builds with Windows. In any case, the notice/warning is harmless.
