### ISSUE TITLE
problematic versioning

### ISSUE THREAD

**Issue by kloczek** [phoronix-test-suite/phoronix-test-suite#474]
Sequence of released version:
- 9.8.0
- 10.0.0m1
- 10.0.0m2
- 10.0.0m3
- 10.0.0

Issue is that 10.0.0m3 is greater than 10.0.0.

**Comment by michaellarabel** [comment]
With which package management solution or configuration are you running into the issue? For a number of years the development releases have been versioned the same as 'mX' milestone releases.

**Comment by kloczek** [comment]
All known for me .. rpm, dpkg, IPS.
https://en.wikipedia.org/wiki/Software_versioning

**Comment by michaellarabel** [comment]
Ah okay in that regard. If any packager doing that runs into issues, happy to change the Git tag format.

**Comment by kloczek** [comment]
Please :)
It will make few things easier.

Just please keep that sunject in mind :P 

Suggestion: non-prod/pre/milestone release you can for example tag as `milestone/<foo.version>`. Something like that will be clear sign that such version is not for general usage.

Closing.
