### ISSUE TITLE
[Installation] No display server was found

### ISSUE THREAD

**Issue by mareng0** [phoronix-test-suite/phoronix-test-suite#475]
The command `./phoronix-test-suite install octanebench` gives me the error `No display server was found,  skipping pts/octanebench-1.3.0`.

I want to run an Octanebenchmark from CLI on a GPU server that has Ubuntu 20.04 installed.

**Comment by michaellarabel** [comment]
The current octanebench test profile requires a display server for launching the program. You may want to try the v-ray test profile or other similar tests that do not require a window to appear for testing and thus can run headless fine. The OctaneBench test profile was also recently updated if it copes any better with the new OctaneBench for headless environments.
