### ISSUE TITLE
pts/desktop-graphics still uses pts/glmark2 1.1.0 instead of 1.2.0

### ISSUE THREAD

**Issue by paulmenzel** [phoronix-test-suite/phoronix-test-suite#476]
Using PTS from GitHub on a freshly installed Ubuntu 20.04 install, running `./phoronix-test-suite benchmark pts/desktop-graphics` fails to build/install `pts/glmark2-1.1.0`, because `/usr/bin/python` is not found.

Isn’t it supposed to use `pts/glmark2-1.2.0` after issue https://github.com/phoronix-test-suite/phoronix-test-suite/issues/471 was addressed?

**Comment by michaellarabel** [comment]
This is now fixed with the updated desktop-graphics suite, thanks. Sorry for the late response.
