### ISSUE TITLE
FFMPEG package source for Windows no longer exists

### ISSUE THREAD

**Issue by brentil** [phoronix-test-suite/phoronix-test-suite#477]
When running on Windows the system looks for the static builds of FFMPEG for Windows from a domain that no longer exists.

example - https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.0.2-win64-static.zip

**Comment by michaellarabel** [comment]
This will be fixed with the next FFmpeg release when being able to procure new mirrors for their Win64 build, thanks though for reporting.
