### ISSUE TITLE
how can I use the compare_results_two_way command

### ISSUE THREAD

**Issue by xufuhai** [phoronix-test-suite/phoronix-test-suite#479]
I wanna compare two different system iperf results, using pts compare_results_two_way subcommand, but I have not idea about how I can run the command like below images. please give me reply thx~
![image](https://user-images.githubusercontent.com/18589955/99073997-e983b100-25f1-11eb-82d7-109307851046.png)

**Comment by michaellarabel** [comment]
The command you should be using would be e.g. `phoronix-test-suite merge-results ptsfio ptsiperf`
