### ISSUE TITLE
Is it possible to add a "partitioning-scheduling/cores" for each benchmark?

### ISSUE THREAD

**Issue by vulptex** [phoronix-test-suite/phoronix-test-suite#480]
It would be great to see how a test-run was scheduled on multiple cores -> more single-threaded or multi-threaded centric test.
If the software behind is scheduling to only 2 cores 4 ...., would give me a nice insight into each benchmark.

**Comment by michaellarabel** [comment]
At the moment you can set the MONITOR=cpu.usage environment variable to monitor the overall CPU usage on a per-test basis. There isn't per-core tracking, trying to think off hand if any existing trace/perf command would provide the metrics you are after, if so it would be easy to add it to PTS as another module.
