### ISSUE TITLE
Unable to run any graphics test on Windows

### ISSUE THREAD

**Issue by flopun** [phoronix-test-suite/phoronix-test-suite#483]
When I try to run any graphic test (eg. gputest) on Windows 10, I get the following message: The test run did not produce a result.
Output of "debug-benchmark" is:

Test Run Command: cd C:\Users\John\.phoronix-test-suite\installed-tests\\pts/gputest-1.3.2\ && ./gputest /benchmark /no_scorebox /disable_opengl_support_check /test=triangle /width=800 /height=600 2>&1
Making use of PhoroScript code path...
Result Key: #_RESULT_#
No Log File Found To Parse
The test run did not produce a result.

I'm using version 10.0.1

**Comment by mylesnel** [comment]
I am having the same issue. Can you enlighten me on what method you used to resolve this problem?
