### ISSUE TITLE
Xonotic benchmark doesn't run at specified resolution

### ISSUE THREAD

**Issue by damian101** [phoronix-test-suite/phoronix-test-suite#485]
Which results in scores being affected by display resolution instead of the specified benchmark resolution.

**Comment by michaellarabel** [comment]
Xonotic regressed with some X11 update. Kind of been hoping a new Xonotic release would be out soon, but alas no signs of new release on the horizon... So while most normally opt anyhow for using their optimal/default resolution, pts/xonotic-1.5.2 is now pushed out that will just limit it to the current resolution until upstream Xonotic issues a new release that works better. Thanks.
