### ISSUE TITLE
Incorrect system info

### ISSUE THREAD

**Issue by pinkhamr** [phoronix-test-suite/phoronix-test-suite#486]
I'm using PTS to benchmark many systems in our pool. All of our linux machines share a common home path located on a network drive. I've installed the tests locally, and changed the caching directory to be local as well. However, it seems like the sysinfo printed by PTS is incorrect. Because of this, some of the results uploaded to openbenchmarking.org with incorrect system info. Here is the output from /proc/cpuinfo compared to what PTS provides:

![image](https://user-images.githubusercontent.com/7255824/102653781-78c63c00-413d-11eb-92d7-3175845ec969.png)

Edit: Just to note, this info is the info from a different server that I previously benchmarked with PTS

**Comment by michaellarabel** [comment]
Hi, what is the the output of `phoronix-test-suite diagnostics | grep PTS_USER_PATH`? Or rather, is that path on a networked drive?

PTS will cache some system information that normally doesn't chance at least without a reboot (CPU string, motherboard, etc). So as long as no reboot was detected based on uptime relative to last run, the cached information will be used.So I am guessing what is pointing to PTS_USER_PATH is a shared network drive location and therefore end up reusing that cache?

What network file-system is in use? (I could add the support to bust the cache say if a given network file-system is detected for the PTS_USER_PATH location.) In the meantime you can also confirm that by running PTS after setting the 'NO_PHODEVI_CACHE=1' environment variable so the cache doesn't outlive the program.

**Comment by pinkhamr** [comment]
The output is the map to the shared home on the network drive

```
vlsipool-j14 phoronix-test-suite ./phoronix-test-suite diagnostics | grep PTS_USER_PATH
PTS_USER_PATH = /n/<servername>/s/pinkhamr/.phoronix-test-suite/
```

I'm using NFS for the network drives. I'm guessing me running another instance of PTS with the same home location touched the cached info. Is there a system variable I can set (PTS_USER_PATH?) to set it to something local?

**Comment by michaellarabel** [comment]
Since it looks like you are on PTS Git anyways, can you try pulling down the latest Git? Just pushed a change where it won't restore the Phodevi cache if the /etc/machine-id is different from the value cached (thus different system, or looking for changed /etc/hostname if machine-id doesn't exist). So this likely should solve the network drive use-case in the simplest manner.

**Comment by pinkhamr** [comment]
I'll pull the change and give it a shot!

**Comment by pinkhamr** [comment]
Looks like it worked with printing the system-info at least. I'll reopen if I see the issue again.
