### ISSUE TITLE
vkmark Fails to compile with error: ‘VK_FORMAT_BEGIN_RANGE’ was not declared in this scope

### ISSUE THREAD

**Issue by kingbeowulf** [phoronix-test-suite/phoronix-test-suite#487]
Looks like issue with vkmark:  [https://github.com/vkmark/vkmark/issues/25](url)
`Recent vulkan header versions removed the VK_FORMAT_BEGIN_RANGE and
VK_FORMAT_END_RANGE enum values, which we used for iterating through a
subset of the available pixel formats.
`
Slackware64-Current (15.0 dev 20NOV2020) multilib
Phoronix Test Suite v10.0.1 (Finnsnes)
Build log attached.
[install-failed.log](https://github.com/phoronix-test-suite/phoronix-test-suite/files/5722542/install-failed.log)

**Comment by michaellarabel** [comment]
If you run `phoronix-test-suite openbenchmarking-refresh` and then run the benchmark vkmark again, it should pickup now pts/vkmark-1.2.0 that is using the latest VkMark Git state so in turn should address your build problem. Thanks.
