### ISSUE TITLE
pts/lammps-1.3.0: checksum failing

### ISSUE THREAD

**Issue by brauliobo** [phoronix-test-suite/phoronix-test-suite#489]
```
    pts/lammps-1.3.0:
        Test Installation 1 of 24
        2 Files Needed [531 MB]
        File Found: lammps-stable_29Oct2020.tar.gz                                                                                                       [122MB]
        Downloading: lammps-hecbiosim-1.tar.gz                                                                                                           [410MB]
        Downloading ............................................................................................................................................
            Checksum Failed: http://www.hecbiosim.ac.uk/lammps-benchmarks/send/2-software/10-lammps-bench
    Try downloading the file again (Y/n): n
            Downloading of needed test files failed.
```

**Comment by michaellarabel** [comment]
Can you try downloading it again? I just downloaded the file again from that URL and the MD5 and SHA256 hashes match the values set in the test profile, so perhaps there was an Internet issue or so during the donload.

**Comment by brauliobo** [comment]
@michaellarabel I've clicked retry many times with it and others failing and it keeps failing. Maybe the retries isn't fully working?

**Comment by michaellarabel** [comment]
I still have been unable to reproduce this issue nor seen reports of others having issues with this mirror, so it appears to be something isolated to your connection or region. Trying again tonight on my connections is still yielding a working mirror and matching checksums.
