### ISSUE TITLE
io_uring broken in pts/fio-1.14.1

### ISSUE THREAD

**Issue by meaton82** [phoronix-test-suite/phoronix-test-suite#490]
Debug output below. The same test works when selecting linux aio instead of io_uring. OS is Ubuntu 20.04 with 5.4 kernel.

========================================
Flexible IO Tester (Run 1 of 1)
========================================

Test Run Command: cd /var/lib/phoronix-test-suite/installed-tests/pts/fio-1.14.1/ && ./fio-run randread io_uring 0 1 4k /mnt/nvme0n1 2>&1

fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=504672256, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=379588608, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=699166720, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=600182784, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=665198592, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=739086336, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=279457792, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=905744384, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=76623872, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=574529536, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=107171840, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=366309376, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=1066180608, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=800714752, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=718979072, buflen=4096
fio: io_u error on file /mnt/nvme0n1/fiofile: Invalid argument: read offset=424083456, buflen=4096

Result Key: #_RESULT_#

Template Line:    READ: bw=#_RESULT_# (861MB/s), 821MiB/s-821MiB/s (861MB/s-861MB/s), io=16.4GiB (17.3GB), run=20002-20002msec

Result Parsing Search Key: ": bw="

Result Line:    READ: bw=188MiB/s (197MB/s), 188MiB/s-188MiB/s (197MB/s-197MB/s), io=192KiB (197kB), run=1-1msec

No Test Results

Result Key: #_RESULT_#

Template Line:    READ: bw=#_RESULT_# (861MB/s), 821MiB/s-821MiB/s (861MB/s-861MB/s), io=16.4GiB (17.3GB), run=20002-20002msec

Result Parsing Search Key: ": bw="

Result Line:    READ: bw=188MiB/s (197MB/s), 188MiB/s-188MiB/s (197MB/s-197MB/s), io=192KiB (197kB), run=1-1msec

Test Result Parser Returning: 188

Result Key: #_RESULT_#

Template Line:   write: IOPS=#_RESULT_# BW=891MiB/s (934MB/s)(17.5GiB/20006msec)

Result Parsing Search Key: "IOPS="

Result Line:   read: IOPS=64.0k, BW=188MiB/s (197MB/s)(192KiB/1msec)

Test Result Parser Returning: 64000

Result Key: #_RESULT_#

Template Line:   write: IOPS=#_RESULT_# BW=891MiB/s (934MB/s)(17.5GiB/20006msec)

Result Parsing Search Key: "IOPS="

Result Line:   read: IOPS=64.0k, BW=188MiB/s (197MB/s)(192KiB/1msec)

Test Result Parser Returning: 64000

Log File At: /var/lib/phoronix-test-suite/installed-tests/pts/fio-1.14.1/fio-1.14.1-1609268585-1.log

Running Post-Test Script

###############################################################################################################
Flexible IO Tester:
Type: Random Read - Engine: IO_uring - Buffered: No - Direct: Yes - Block Size: 4KB - Disk Target: /mnt/nvme0n1

188 MB/s

Average: 188 MB/s
###############################################################################################################

###############################################################################################################
Flexible IO Tester:
Type: Random Read - Engine: IO_uring - Buffered: No - Direct: Yes - Block Size: 4KB - Disk Target: /mnt/nvme0n1

64000 IOPS

Average: 64000 IOPS
###############################################################################################################

**Comment by michaellarabel** [comment]
It might be iO_uring with FIO having an issue with Ubuntu's Linux 5.4 kernel. The fio test profile with IO_uring is working fine for me on newer versions of the kernel.

**Comment by meaton82** [comment]
Thanks for checking. I figured it might be kernel related. Kernel upgrade is not an option for me at this point so I'll stick to linux aio for now.
