### ISSUE TITLE
libgcrypt dependency of 1.9.0 broken

### ISSUE THREAD

**Issue by antonym** [phoronix-test-suite/phoronix-test-suite#499]
It appears libgcrypt has been marked as do_not_use upstream.  

http://mirrors.dotsrc.org/gcrypt/libgcrypt/libgcrypt-1.9.0_do_not_use.tar.bz2

Changing the downloads.xml and install.sh files to reflect 1.9.1 appears to fix the issue.

**Comment by michaellarabel** [comment]
Thanks yeah been meaning to update it following the recent libgcrypt vulnerabiity. pts/gcrypt-1.1.2 is now uploaded that shifts to using the 1.9.1 point release.
