### ISSUE TITLE
[Ubuntu 14.10 x86] pts/minion fails to compile

### ISSUE THREAD

**Issue by snigel** [phoronix-test-suite/phoronix-test-suite#50]
Using gcc 4.9.1 installed via apt-get.

From the log:
...
minion-0.15/nauty24b7/nautycxx.cpp
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != ((void *)0)' failed!
make: *** No rule to make target 'minion'.  Stop.

I have no idea how to proceed here, but there shouldn't be any magic in this machine.

**Comment by michaellarabel** [comment]
Looks like the test code breaks against the latest GCC. It's really outside the realm of PTS but will see if there's a newer version of Minion available that is hopefully compatible with newer versions of GCC.
