### ISSUE TITLE
"Invalid Argument: ashvi/trial3" with "phoronix-test-suite benchmark ashvi/trial3"

### ISSUE THREAD

**Issue by sniklaus** [phoronix-test-suite/phoronix-test-suite#501]
Thank you for this wonderful tool! On the website at https://openbenchmarking.org/suite/ashvi/trial3 it says the following.

> See how your system performs with this suite using the Phoronix Test Suite. It's as easy as running the `phoronix-test-suite benchmark ashvi/trial3` command.

However, running `phoronix-test-suite benchmark ashvi/trial3` yields `Invalid Argument: ashvi/trial3` for me. Any suggestions on how to run this benchmarking suite? I am using v10.2.1 in case it helps to reproduce this issue. Thanks!

**Comment by michaellarabel** [comment]
Thanks for the feedback.

The latest PTS Git has improved error message and new enable-repo helper to make the process more clear.

With ~98% of PTS usage being users running just the official tests and then another percent or so being users running their own tests/suites (and having logged into their OB account on their system and thus enabled the repo in the process), there is a small niche of users who are trying to access a third-party/unofficial test without logging into an account. So for that the latest PTS Git today makes the process more clear that the user is trying to run such a test or suite and then informs them of how they can opt to enable that repo if desired.

So for the latest Git and upcoming PTS 10.2.2 this behavior should be more clear. Thanks!

![Screenshot from 2021-02-06 08-02-20](https://user-images.githubusercontent.com/6035554/107120313-9452e680-6852-11eb-89a9-a19f2ac2ed8c.png)
![Screenshot from 2021-02-06 08-07-49](https://user-images.githubusercontent.com/6035554/107120318-987f0400-6852-11eb-9452-0c88b2d3a0fc.png)
