### ISSUE TITLE
How to test the performance of the compiler

### ISSUE THREAD

**Issue by tianwei08222** [phoronix-test-suite/phoronix-test-suite#502]
How to test the performance of the compiler，Can you give a specific test method？

**Comment by michaellarabel** [comment]
PTS will respect any CFLAGS/CXXFLAGS you st as well as your PATH if specifying an alternative compiler. From there you can run any of the common C/C++ benchmarks for benchmarking. See the compiler benchmark articles on Phoronix.com if looking for particular test recommendations or the like.
