### ISSUE TITLE
stress-run repeatedly reads test definitions

### ISSUE THREAD

**Issue by OttoHollmann** [phoronix-test-suite/phoronix-test-suite#505]
It seems like phoronix-test-suite is reading `test-definition.xml` and `pts-install.xml` very often (thousands reads per minute) when running stress-run. This causing high utilization of php Zend resources and may lead php to crash. Many Zend resources get created and destroyed and eventually indices used in `executor_globals.regular_list` reach maximum value `0x80000000` (member nNextFreeElement). We are still investigating this php issue and we are going to open issue with php as well.

We found, that test definition is read from `__constructor` of `class pts_test_profile_parser`
https://github.com/phoronix-test-suite/phoronix-test-suite/blob/9703b4bc0738df93a1baa31446d64b85dd9090f4/pts-core/objects/pts_test_profile_parser.php#L119
which is called from constructor of `class pts_test_profile` which extends `pts_test_profile_parser`.

But is still unclear why it's necessary to read this file so often.
Can you consider rewriting your tests to reduce reading of these definitions?

**Comment by michaellarabel** [comment]
Actually this shouldn't be the case if using the latest PTS Git, should actually be addressed by recent improvements currently in Git. At one point there was the possibility of the XML structure being modified in-memory so would be freshly re-read from disk but that is no longer the case.
