### ISSUE TITLE
batch benchmark testing went wrong

### ISSUE THREAD

**Issue by BenniProbst** [phoronix-test-suite/phoronix-test-suite#506]
C:\phoronix-test-suite-10.2.2>phoronix-test-suite create-test-profile
Starting the Phoronix Test Suite

    [NOTICE] file_put_contents(C:\Users\Benni\Downloads\mdstool-cli.exe): Failed to open stream: No such file or directory in pts_network:216
The create-test-profile helper will attempt to walk you through creating the basics of creating a new test profile for execution by the Phoronix Test Suite. Follow the prompts to begin filling out the XML meta-data that defines a test profile.

Enter an identifier/name for the test profile: morpheus_test
Creating test profile: local/morpheustest @ C:\Users\Benni\.phoronix-test-suite\test-profiles/local/morpheustest

Phoronix Test Suite v10.2.2
test-definition.xml Creation

Title
The title of the test profile / the program under test. The title is shown on the test profile, the test results/graphs, etc.

PhoronixTestSuite/TestInformation/Title: Try to test a morpheus model

AppVersion
The AppVersion is the application/program version, if relevant, for the workload being tested. This is used for showing on the test results and elsewhere while the actual test profile is versioned separately.

PhoronixTestSuite/TestInformation/AppVersion: 2.1.1

Description
A summary of the program/application being benchmarked or a description of what the test profile is testing.

PhoronixTestSuite/TestInformation/Description: Try to model a cell cycle

ResultScale
The result scale string, if relevant for the test. Common result scales include Frames Per Second, MB/s, GFLOPS, Seconds, etc.

PhoronixTestSuite/TestInformation/ResultScale: CPU load for each second

Proportion
Possible Values: LIB, HIB, ABSTRACT,
Multiple Selections Allowed: NO
HIB or LIB are relevant values for the Proportion to indicate if higher results are better (HIB) or lower is better (LIB) depending upon result scale.
Default Value: HIB

1: LIB
2: HIB
3: ABSTRACT
4:
Select from the supported options: 2

Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in C:\phoronix-test-suite-10.2.2\pts-core\objects\pts_validation.php:500
Stack trace:
#0 C:\phoronix-test-suite-10.2.2\pts-core\objects\pts_validation.php(500): implode(',', 'HIB')
#1 C:\phoronix-test-suite-10.2.2\pts-core\objects\pts_validation.php(431): pts_validation::xsd_nodes_to_cli_prompts(Array, Object(nye_XmlWriter))
#2 C:\phoronix-test-suite-10.2.2\pts-core\commands\create_test_profile.php(65): pts_validation::xsd_to_cli_creator('C:\\phoronix-tes...', Object(nye_XmlWriter), Array)
#3 C:\phoronix-test-suite-10.2.2\pts-core\objects\client\pts_client.php(1528): create_test_profile::run(Array)
#4 C:\phoronix-test-suite-10.2.2\pts-core\phoronix-test-suite.php(152): pts_client::execute_command('create_test_pro...', Array)
#5 {main}
  thrown in C:\phoronix-test-suite-10.2.2\pts-core\objects\pts_validation.php on line 500

**Comment by BenniProbst** [comment]
*Windows

**Comment by michaellarabel** [comment]
A fix for this should now be in PTS Git, thanks.
