### ISSUE TITLE
Application oriented testing

### ISSUE THREAD

**Issue by BenniProbst** [phoronix-test-suite/phoronix-test-suite#508]
It is great that PTS can monitor software and hardware on different systems, but if you want to log system performance in orientation of a software program you need to add git support to load a revision of your software, compile it automatically and review the performance of an input job. And if that may exist, you may consider improving the documentation. Most programmers really need a platform that is Application oriented and not only Hardware testing oriented. Compare application versions on a system vs comparing systems upon an application. And the process of testing and compiling multiple versions should be simple. Consider a gui for that, it just needs to be stacked ontop.

**Comment by mtippett** [comment]
Hi  Ben,

The phoromatic test orchestration system is likely the best approach for
you.

You can use can configure a system, to respond to a trigger, which we use
to set as context.  Switching context is entirely specific to a use case,
and so you can create a script that can check out and prepare that code fr
use as part of the system under test.

If your needs are commercial in nature, please reach out to
matthew@phoronix.com to discuss.  There might be other options that may
suit your needs.

Matthew

**Comment by BenniProbst** [comment]
Oh I will just fix that Variation testing with a Script. Thank you
