### ISSUE TITLE
pts/fhourstones mirrors broken

### ISSUE THREAD

**Issue by snigel** [phoronix-test-suite/phoronix-test-suite#51]
I've seen this for a couple of days now, so I don't think it's an intermittent issue.

snigel@ubuntu:~/phoronix-test-suite$ ./phoronix-test-suite force-install fhourstones

Phoronix Test Suite v5.6.0m2

    To Install: pts/fhourstones-1.1.0

    Determining File Requirements ...........................................................................................................
    Searching Download Caches ...............................................................................................................

    1 Test To Install
        1 File To Download [0.01MB]
        1MB Of Disk Space Is Needed

    pts/fhourstones-1.1.0:
        Test Installation 1 of 1
        1 File Needed [0.01 MB / 1 Minute]
        Downloading: Fhourstones.tar.gz                                                                                              [0.01MB]
        Estimated Download Time: 1m .........................................................................................................
            Checksum Failed: http://homepages.cwi.nl/~tromp/c4/Fhourstones.tar.gz
            Attempting to download from alternate mirror.
        Downloading: Fhourstones.tar.gz                                                                                              [0.01MB]
            Download Failed: ftp://ftp.es.freebsd.org/pub/FreeBSD/ports/distfiles/Fhourstones.tar.gz
            Attempting to download from alternate mirror.
        Downloading: Fhourstones.tar.gz                                                                                              [0.01MB]
            Download Failed: ftp://ftp.uni-hannover.de/pub/mirror/bsd/FreeBSD/ports/distfiles/Fhourstones.tar.gz
            Downloading of needed test files failed.

**Comment by michaellarabel** [comment]
This test profile has been updated on OpenBenchmarking.org with a new download mirror hosted by Phoronix-Test-Suite.com to replace the stale links. Thanks!
