### ISSUE TITLE
cpu-usage records always the same value

### ISSUE THREAD

**Issue by m4v** [phoronix-test-suite/phoronix-test-suite#518]
If I try to monitor cpu.usage in a test, the data always has the same value, see attached result. In this case all data points are "1.00". It doesn't happen with other sensors.

Phoronix-test-suite 10.2.2 Ubuntu 20.04

[composite.txt](https://github.com/phoronix-test-suite/phoronix-test-suite/files/6330561/composite.txt)

**Comment by michaellarabel** [comment]
This issue happened to be fixed in Git in a while back, so would recommend using Git or v10.6 when formally available.
