### ISSUE TITLE
[osx ppc 10.5.8] pts/minion solitaire never finishes(?)

### ISSUE THREAD

**Issue by snigel** [phoronix-test-suite/phoronix-test-suite#52]
The first minion benchmark passed fine, but the solitaire never finished.
I let the computer (iBook G4 1.33GHz / 1.5GB) run the benchmark for 30 hours straight.

Since a raspberry pi can finish this test in less than 1.5 hours it seems like something is wrong.
Is there a way to better debug what's happening in the test? Perhaps it's something with PPC?

**Comment by michaellarabel** [comment]
Likely something to do with PPC but unfortunately I have no PPC hardware to test directly. I'd look at the phoronix-test-suite debug-run minion and then try running the minion binary (mentioned in the output of the debug-run) directly to see if you can see what's happening, but is likely an issue with the upstream test code as opposed to the Phoronix Test Suite.

**Comment by snigel** [comment]
Thank you, I will try that and see if I can provide more details.

**Comment by michaellarabel** [comment]
Did you find out any more about the minion issue on OS X?

**Comment by snigel** [comment]
Sorry for a really late reply.

I tried running "phoronix-test-suite debug-run minion"
Then I selected all tests, every test finished successfully.

Solitaire took 1059 seconds, which is ~20 minutes. Seems normal for the machine.

I will update my installation of phoronix-test-suite and try a regular run with the latest version.

**Comment by snigel** [comment]
With the latest version I had no problem to compile and run the whole suite of minion.
So I'm closing this.
