### ISSUE TITLE
Local tests repo isn't present on client nodes

### ISSUE THREAD

**Issue by antonym** [phoronix-test-suite/phoronix-test-suite#520]
Tests suites that are created on the phoromatic server are not showing up on the clients.  I have tried the latest stable as well as latest master (6e63ccdd44de5f66eb045f59007e8aebc4874b03).

From the phoromatic server:

root@phoromatic:/# tree -P "test1" --matchdirs --prune
```
.
└── var
    └── lib
        └── phoronix-test-suite
            └── test-profiles
                └── local
                    └── test1
```
root@phoromatic:~/phoronix-test-suite# phoronix-test-suite list-available-tests | grep -i local
local/test1                 test

From a client:

root@NDA-1-02-U27:~# phoronix-test-suite phoromatic.explore

Phoronix Test Suite v10.4.0m1
Phoromatic Servers

IP: 10.127.89.250
HTTP PORT: 10080
WEBSOCKET PORT: 8502
SERVER: PHP 7.4.3 Development Server
PHORONIX TEST SUITE: Phoronix Test Suite v10.4.0m1 [10311]
DOWNLOAD CACHE: 0 FILES / 0 MB CACHE SIZE
SUPPORTED OPENBENCHMARKING.ORG REPOSITORIES:
      git - Last Generated: 20 Apr 2021 15:00
      pts - Last Generated: 20 Apr 2021 15:00
      system - Last Generated: 20 Apr 2021 15:00
      windows - Last Generated: 20 Apr 2021 15:00

The local repo never appears to show up as an available repository here.  I've noticed a few others on the forum have not been able to get it to work either. (https://github.com/phoronix-test-suite/phoronix-test-suite/issues/255) Is there an index or something else that needs to be set or does the local repository need to be enabled somewhere? What is the best way to ensure the clients can see tests from the server and execute them?

**Comment by michaellarabel** [comment]
The local/ tests won't show up as a repository itself (such as listed via the phoromatic.explore) as they are a special case. If the client though is connected to a Phoromatic account, it will directly query the Phoromatic Server when hitting an unrecognized test identifier. If that test profile is on the Phoromatic Server / visible to the Phoromatic Server, it should then be automatically downloaded. Is your client not connected to a current Phoromatic account [having run phoromatic.connect...]? On the Phoromatic Server in the log file you should also see some entry around 'XXX requested a copy of the XYZ test' or ' requested a fallback copy of the '.

**Comment by antonym** [comment]
Ok, good to know they won't show up there.  The client is connected to the server and is idle waiting for a task.  When I attempt to download the test I get this at the client:

root@NDA-1-02-U27:~# phoronix-test-suite install local/test1
    [PROBLEM] Invalid Argument: local/test1
CORRECT SYNTAX:
phoronix-test-suite install [Test | Suite | OpenBenchmarking ID | Test Result]  ...
See available tests to run by visiting OpenBenchmarking.org or running:
    phoronix-test-suite list-tests
Tests can be installed by running:
    phoronix-test-suite install <test-name>

But on the server, I see this:

[Tue Apr 20 16:01:39 2021] 10.127.90.205:44334 Accepted
[Tue Apr 20 16:01:39 2021] 10.127.90.205:44334 [200]: GET /server.php
[Tue Apr 20 16:01:39 2021] 10.127.90.205:44334 Closing
[Tue Apr 20 16:01:39 2021] 10.127.90.205:44336 Accepted
[Tue Apr 20 16:01:39 2021] 10.127.90.205:44336 [200]: GET /openbenchmarking-cache.php?is_test&repo=&test=local/test1
[Tue Apr 20 16:01:39 2021] 10.127.90.205:44336 Closing
[Tue Apr 20 16:01:39 2021] 10.127.90.205:44338 Accepted
[Apr 20 16:01:39 2021] 10.127.90.205 requested a fallback copy of the local/test1 test profile
[Tue Apr 20 16:01:39 2021] 10.127.90.205:44338 [200]: GET /openbenchmarking-cache.php?test&repo=local&test=test1
[Tue Apr 20 16:01:39 2021] 10.127.90.205:44338 Closing

So it looks like it's attempting to reach out but failing to download for some reason.

**Comment by michaellarabel** [comment]
So indeed it appears to be querying the Phoromatic Server fine it sees the test ('is_test' passes) and so then tries to download it.

If you happen to have basic debug experience for printing some extra output, adding any additional output around https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/pts-core/objects/pts_openbenchmarking.php#L674 would likely show what's happening. It's working fine on my end but guessing there might be some corner case going awry.

**Comment by antonym** [comment]
^ That seemed to help as I can pull the test down now to a remote node, think I also needed php-zip installed... is there a way to pull suites as well in a similar manner?  The suites I created on the phoromatic server aren't showing up with a list-suites on the remote node.  Is there something that needs to be done to enable remote download of the suites?

**Comment by michaellarabel** [comment]
Yes this issue should be fixed with Git. Custom suites from the Phoromatic Server aren't pulled to clients unless the client is running it as part of a scheduled event from Phoromatic due to similar complexities around the test handling.
