### ISSUE TITLE
Dota 2 test: "The test run did not produce a result"

### ISSUE THREAD

**Issue by adrfantini** [phoronix-test-suite/phoronix-test-suite#528]
I'm trying to benchmark Dota 2 on my machine (in particular, Vulkan VS OpenGL) using the default test profile (`phoronix-test-suite benchmark dota2`). The game starts, but exists after a few seconds. The only output I get in PTS is `The test run did not produce a result`. The tests will then continue until all have failed.

If run normally, the game works correctly both using OpenGL and Vulkan.

What can I do to debug this?

Output of `diagnostics`: https://pastebin.com/aNLv121m
Output of `system-info`: https://pastebin.com/pgvFcWT2

**Comment by michaellarabel** [comment]
You can try `phoronix-test-suite debug-run dota2` but long story short likely running into some Steam path or library issue. Automating around Steam on Linux tends to be a mess and running the Steam game benchmarks outside of a stock install of Ubuntu with the default Steam paths you may have your mileage vary and may need to manually muck around with the test install script.

**Comment by adrfantini** [comment]
Thanks Michael for the reply.
FYI this is the debug output of the command you suggested: https://pastebin.com/zUueFh3Z
The log file is empty.

If running the benchmark "manually" from the CLI (copying the command from the template line), I get this:
```
>  /home/adriano/.steam/steam/steamapps/common/dota\ 2\ beta/game/bin/linuxsteamrt64/dota2 -novid +cl_showfps 1 +timedemo pts2 +demo_quitafterplayback 1 +fps_max 0 -novconsole -fullscreen +timedemo_start 1 +timedemo_end 1000 +bench_start dota2.bench
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/home/adriano/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198122978546 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561198122978546
Setting breakpad minidump AppID = 373300
Attempting to create OpenGL context: v3.3 (Core profile)...success. Checking entry points...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success. Checking entry points...success.
DumpContextInfo: OpenGL vendor Intel
DumpContextInfo: OpenGL renderer Mesa Intel(R) HD Graphics 530 (SKL GT2)
DumpContextInfo: Using OpenGL context version 4.6
DumpContextInfo: Context supports GLSL version 4.60
Fontconfig warning: "/home/adriano/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/adriano/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
 failed to dlopen "libtensorflow.so" error=libtensorflow.so: cannot open shared object file: No such file or directory
LuaDbg - Debugging stopped
CSteam3Client::Shutdown
[S_API FAIL] Tried to access Steam interface STEAMCHAT_INTERFACE_VERSION003 before SteamAPI_Init succeeded.
```

If running manually the command found in `~/.phoronix-test-suite/installed-tests/pts/dota2-1.2.6/dota2-benchmark`, nothing starts:
```
$ . steam-env-vars.sh
ERROR: ld.so: object '/home/adriano/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameMode ERROR: Could not connect to bus: '=' character not found or has no value following it
dbus[27665]: arguments to dbus_connection_unref() were incorrect, assertion "connection != NULL" failed in file dbus-connection.c line 2822.
This is normally a bug in some application using the D-Bus library.

gamemodeauto: Could not connect to bus: '=' character not found or has no value following it

$ ./dota.sh +con_logfile $LOG_FILE +timedemoquit dota2-pts-1971360796 +demo_quitafterplayback 1 +cl_showfps 2 +fps_max 0 -nosound -noassert -console -fullscreen +timedemo_start 50000 +timedemo_end 51000 -autoconfig_level 3 -testscript_inline \"Test_WaitForCheckPoint DemoPlaybackFinished\; quit\" $@
ERROR: ld.so: object '/home/adriano/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameMode ERROR: Could not connect to bus: '=' character not found or has no value following it
dbus[27679]: arguments to dbus_connection_unref() were incorrect, assertion "connection != NULL" failed in file dbus-connection.c line 2822.
This is normally a bug in some application using the D-Bus library.

gamemodeauto: Could not connect to bus: '=' character not found or has no value following it
bash: ./dota.sh: No such file or directory
ERROR: ld.so: object '/home/adriano/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameMode ERROR: Could not connect to bus: '=' character not found or has no value following it
dbus[27682]: arguments to dbus_connection_unref() were incorrect, assertion "connection != NULL" failed in file dbus-connection.c line 2822.
This is normally a bug in some application using the D-Bus library.

gamemodeauto: Could not connect to bus: '=' character not found or has no value following it
```

**Comment by BrunoHernandez** [comment]
Hi Adriano, it seems the Dota2 update has broken the test in both our computers so I'm looking at the issue as well but I have different error.

In my case I get a crash dump, so not looking very promising:
> crash_20210523194905_1.dmp[3055178]: Uploading dump (out-of-process)
> /tmp/dumps/crash_20210523194905_1.dmp

In your case, some env variable might be missing since the integrated graphics are being used:
> DumpContextInfo: OpenGL renderer Mesa Intel(R) HD Graphics 530 (SKL GT2)

For just debugging that might be OK but if we look at the following error:
>  failed to dlopen "libtensorflow.so" error=libtensorflow.so: cannot open shared object file: No such file or directory

I think it is expecting to find the NVidia card.

This error seems to be related to overlay:
> ERROR: ld.so: object '/home/adriano/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored. GameMode ERROR: Could not connect to bus: '=' character not found or has no value following it

I have warnings related to overlay as well. 
> ERROR: ld.so: object '/home/bruno/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

They don't seem to be important, but just in case you can disable the Steam overlay in the Steam options for Dota2. You will notice that overlay message will no longer show up in the pre-test script.
Also overlay will slightly impact your benchmark results.

**Comment by adrfantini** [comment]
I'm very sorry I forgot to reply.
I have tested again and it appears that now, after a few updates (who knows what, if the game itself or some system component), the benchmarks seem to run fine for me. They are still very outdated and imho too short to be able to draw a proper statistics, but they already provide a good baseline.

(FYI, Vulkan is about 5% faster than OpenGL on average on my system, using the Nvidia  graphics card).
