### ISSUE TITLE
pts/byte benchmark 2, 3 and 4 broken

### ISSUE THREAD

**Issue by snigel** [phoronix-test-suite/phoronix-test-suite#53]
I tried running the byte benchmark on a Ubuntu 14.10 machine on x86 (gcc 4.9) and on a osx 10.4 ppc machine.

The first test, Dhrystone 2, works fine while test 2-4 doesn't.
Integer Arithmetic, Register Arithmetic and Floating-Point  Arithmetic all give a score of 1.

Here is an example run:
http://openbenchmarking.org/result/1502131-DE-20150213186

Or from the terminal:
BYTE Unix Benchmark 3.6:
    pts/byte-1.2.0 [Computational Test: Register Arithmetic]
    Test 1 of 1
    Estimated Trial Run Count:    3
    Estimated Time To Completion: 7 Minutes
        Started Run 1 @ 21:58:24
        Started Run 2 @ 22:00:28
        Started Run 3 @ 22:02:33  [Std. Dev: 0.00%]

    Test Results:
        1
        1
        1

    Average: 1 LPS

**Comment by michaellarabel** [comment]
This is an issue with the upstream byte program it seems, so it's out of the scope of the Phoronix Test Suite due to breakage with byte and what seems to be an issue with newer compiler versions from what I've seen from my own testing.
