### ISSUE TITLE
pts/csgo unable to parse results

### ISSUE THREAD

**Issue by BrunoHernandez** [phoronix-test-suite/phoronix-test-suite#530]
The test csgo-1.6.0 runs the demo and produces results, but seems not to parse the format. If the debug function is used:
`phoronix-test-suite debug-run pts/csgo` 
The demo runs, and it ends with:
> The test run did not produce a result.

However if one looks at the log file:
> $HOME/.phoronix-test-suite/installed-tests/pts/csgo-1.6.0/csgo-1.6.0-1621872597-1.log

It seems to contain the test result data:

>demo tick,frame start time,frame start delta,frame swap time,frame swap delta,FPS variability
>
>6,6.931319,0.000000,7.806210,7.806210,0.000000
>7,7.806508,0.875189,9.095295,1.289085,0.000000
>8,9.095427,1.288919,9.110699,0.015404,62.124516
>9,9.110758,0.015331,9.114115,0.003416,287.679108
>
>(...)

If I understood correctly, the result format might have changed slightly and the key to parse results (csgo-1.6.0) is this one:
`<OutputTemplate>pts10.dem UNKNOWN #_RESULT_# </OutputTemplate>`

**Comment by michaellarabel** [comment]
pts/csgo-1.7.0 is since available and working fine with the latest CS:GO.
