### ISSUE TITLE
pts/disk where to specify the mountpoint?

### ISSUE THREAD

**Issue by colttt** [phoronix-test-suite/phoronix-test-suite#533]
Hello,

where can I specify the mountpoint for the disks benchmarks? I don't have a ~/.phronix* folder. It would be fine if I can do this via a variable.
When I try to run
`phoronix-test-suite user-config-set EnvironmentDirectory=/mnt/` it doesnt work

**Comment by michaellarabel** [comment]
The EnvironmentDirectory can be specified via ~/.phoronix-test-suite/user-config.xml or /etc/phoronix-test-suite.xml if running as root and will control where tests are installed/run by default.
