### ISSUE TITLE
Package name mispelling in test dependency detection

### ISSUE THREAD

**Issue by Sqeaky** [phoronix-test-suite/phoronix-test-suite#534]
On Gentoo Linux I tried running "phoronix-test-suite run pts/gl-vs-vk" and got an error indicating I needed to install `media-libs/vulkan-loder` should be "media-libs/vulkan-loader". I installed the package with the "a" in the world "loader" and it worked after that.

**Comment by michaellarabel** [comment]
Fixed, thanks.

**Comment by Sqeaky** [comment]
Wow, fast. Thanks,
