### ISSUE TITLE
Unable to obtain pts/amg-1.0.1 from OpenBenchmarking.org

### ISSUE THREAD

**Issue by alitx29** [phoronix-test-suite/phoronix-test-suite#536]
I am getting this error when started phormatic server. Please assist. 

[root@gievlcss14542a phoronix-test-suite]# phoronix-test-suite start-phoromatic-server

Port 8288 chosen as random port for this instance. Change the default port via the Phoronix Test Suite user configuration file.
Phoronix Test Suite v10.4.0 (Ibestad) starting Phoromatic Server
Phoronix Test Suite User-Data Directory Path: /var/lib/phoronix-test-suite/
Phoronix Test Suite Configuration File: /etc/phoronix-test-suite.xml
Phoromatic Server Log File: /var/log/phoromatic.log

Launching with PHP built-in web server.

The Phoromatic Web Interface Is Accessible At: http://localhost:8288

WebSocket Server Active: localhost:8266

    [PROBLEM] Unable to obtain pts/encoding-1.0.0 from OpenBenchmarking.org.  If this issue persists, file an issue @ https://github.com/phoronix-test-suite/phoronix-test-suite/issues

**Comment by michaellarabel** [comment]
Likely a firewall issue with the server making a false positive for blocking, should be flushed now, otherwise an ISP issue.
