### ISSUE TITLE
blender: The test run did not produce a result.

### ISSUE THREAD

**Issue by otoomet** [phoronix-test-suite/phoronix-test-suite#538]
I am running blender 1.9.0 test on an ubuntu 20.04 computer using pts 10.4.0.  The test fails with:

        Estimated Time To Completion: 22 Minutes [08:58 PDT] 
            Started Run 1 @ 08:37:06
            The test run did not produce a result.
            ...

The log file `.phoronix-test-suite/test-results/t470/test-logs/de3abfa266dc49bbd6b16d2bd0c849e2e52f6c86/blender-classroom.log` ends with messages

    Fra:1 Mem:471.47M (Peak 473.00M) | Time:01:02:15.28 | Remaining:00:00.13 | Mem:75.10M, Peak:75.82M | _mainScene, interior | Rendered 2039/2040 Tiles, Sample 300/300
    Fra:1 Mem:471.30M (Peak 473.00M) | Time:01:02:15.58 | Mem:74.93M, Peak:75.82M | _mainScene, interior | Rendered 2040/2040 Tiles
    Fra:1 Mem:471.30M (Peak 473.00M) | Time:01:02:15.58 | Mem:74.93M, Peak:75.82M | _mainScene, interior | Finished
    Saved: 'output.test0001.jpg'
     Time: 01:02:15.75 (Saving: 00:00.15)

    Error: Cannot read file '/home/otoomet/.phoronix-test-suite/installed-tests/pts/blender-1.9.0/blender-2.92.0-linux64/NONE': No such file or directory

    Blender quit

This happens when I choose _classroom_ and _CPU-Only_.  If I choose _OpenCL_, the result is fairly similar, just the directory that is not found is called _OPENCL_.

I tried with debug-run, it produced the command

    cd /home/otoomet/.phoronix-test-suite/installed-tests/pts/blender-1.9.0/ && ./blender -noaudio --enable-autoexec -b ../classroom_gpu.blend -o output.test -x 1 -F JPEG -f 1  NONE 2>&1

But I stopped the command before it finished.

As a side note, this is the second laptop where blender fails, but it works on two desktops that have fresh ubuntu-20 install.

I'd be happy to do some more debugging but the pts structure seems rather complex to me.

**Comment by michaellarabel** [comment]
Classroom itself may have issues if the system is under memory pressure but an upstream issue with it/Blender. This test profile has also since been updated against the recent Blender 3.0.
