### ISSUE TITLE
"This result viewer is deprecated [...] please open a bug report on GitHub."

### ISSUE THREAD

**Issue by flx42** [phoronix-test-suite/phoronix-test-suite#543]
... that's what I was faced with, so here I am.

I ran 3 separate benchmarks, merged them into a single file with `merge-results`, and then moved the resulting `merge-XXXX` folder to a nginx server so the `index.html` can be viewed from the web browser, and I get a red header message that says:
```
This result viewer is deprecated and by default the Phoronix Test Suite should be presenting the much more feature-rich modern result viewer since Phoronix Test Suite 9.0. If you continue to see this deprecated viewer used when launching the Phoronix Test Suite, please open a bug report on GitHub.
```

This was using `10.4.0` installed with the deb package from GitHub. 

Not a big deal, as the the current visualization I'm faced with seems just fine.

**Comment by michaellarabel** [comment]
That warning can be safely ignored. Basically if you saw that simple HTML/JS viewer when launched by phoronix-test-suite itself as opposed to seeing it when independently/externally loading that HTML file.

**Comment by flx42** [comment]
Got it, thanks!
