### ISSUE TITLE
Phoromatic has sqlite problems on Wheezy

### ISSUE THREAD

**Issue by cen1** [phoronix-test-suite/phoronix-test-suite#56]
Basically, when you want to display the results there is an SQLITE error that instr() does not exist. That function is used inside a prepared statement in phoromatic_result.php line 427 (and some other queries). Apparently an updated Wheezy has such an old php5-sqlite package that the function does not yet exist. I even tried to use dotdeb repositories and installed PHP 5.6.X but it was still a no go. On the end I removed the function and replaced it with a LIKE statement.

**Comment by michaellarabel** [comment]
If you happen to have a patch for it would be happy to integrate it. Thanks.

**Comment by cen1** [comment]
Allright, I'll make a pull request
