### ISSUE TITLE
pts/opevino does not install

### ISSUE THREAD

**Issue by CammyTetehJr** [phoronix-test-suite/phoronix-test-suite#567]
Hi, I am trying to install the pts/openvino test but I receive the error `The installer exited with a non-zero exit status. ERROR: VPU_OCL_COMPILER is not found` 

How can this issue be solved? I am running test on an embedded systems device running ubuntu 20.04.3

Thanks

**Comment by michaellarabel** [comment]
Check the mentioned log file in the output when seeing that install failure. OpenVINO has some messy dependencies and other build complexities upstream. It's likely hitting some OpenCV issues on the system as the most likely scenario.

**Comment by CammyTetehJr** [comment]
Thanks. I finally got it to install. However running the benchmark for Face Detection and Person Detection models on GPU exits, is that the expected behavior? CPU works fine for those models
