### ISSUE TITLE
Link to deb package on Downloads page is not https

### ISSUE THREAD

**Issue by martin-kokos** [phoronix-test-suite/phoronix-test-suite#573]
Link on https://www.phoronix-test-suite.com/?k=downloads
for _Ubuntu/Debian package_ is not `https` but `http`:
`http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_10.6.1_all.deb`

Not only is this not secure way to distribute executables, but also Chrome and Firefox (in some configurations) reject to download it, rightly so, due to risk of the file being potentially malicious.

**Comment by michaellarabel** [comment]
This has since been fixed, thanks.
