### ISSUE TITLE
Resume manually terminated test at last completed checkpoint 

### ISSUE THREAD

**Issue by FCLC** [phoronix-test-suite/phoronix-test-suite#574]

**Comment by michaellarabel** [comment]
Using the 'phoronix-test-suite finish-run' subcommand already provides this functionality. See the documentation for details.
-------- Original message --------From: FCLC ***@***.***> Date: 12/10/21  07:47  (GMT-06:00) To: phoronix-test-suite/phoronix-test-suite ***@***.***> Cc: Subscribed ***@***.***> Subject: [phoronix-test-suite/phoronix-test-suite] Resume manually terminated
  test at last completed checkpoint  (Issue #574)

**Comment by FCLC** [comment]
> Using the 'phoronix-test-suite finish-run' subcommand already provides this functionality. See the documentation for details.

My bad, should have RTFM in greater detail. Had been looking for the 'resume' keyword instead of finish
