### ISSUE TITLE
Readme section "Installation & Setup" misses to mention the exact commands  to install phoronix-test-suite

### ISSUE THREAD

**Issue by mi-hol** [phoronix-test-suite/phoronix-test-suite#579]
I'd suggest to insert a code block with the required commands, so its easy to copy & paste them

Code would be along the lines of
`wget -O - <URL_of_install_script> | bash`

**Comment by michaellarabel** [comment]
As mentioned in the docs, you can simply run within the directory, i.e. ./phoronix-test-suite but otherwise there is also the install scripts in the main directory.

**Comment by mi-hol** [comment]
@michaellarabel for a Linux pro its obvious how to download, install & run phoronix-test-suite but what about the newbies?
For example openmediavault (OMV) has many more users since  making installation "fool proof" for newbies via https://github.com/OpenMediaVault-Plugin-Developers/installScript#readme
I'd like to encourage those newbies to benchmark their OMV setup via dbench, but unfortunately at this time most of them would fail
