### ISSUE TITLE
Many extensions are required: how to overcome this?

### ISSUE THREAD

**Issue by ibobak** [phoronix-test-suite/phoronix-test-suite#588]
No matter of what command I am running, I am always gettng this: 

```(base) ihor@monster:~/github/phoronix-test-suite$ ./phoronix-test-suite help

The following PHP extensions are REQUIRED:

DOM       The Document Object Model is required for XML operations.
SimpleXML SimpleXML is required for XML operations.

The following PHP extensions are OPTIONAL but recommended:

GD        The GD library is recommended for improved graph rendering.
Bzip2     The bzcompress/bzip2 support can be used for greater file compression.
SQLite3   SQLite3 is required when running a Phoromatic server.
CURL      CURL is recommended for an enhanced download experience.
```

The command "install-dependencies" doesn't help either: it also outputs this stuff.

**Comment by nhubbard** [comment]
So the `install-dependencies` command only installs dependencies of test suites. These extensions are necessary for PTS to actually function.

If you're running a Linux distribution, you can use your package manager to install these extensions. For example, on the latest version of Ubuntu:

```bash
# Required extensions.
sudo apt install php8.0-dom php8.0-xml
# Optional extensions.
sudo apt install php8.0-gd php8.0-bz2 php8.0-sqlite3 php8.0-curl
```

If you're running Windows, you need to get the DLLs. (I believe these extensions are all core extensions and are therefore included with the default PHP build. Someone correct me if I'm wrong!)

If you're running macOS, it's somewhat of the same situation as Ubuntu, where the extensions are also included in the core PHP build you can install via Homebrew.

**Comment by michaellarabel** [comment]
As noted, you are likely missing a package called like php-dom or php-simplexml on your system (or might be prefixed php7-* / php8-* )
