### ISSUE TITLE
Tests failed to install in Alpine Linux

### ISSUE THREAD

**Issue by afzl-wtu** [phoronix-test-suite/phoronix-test-suite#591]
I could not find any working phoronix-test-suite for Alpine linux. So at the end I git cloneed you last stable release and thanks it worked but now I can ot install any test. I tried to install both pts/fio and compress-7zip but failed. Here is the log file output:

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (306C3),ASM,AES-NI)

Scanning the drive for archives:
1 file, 1215031 bytes (1187 KiB)

Extracting archive: 7z2106-src.7z
--
Path = 7z2106-src.7z
Type = 7z
Physical Size = 1215031
Headers Size = 20273
Method = LZMA:23
Solid = +
Blocks = 1

Everything is Ok

Files: 1242
Size:       8186206
Compressed: 1215031
mkdir -p _o
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/7zBuf2.o ../../../../C/7zBuf2.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/7zStream.o ../../../../C/7zStream.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Alloc.o ../../../../C/Alloc.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Bcj2.o ../../../../C/Bcj2.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Bcj2Enc.o ../../../../C/Bcj2Enc.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Blake2s.o ../../../../C/Blake2s.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Bra.o ../../../../C/Bra.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Bra86.o ../../../../C/Bra86.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/BraIA64.o ../../../../C/BraIA64.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/BwtSort.o ../../../../C/BwtSort.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/CpuArch.o ../../../../C/CpuArch.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Delta.o ../../../../C/Delta.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/HuffEnc.o ../../../../C/HuffEnc.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/LzFind.o ../../../../C/LzFind.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Lzma2Dec.o ../../../../C/Lzma2Dec.c
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Lzma2DecMt.o ../../../../C/Lzma2DecMt.c
In file included from ../../../../C/MtDec.h:10,
                 from ../../../../C/Lzma2DecMt.c:30:
../../../../C/Threads.h:74:9: error: unknown type name 'cpu_set_t'
   74 | typedef cpu_set_t CCpuSet;
      |         ^~~~~~~~~
cc      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Lzma2Enc.o ../../../../C/Lzma2Enc.c
make: *** [../../7zip_gcc.mak:1076: _o/Lzma2DecMt.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ../../../../C/MtDec.h:10,
                 from ../../../../C/MtCoder.h:7,
                 from ../../../../C/Lzma2Enc.c:13:
../../../../C/Threads.h:74:9: error: unknown type name 'cpu_set_t'
   74 | typedef cpu_set_t CCpuSet;
      |         ^~~~~~~~~
make: *** [../../7zip_gcc.mak:1078: _o/Lzma2Enc.o] Error 1

**Comment by michaellarabel** [comment]
This is an issue of the upstream program under test (in this case 7-Zip) on your given software/architecture but not of the Phoronix Test Suite itself.
