### ISSUE TITLE
Questions about some packages

### ISSUE THREAD

**Issue by FabioLolix** [phoronix-test-suite/phoronix-test-suite#596]
Hello, I'm on Arch Linux and I have PTS updated at last commit (AUR pkgbuild)

I have installed some suites with

> $ pts install video-encoding audio-encoding av1 imaging ocr vulkan-compute multicore

For some test there isn't the prompt for installing the system package, for gimp and darktable I've made a PR (#595 )

For gmic, rawtherapee-cli, hugin, gegl, tesseract, ocrmypdf and mako I haven't seen the \<Package> field in either `fedora-packages.xml`, `ubuntu-packages.xml` and `generic-packages.xml`

```
The following tests failed to install:

  - pts/dav1d-1.11.1
  - pts/libgav1-1.2.0
  - pts/encode-ape-1.4.0
    [collect2: error: ld returned 1 exit status]
  - system/gmic-1.0.0
    [ERROR: G'MIC is not found on the system! This test profile needs a working gmic installation in the PATH]
  - pts/webp2-1.0.0
    [libwebp2-master/src/dec/anim_dec.cc:128:21: error: ‘this’ pointer is null [-Werror=nonnull]]
  - system/rawtherapee-1.0.1
    [ERROR: RawTherapee is not found on the system! This test profile needs a working rawtherapee-cli in the PATH.]
  - system/gimp-1.1.3
    [ERROR: gimp is not found on the system! This test profile needs a working GIMP installation in the PATH]
  - pts/montage-1.0.0
    [collect2: error: ld returned 1 exit status]
  - system/hugin-1.0.0
    [ERROR: Hugin is not found on the system! This test profile needs a working hugin_executor in the PATH.]
  - system/darktable-1.0.5
    [ERROR: Darktable is not found on the system! This test profile needs a working Darktable installation]
  - system/gegl-1.0.0
    [ERROR: gegl is not found on the system! This test profile needs the 'gegl' commandline in the PATH]
  - system/tesseract-ocr-1.0.1
    [ERROR: Tesseract OCR is not found on the system! This test profile needs a working tesseract installation in the PATH. Check your system package manager for tesseract / tesseract-ocr.]
  - system/ocrmypdf-1.0.0
    [ERROR: OCRMyPDF is not found on the system! This test profile needs a working ocrmypdf in the PATH.]
  - pts/betsy-1.0.0
    [betsy-1.1-beta/Dependencies/FreeImage/Source/OpenEXR/Imath/ImathVec.h:2150:33: error: ISO C++17 does not allow dynamic exception specifications]
  - pts/libplacebo-1.0.0
    [Module 'mako' not found, please install 'python3-mako' or an equivalent package on your system!]
  - pts/yafaray-1.1.1
    [Core-3.5.1/include/core_api/surface.h:118:46: error: expected unqualified-id before ‘>’ token]
  - pts/n-queens-1.2.1
    [/usr/sbin/ld: cannot find -lgomp]
  - pts/john-the-ripper-1.7.2
    [blake2b_plug.c:274:3: error: size of array element is not a multiple of its alignment]
  - pts/build-wasmer-1.0.0
    [error: build failed]
  - pts/v-ray-1.3.0
  - pts/oneapi-level-zero-1.0.0
    [clang-format-7 not found.  clang-format and clang-format-check targets will]
  - pts/openvino-1.0.4
    [-- Looking for pthread_create in pthreads - not found]
```

**Comment by michaellarabel** [comment]
The SystemDependencies field is automatically queried using any file-to-dependency resolver / reverse dependency calculation supported by the host's package manager.

In the case of Arch Linux, if pkgfile is installed and the cache for it present, it should automatically query pkgfile for figuring out the package names based on the binary / header file names - https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/pts-core/external-test-dependencies/dependency-handlers/arch_dependency_handler.php

The older ExternalDependencies field is what relies on the static lists.

**Comment by FabioLolix** [comment]
> In the case of Arch Linux, if pkgfile is installed and the cache for it present, it should automatically query pkgfile for figuring out the package names based on the binary / header file names

Ok, I don't have pkgfile installed in fact.

***

Another thing, in `arch-packages.xml` are listed qt4, mongodb and dune (dune-common dune-grid dune-istl) which are no longer in Arch repository
