### ISSUE TITLE
pts/apache-2.0.0 fails with "./apache: 2: /go/bin/bombardier: not found" on Ubuntu 20.04

### ISSUE THREAD

**Issue by msLinuxNinja** [phoronix-test-suite/phoronix-test-suite#599]
Running the pts/apache-2.0.0 benchmark on Ubuntu 20.04 fails with:
```
Apache HTTP Server 2.4.48:
    pts/apache-2.0.0 [Concurrent Requests: 1000]
    Test 1 of 1
    Estimated Trial Run Count:    3
    Estimated Time To Completion: 6 Minutes [20:37 UTC]
        Running Pre-Test Script @ 20:31:54
        Started Run 1 @ 20:31:59
        The test quit with a non-zero exit status.
        Started Run 2 @ 20:32:03
        The test quit with a non-zero exit status.
        Started Run 3 @ 20:32:07
        The test quit with a non-zero exit status.
        E: ./apache: 2: /go/bin/bombardier: not found
```
  This could be due to the install script running `go get -u github.com/codesenberg/bombardier` and the default version of golang in Ubuntu 20.04 `go1.13.8`:

```bash
# go get -u github.com/codesenberg/bombardier
# golang.org/x/net/http2
/root/go/src/golang.org/x/net/http2/transport.go:417:45: undefined: os.ErrDeadlineExceeded
```

**Comment by michaellarabel** [comment]
This is a bug in Ubuntu 20.04's Go package. Go either needs to be upgraded to newer version or using an older version of the test w/o Bombardier like pts/apache-1.7.2.

**Comment by msLinuxNinja** [comment]
For completion’s sake and in case anyone is looking for this, pts/apache-2.0.0 can be used on Ubuntu 20.04, simply install go from source to at least version 1.17 and then create a symlink `ln -s /usr/local/go/bin/go /usr/bin/go`
