### ISSUE TITLE
Unable to delete published result on OpenBenchmarking

### ISSUE THREAD

**Issue by CammyTetehJr** [phoronix-test-suite/phoronix-test-suite#600]
Hi @michaellarabel , I see it is not possible to delete an uploaded result on OpenBenchmarking, I saw from a thread from last year that you could help delete from your end. Can you help delete this  https://openbenchmarking.org/result/2202163-UPBO-MERGE3024 

I had an error on the description. Adding a feature to delete an uploaded result will be useful. Thanks

**Comment by michaellarabel** [comment]
Deleted now.
