### ISSUE TITLE
[Request] Please add RandomX (CPU Mining) Benchmark with XMRig

### ISSUE THREAD

**Issue by hilga007** [phoronix-test-suite/phoronix-test-suite#602]
In addition to being a CPU mining and OpenCL mining program, [XMRig](https://github.com/xmrig/xmrig) is a benchmarking tool. It can benchmark the rx/0 and rx/wow algorithms which are monero and wownero respectively. Requesting this be added as a benchmark option.

**Comment by michaellarabel** [comment]
xmrig has long been available via PTS - https://openbenchmarking.org/test/pts/xmrig
