### ISSUE TITLE
Quick start guide

### ISSUE THREAD

**Issue by flip111** [phoronix-test-suite/phoronix-test-suite#608]
I'm first time user and i want to run all available tests, get a report and possible upload to open benchmark.

I installed the phoronix-test-suite program. Then i guessed these were the right commands. First i ran `batch-setup`, then i tried `batch-run` but it needs an argument which i don't know.

The manual is confusing to me, i can't figure out what `[Test | Suite | OpenBenchmarking ID | Test Result] ...` means, what options i can put there, and what option to put to run all available tests.

**Comment by michaellarabel** [comment]
https://github.com/phoronix-test-suite/phoronix-test-suite#usage

**Comment by flip111** [comment]
I've read that and it's not clear to me.
