### ISSUE TITLE
Question regarding SQLite3 test

### ISSUE THREAD

**Issue by GiorgiKvernadze** [phoronix-test-suite/phoronix-test-suite#611]
Hello,

Could you tell me what kind of test is being done with SQLite3 in this test suite?
I'd like to recreate the test without the suite, since the platform I'm using doesn't support it in its current state and I'd like to compare with the results shown on the openbenchmarking website,
Thank you for your time.

**Comment by michaellarabel** [comment]
https://openbenchmarking.org/innhold/2e1c83c650102ccd3234cce60efa7a9c7c193601

https://openbenchmarking.org/innhold/70b7540d30edd0c070f7c79b21d489f7504c7bac
