### ISSUE TITLE
PTS_IS_DAEMONIZED_SERVER_PROCESS Environment Variable not recognized 

### ISSUE THREAD

**Issue by ssgrummons** [phoronix-test-suite/phoronix-test-suite#615]
I am trying to run the Phoromatic Server in a container and have found that the `start-phoromatic-server` command does not recognize the `PTS_IS_DAEMONIZED_SERVER_PROCESS` environment variable.  In order to get the `start_phoromatic_server.php` code to actually pickup the environment variables I set, I had to replace `PTS_IS_DAEMONIZED_SERVER_PROCESS` in the code with `getenv('PTS_IS_DAEMONIZED_SERVER_PROCESS')`.  So after adding the following line, the containers would start and continue running without the `Press [ENTER] to kill server...` prompt:
```
RUN sed -i "s/PTS_IS_DAEMONIZED_SERVER_PROCESS/getenv('PTS_IS_DAEMONIZED_SERVER_PROCESS')/g" ${INSTALL_DIR}/pts-core/commands/start_phoromatic_server.php
```

Now my container works whether or not I set `ENV PTS_IS_DAEMONIZED_SERVER_PROCESS=1` or `ENV PTS_IS_DAEMONIZED_SERVER_PROCESS="True"` in my Dockerfile.  

For what it is worth, I am not specifying the version of PHP in my Dockerfile and am just pulling the most recent version: `yum install -y php php-xml php-gd php-sqlite3 php-posix php-cli php-json php-zip`.

**Comment by michaellarabel** [comment]
PTS_IS_DAEMONIZED_SERVER_PROCESS has never been an environment variable. It's logic is set @ https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/pts-core/pts-core.php#L121

Presumably your container is restricting /var/lib or /etc writes or so, so perhaps the logic there just needs to be extended to accommodate more container setups.

**Comment by ssgrummons** [comment]
Thanks!  I was basing my work off of https://github.com/mgasiorowski/phoromatic-server-docker/blob/master/Dockerfile which set that using `ENV PTS_IS_DAEMONIZED_SERVER_PROCESS=1`, but now I was able to just edit the permissions of those two directories and get it to work.

Here is my improved Dockerfile: https://github.com/ssgrummons/phoromatic-server-docker 

Thanks!
