### ISSUE TITLE
RFE: Support blender on aarch64

### ISSUE THREAD

**Issue by jvillal-amp** [phoronix-test-suite/phoronix-test-suite#619]
Currently when I try to run `pts/blender` on aarch64 (Ampere Altra/AltraMAX) I get the following message:

```
# phoronix-test-suite batch-benchmark pts/blender


        pts/blender-3.0.0 is not supported on this architecture: aarch64
```

Would be great if support could be added.

**Comment by michaellarabel** [comment]
The test profile relies on the upstream Blender binaries to which they do not currently provide any for Linux AArch64. The `system/blender` test profile can be run instead that will try to use Blender from your distro's package manager if available on the system for AArch64 and other archs.

**Comment by jvillal-amp** [comment]
Thanks for the possible work-around.
