### ISSUE TITLE
RFE: Support pts/compress-rar on aarch64

### ISSUE THREAD

**Issue by jvillal-amp** [phoronix-test-suite/phoronix-test-suite#620]
Currently when I try to run `pts/compress-rar` on aarch64 (Ampere Altra/AltraMAX) I get the following message:

```
# phoronix-test-suite batch-benchmark pts/compress-rar


        pts/compress-rar-1.2.0 is not supported on this architecture: aarch64
```

Would be great if support could be added.

**Comment by michaellarabel** [comment]
The upstream WinRAR/Rarlab (proprietary) used does not currently provide any Linux AArch64 binaries.

**Comment by jvillal-amp** [comment]
Thanks for the info.
