### ISSUE TITLE
Efficient way to debug benchamark failures

### ISSUE THREAD

**Issue by himadrics** [phoronix-test-suite/phoronix-test-suite#629]
Sometime benchmarks crash and I struggle to find the reason. The information printed on console is not particularly useful in some cases. For example, messages like "The test exited with a non-zero status" or "This test didn't produce a result" doesn't say much about what to do in order to fix it. I often find empty result directories and no logs under ~/.phoronix-test-suite/test-results/ in such cases. I often also don't find anything useful in /var/log/phoronix-test-suite-benchmark.log as well.

Is there some other phoronix specific place/file that I should be looking at? I can use some advice in general on debugging steps for fixing benchmark failures with phoronix. Thanks.

**Comment by michaellarabel** [comment]
Using `phoronix-test-suite debug-run [test]` will output debugging information and also preserve the log files in the test install directory.
