### ISSUE TITLE
zstd benchmark misleading

### ISSUE THREAD

**Issue by haampie** [phoronix-test-suite/phoronix-test-suite#633]
The [Clear Linux benchmark for ZStandard](https://www.phoronix.com/scan.php?page=article&item=h1-2022-linux&num=3) is misleading

They add a patch to enable threading by default with 4 threads:

https://github.com/clearlinux-pkgs/zstd/blob/main/multi-thread-default.patch

It's more fair to set `ZSTD_NBTHREADS=1` before running `zstd -b...`

**Comment by michaellarabel** [comment]
There is nothing misleading about it - Linux distros often patch their packages for better defaults / optimizations / tuning. The PTS system/* tests are intended to benchmark the underlying system packages. system/compress-zstd is used for evaluating the performance of the underlying Zstd while those wanting to compare the same Zstd build and options can use the pts/compress-zstd test profile where it's all from the same source build. It isn't misleading in my article either as the intent was looking at the defaults/out-of-box performance. Hopefully more Linux distros improve their defaults or that patch is upstreamed.
