### ISSUE TITLE
Contains XMRig mining scripts!

### ISSUE THREAD

**Issue by github-young** [phoronix-test-suite/phoronix-test-suite#654]
Phoronix-test-suite contains XMRig mining scripts that caused my computer blocked by my ISP!
Please explicitly mark it otherwise users that do not inspect the project may face unncessary trouble.

**Comment by Evernow** [comment]
It is contained purposely as a benchmark: https://github.com/phoronix-test-suite/phoronix-test-suite/blob/89e05c275735dedec3cc52f51fd2761d17acdd62/ob-cache/test-profiles/pts/xmrig-1.0.0/test-definition.xml
