### ISSUE TITLE
build-php test fail but report success

### ISSUE THREAD

**Issue by ptzafrir** [phoronix-test-suite/phoronix-test-suite#66]
I'm running pts/build-php on my system, and the make of the php code fails.
However, I do get benchmark results by phoronix-test-suite.

I noticed that pts/build-linux-test time-compile-kernel script has a line at the 
echo $? > ~/test-exit-status

Which is not available in build/php time-compile script
Adding that to the bottom of the script, reported correctly that the test failed.
Is it missing on purpose?

**Comment by michaellarabel** [comment]
The test-exit-status to build-php was added a ways back but forgot to close this bug report.
