### ISSUE TITLE
Installing dependencies fails on Fedora 22

### ISSUE THREAD

**Issue by kaccardi** [phoronix-test-suite/phoronix-test-suite#67]
Fedora 22 has moved from yum to dnf.  The --skip-broken switch is no longer supported, and when phoronix attempts to install dependencies it fails as a result.

**Comment by michaellarabel** [comment]
This issue should already be fixed in the Phoronix Test Suite 5.8.0 release. Once upgrading, it will detect dnf and not pass the switch. Thanks anyhow for reporting.
