### ISSUE TITLE
blas and blas-devel installed but not detected

### ISSUE THREAD

**Issue by kaccardi** [phoronix-test-suite/phoronix-test-suite#68]
On Fedora 22, the blas and blas-devel packages are dependencies for a test in the "universe" benchmark.  They are correctly installed on the system, but phoronix-test-suite cannot detect them.

**Comment by michaellarabel** [comment]
With the latest Git now (https://github.com/phoronix-test-suite/phoronix-test-suite/commit/3c31134e17407758babbe4d2a8bf5472e0cd8e2c) the detection for blas development files has now changed so when running the new code it should properly see it as being installed. Thanks.
