### ISSUE TITLE
install fails for encode-ogg on Fedora 22 x86_64

### ISSUE THREAD

**Issue by kaccardi** [phoronix-test-suite/phoronix-test-suite#69]
/bin/sh ../libtool --tag=CC --mode=link gcc  -O2 -Wall -ffast-math -fsigned-char -g -O2   -o oggenc    oggenc.o audio.o encode.o platform.o resample.o skeleton.o ../share/libutf8.a ../share/libgetopt.a -lvorbisenc -lvorbis   -logg
libtool: link: gcc -O2 -Wall -ffast-math -fsigned-char -g -O2 -o oggenc oggenc.o audio.o encode.o platform.o resample.o skeleton.o  ../share/libutf8.a ../share/libgetopt.a -lvorbisenc -lvorbis -logg
/usr/bin/ld: resample.o: undefined reference to symbol 'sin@@GLIBC_2.2.5'
/usr/lib64/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:355: recipe for target 'oggenc' failed
make[2]: **\* [oggenc] Error 1
make[2]: Leaving directory '/home/kristen/.phoronix-test-suite/installed-tests/pts/encode-ogg-1.4.1/vorbis-tools-1.4.0/oggenc'
Makefile:412: recipe for target 'install-recursive' failed
make[1]: **\* [install-recursive] Error 1
make[1]: Leaving directory '/home/kristen/.phoronix-test-suite/installed-tests/pts/encode-ogg-1.4.1/vorbis-tools-1.4.0/oggenc'
Makefile:349: recipe for target 'install-recursive' failed
make: **\* [install-recursive] Error 1

**Comment by autentico** [comment]
I've got the same problem in Fedora 26 Alpha. 

_/usr/bin/ld: resample.o: undefined reference to symbol 'sin@@GLIBC_2.2.5'
/usr/lib64/libm.so.6: error adding symbols: DSO missing from command line_

This **_SOLUTION_** worked for me.
```
LDFLAGS="$LDFLAGS -lm"
export LDFLAGS
CFLAGS="$CFLAGS $LDFLAGS"
export CFLAGS
```
then, call the installer routine once again
`phoronix-test-suite benchmark encode-ogg`

It should work at this point.

It seems the newer linker doesn't include libm.so by default, so calling the installer routine with proper LDFLAGS seems to solve the issue.  

I hope @michaellarabel will update this call for the next version of PTS, in case my _fix_ is the right one.

**Comment by michaellarabel** [comment]
The pts/encode-ogg-1.5.0 test profile is now available that pulls in the latest Ogg/Vorbis library releases and should have fixes for these problems.
