### ISSUE TITLE
run：phoronix-test-suite benchmark fio The following error occurs

### ISSUE THREAD

**Issue by haolixu** [phoronix-test-suite/phoronix-test-suite#706]
[8192] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phodevi_linux_parser:612
![image](https://user-images.githubusercontent.com/26183306/222660356-c6e2a003-f786-4fda-93dc-95298e8a30b2.png)

**Comment by lwandrebeck** [comment]
The strpos error is just a warning (for now). You’re missing zlib.h, which comes from zlib1g-dev. Install it and fio will likely run smoothly.

**Comment by haolixu** [comment]
@lwandrebeck I installed ：apt install zlib1g-dev，but the same question as above。This is the relevant system information
![image](https://user-images.githubusercontent.com/26183306/223641631-9f552c9b-00f2-443d-b0d9-bd98731171b2.png)

**Comment by lwandrebeck** [comment]
@haolixu do you get the same error message complaining about missing zlib.h or ?
That said, I don't know if fio runs nicely on aarch64. I guess it should.
