### ISSUE TITLE
SleepTimeBetweenTests is not implemented

### ISSUE THREAD

**Issue by mburz** [phoronix-test-suite/phoronix-test-suite#713]
Testing Option `SleepTimeBetweenTests` as documented [here](https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/documentation/phoronix-test-suite.md) doesn't appear to be implemented (there is not reference to it in Code, not even v5.0.1 had it).
It would be great to add it, in some cases it's very useful.
If indeed obsolete, is there an alternative?

**Comment by jsfreischuetz** [comment]
Also interested in this. Commenting to follow
