### ISSUE TITLE
[osx ppc 10.5.8] pts/ffmpeg remove doc-generation from install script.

### ISSUE THREAD

**Issue by snigel** [phoronix-test-suite/phoronix-test-suite#73]
Currently the pts/ffmpeg compile fails on doc generation, if the doc generation is disabled it works fine.

The fix is simple, just change this line in the install script:
```
./configure --disable-zlib --prefix=$HOME/ffmpeg_/
```
To this
```
./configure --disable-zlib --disable-doc --prefix=$HOME/ffmpeg_/
```

More details on the issue:
https://trac.ffmpeg.org/ticket/4411
https://hexeract.wordpress.com/2009/04/12/how-to-compile-ffmpegmplayer-for-macosx/#comment-2846

I'd gladly update the code myself, but I don't know where the install scripts for this test is located.

**Comment by michaellarabel** [comment]
Thanks for reporting this OSX PPC issue. The latest test profile update for FFmpeg [http://openbenchmarking.org/innhold/831fd0f37175fda1045b50080ce8121553f0b9f9] now uses --disable-doc during the configure process.
