### ISSUE TITLE
Some test need glibc-static

### ISSUE THREAD

**Issue by madebr** [phoronix-test-suite/phoronix-test-suite#75]
Some tests do need glibc-static in order to be compiiled statically.
e.g. pts/fs-mark

Dependencies such as libaio-devel are installed automatically, but not glibc-static.

Maybe add this once?

**Comment by michaellarabel** [comment]
Sorry for the late response. What distribution are you using? glibc-static should be included on Fedora and other distributions when needed.

**Comment by madebr** [comment]
That was on Fedora 22.
I believe glibc-static is only installed when requested (either by dependency either explicitly).

**Comment by michaellarabel** [comment]
Glibc-static on Fedora is listed as part of the "build-utilities" external dependency so any test profile relying on building from source includes it, so it should be there.

**Comment by madebr** [comment]
I'm still working on this Fedora 22 system (will soon upgrade to 23).
I think it is a build dependency.
Since glibc-static is a static library (not a shared one), it should only be there at build time.

I can remove glibc-static (using dnf remove) without having to remove any other package because of the dependencies.
