### ISSUE TITLE
Wrong unit for "fio" test

### ISSUE THREAD

**Issue by MShekow** [phoronix-test-suite/phoronix-test-suite#762]
The [fio](https://openbenchmarking.org/test/pts/fio) test incorrectly parses the results and presents them as `MiB/s` when they are really `KiB/s`.

Here is an example excerpt of `fio`'s output (PTS parses the third line):
```
test: (groupid=0, jobs=1): err= 0: pid=3790: Wed Nov 22 09:23:35 2023
  write: IOPS=73, BW=299MiB/s (313MB/s)(17.8GiB/60944msec); 0 zone resets
   bw (  KiB/s): min=49152, max=753664, per=100.00%, avg=320003.53, stdev=157766.81, samples=115
```

**Comment by hongj520** [comment]
I have the same case.

**Comment by hongj520** [comment]
In the fio-2.0.0, the link is https://openbenchmarking.org/test/pts/fio-2.0.0.I find in the 2.0.0 results-definition.xml is diffrent the fio-1.15.0.
When I copy the  [Flexible IO Tester 1.15.0](https://openbenchmarking.org/test/pts/fio-1.15.0) results-definition.xml
replace the fio-2.0.0 results-definition.xml(/var/lib/phoronix-test-suite/test-profiles/pts/fio-2.0.0/results-definition.xml ),it's right.

**Comment by MShekow** [comment]
> I had unit trouble too and created a results-definition.xml I used with fio-2.0.0. I posted it here: [phoronix-test-suite/test-profiles#286 (comment)](https://github.com/phoronix-test-suite/test-profiles/issues/286#issuecomment-1828734721)

Thanks for pointing it out, I was not aware of that repository. Closing _this_ ticket, because the issue is already reported in the right place anyway.
