### ISSUE TITLE
mining benchmarks

### ISSUE THREAD

**Issue by skunk73** [phoronix-test-suite/phoronix-test-suite#78]
what about adding some cuda/opencl mining tests?
i think it would attract a lot of new visitors, especially in combination with performance/price and performance/watt features...
the tests could be based on:
https://github.com/sp-hash/ccminer for cuda
https://github.com/sgminer-dev/sgminer for opencl

**Comment by michaellarabel** [comment]
Can the tests all be automated well? Any example scripts to adapt for the test profile?

**Comment by skunk73** [comment]
well, i don't know how pts works as i've never used it, but i think so because both miners can be queried about performance data via websocket, as a fact i'm using ccminer's api data for switching algorithm and calculate profit with a bash script...
if all what you need to do is starting the miner in benchmark mode, read performance data via websocket or from stdout and kill it...
i'm not a dev but please don't hesitate to ask...

**Comment by michaellarabel** [comment]
If you can have a basic bash script to automatically run a miner test, exits, and outputs whatever performance result, from there I'm able to adapt it into a test profile.

**Comment by skunk73** [comment]
find below a script i use to get hashing rates on for different algorithms:

#!/bin/bash

# start "miner" screen session if it doesn't exist
if [ "$(screen -ls|grep miner)" == "" ]
then
        screen -dmS miner
fi

# algo ids (the first 9 must match with nicehash's api: https://nicehash.com/?p=api)
scrypt=0
sha256=1
nscrypt=2
x11=3
x13=4
keccak=5
x15=6
nist5=7
neoscrypt=8
lyra2=9
whirlpoolx=10
qubit=11
quark=12
axiom=13
lyra2v2=14
blake=15
skein=16
fresh=17
groestl=18

# in the following array keys must match with above ids
declare -a ALG=('scrypt' 'sha256' 'nscrypt' 'x11' 'x13' 'keccak' 'x15' 'nist5' 'neoscrypt' 'lyra2' 'whirlpoolx' 'qubit' 'quark' 'axiom' 'lyra2v2' 'blake' 'skein' 'fresh' 'groestl')

source profit_switcher.conf

STATUS=$(grep -v default  profit_switcher.status)
echo "$STATUS" > profit_switcher.status
for i in "${ALG[@]}"
do
        eval id=\${$i}
        if [ $id -gt 2 ]
        then
                screen -S miner -X screen schedtool -B $AFFINITY_GPU -e $CCMINER -a $i --benchmark -b 127.0.0.1:4068
                sleep 60
                eval $(nc 127.0.0.1 4068 <<< 'summary' 2>/dev/null|tr -d '|'|sed 's/(SP-MOD)//')
                eval $(nc 127.0.0.1 4068 <<< 'threads' 2>/dev/null|tr -d '|'|tr ' ' '-')
                killall -wq $(basename $CCMINER)
                echo "algo: $i, default intensity: $I, hash rate: $KHS"
                echo "INT_default[\$$i]=$I" >> profit_switcher.status
                echo "RATE_default[\$$i]=$KHS" >> profit_switcher.status
        else
                echo "INT_default[\$$i]=0" >> profit_switcher.status
                echo "RATE_default[\$$i]=0" >> profit_switcher.status
        fi
done

**Comment by mtippett** [comment]
We'd generally not want to encapsulate screen.

Parsing output is a given.

The concern is the coordination/multiple running instances on the same
host.  Killing by pid are not non-starters, but they make it a lot harder
to make it reliable and consistent.

That said, I'd suggest you start discussions on the github pages of the two
products you mentioned.    We have found historically that asking for a
mode that will execute pre-defined benchmarks and then exit are fairly well
received.  Particularly in that Michael occasionally does some heavy
lifting multi-device benchmarking on Phoronix.com when good and interesting
test profiles are available.  A lot of times it is a fairly small change to
do the automatic exit.

Both referenced projects are under active (or semi active) development, and
so their maintainers might be open to discussion.  Feel free to include
Michael and myself (both michael and matthew @phoronix.com) with the
maintainers to dig deeper.

Matthew

**Comment by steveoc64** [comment]
Another real-world benchmarking activity for opencl would be to do some photo processing using darktable.

This uses opencl for processing photos. There are command line options to generate profiling data, and a darktable-cli command to automate simple batch processing.

$ darktable -d perf

You can also run the process with opencl disabled, in which case darktable will use multiple CPU cores to perform the same image processing.

$ darktable -d perf --disable opencl

Slight problem with including this in the test suite is that some DNG  files (Digital Negative - raw image format) can be monstrously huge.  50-100 MB for a single image !  The user would have to supply their own files.

Some nice example large files here :
http://www.imaging-resource.com/PRODS/pentax-645z/pentax-645zGALLERY.HTM

And some other typical pro-photography happy snaps here : 
http://www.slack.co.uk/slack/Download.html

It would be a good real-world use case, because being able to work with a volume of large digital images is one of those 'time is money' tasks, that add some relevance to comparing the benefits of a range of video cards.

Is this worth a play with ?

**Comment by michaellarabel** [comment]
Darktable, Ethminer, and cpuminer-opt are among the test profiles that have been added since this thread was first opened. Are there any other new automated-friendly mining (or others, as in the case of Darktable) benchmarks I should be aware of?

**Comment by skunk73** [comment]
again, [ccminer](https://github.com/tpruvot/ccminer) is a very popular cuda miner supporting a lot of algorithms and now with --time-limit which stops the miner after a defined amount of seconds.
while for comparing nvidia and amd gpu's this [etherminer](https://github.com/ethereum-mining/ethminer) is more appropriate as it support both cuda and opencl.
another miner worth of consideration is [xmr-stak](https://github.com/fireice-uk/xmr-stak).

**Comment by h1z1** [comment]
@michaellarabel - Darktable fails to run with latest git pts, as does ethminer.

```
    system/darktable-1.0.1:
        Test Installation 1 of 1
        1 File Needed [59.52 MB / 1 Minute]
        Downloading: darktable-bench-assets-1.tar.bz2              [59.52MB]
        Estimated Download Time: 1m ........................................
        Installation Size: 100 MB
        Installing Test @ 02:47:16
            The installer exited with a non-zero exit status.
            ERROR: ERROR: Darktable is not found on the system! This test profile needs a working Darktable installation
            LOG: ~/.phoronix-test-suite/installed-tests/system/darktable-1.0.1/install-failed.log


```

**Comment by michaellarabel** [comment]
@h1z1 that's because you need to install them manually via your system's package manager if not on a platform where PTS can use a reverse-dependency solver to determine the package to grab.
