### ISSUE TITLE
Bash Completion = busted

### ISSUE THREAD

**Issue by bobwya** [phoronix-test-suite/phoronix-test-suite#79]
Hi Michael,

I was working on some "improved" Gentoo ebuilds to stick in my Overlay today... The in-tree Phoronix Test Suite package is a bit outdated - to say the least!!

Sorry, but you've failed the BASH basics class!!
http://www.tldp.org/LDP/abs/html/gotchas.html

Your bash_completion helper function contains invalid characters ('-') - it's probably never worked!!

Something like:
```
have phoronix-test-suite &&
_phoronix_test_suite_show()
{
        local cur

        COMPREPLY=()
        cur=${COMP_WORDS[COMP_CWORD]}
        COMPREPLY=($( compgen -W "$(phoronix-test-suite dump-possible-options)" -- "$cur" ))
}
complete -F _phoronix_test_suite_show phoronix-test-suite
```

Should be the ticket :-)

Bob

**Comment by michaellarabel** [comment]
Actually it did work when originally working on the bash compeltion, but may have gotten changed somehow along the line. Anyhow, the fix has now been merged. Thanks for reporting it!

**Comment by bobwya** [comment]
Hi Michael,

I know you've just closed this - but I also just noticed in the Portage build logs...
```
 * Problems with installed bash completions were found:
 * 
 *      phoronix-test-suite: 'have' command is deprecated and must not be used.
```
Refer to (3):
https://wiki.gentoo.org/wiki/Bash/Installing_completion_files

Which obviously more esoteric (i.e. bash completions will continue to work)... Possibly not worth fixing? Perhaps I'm being too pedantic now... :-)

Bob
