### ISSUE TITLE
CC environment variable is ignored if cc is not in path

### ISSUE THREAD

**Issue by ptzafrir** [phoronix-test-suite/phoronix-test-suite#80]
Relying on CC environment variable to detect current compiler is broken when creating new tests.

If cc is not found in path, PTS overwrite CC environment variable with gcc, thus disabling the option to use the chosen compiler in test scripts.
this is done in pts_client at the end of environmental_variables() function

**Comment by michaellarabel** [comment]
If CC is set, PTS should respect it and as part of its 'compiler mask' set cc/gcc links to point to whatever is specified by CC environment variable, regardless of whether there is a 'cc' link/binary on the system. 

What version of PTS are you trying with?

If you still run into problem, can you provide more detailed steps to reproduce for your issue? Thanks!

**Comment by ptzafrir** [comment]
I'm using version 5.8.0

See below an example install.sh script for a local PTS test to reproduce the issue
```
#hide cc binary file - change this line if this is not the only cc in the PATH
sudo mv /usr/bin/cc /usr/bin/cc.bak
echo "#!/bin/sh
echo install time CC is ${CC}
echo \"found at:\"
which ${CC}
echo run time CC is \${CC}
echo \"found at:\"
which \${CC}
" > test-cc
chmod +x test-cc
```
I get the following output when running this test
```
install time CC is clang
found at:
/home/tzafrir/bin/clang
run time CC is gcc
found at:
/usr/lib/ccache/gcc
```

From pts_client.php, this is the code which I suspect responsible for this,

```
if(!pts_client::executable_in_path('cc') && pts_client::executable_in_path('gcc'))
{
	// This helps some test profiles build correctly if they don't do a cc check internally
	$env_variables['CC'] = 'gcc';
}
```

**Comment by michaellarabel** [comment]
Ah, okay, within the pts_client is what you were referring to rather than the installation mask portion. Does https://github.com/phoronix-test-suite/phoronix-test-suite/commit/f80adcb8a0e2b7aa52360d67891b8c2f93765141 handle your needs now as desired? It should be fine and was likely just an oversight there of not checking the CC environment variable there.

**Comment by ptzafrir** [comment]
Yes, This fixed the issue. Thanks
