### ISSUE TITLE
Multiple GPUs (Enabled embedded and Discrete) not in detailed-system-info

### ISSUE THREAD

**Issue by Min1123** [phoronix-test-suite/phoronix-test-suite#89]
When a system has multiple GPUs, one is chosen and the other ignored. The other GPU in this system is a discrete Radeon HD 270X with 2GB of GDDR5. As below:

[min@delta ~]$ phoronix-test-suite detailed-system-info

Phoronix Test Suite v5.8.0
System Information

Hardware:
Processor: AMD A10-7800 Radeon R7 12 Compute Cores 4C+8G @ 3.50GHz (4 Cores), Motherboard: ASRock FM2A88M-HD+, Chipset: AMD Family 15h, Memory: 15360MB, Disk: 1000GB SAMSUNG HD103SJ + 480GB OCZ ARC100, Graphics: AMD Radeon R7 1024MB, Audio: Realtek ALC662 rev1, Network: Realtek RTL8111/8168/8411

Software:
OS: Fedora 22, Kernel: 4.1.7-200.fc22.x86_64 (x86_64), Desktop: GNOME Shell 3.16.3, OpenGL: 4.1 Mesa 11.1.0-devel Gallium 0.4, Compiler: GCC 5.1.1 20150618, File-System: btrfs, Screen Resolution: 1920x1080

PROCESSOR:

Core Count: 2
Thread Count: 4
Cache Size: 2048 KB
Instruction Set Extensions: SSE 4.2 + AVX + XOP + FMA4 + FSGSBASE
AES Encryption: YES
Energy Performance Bias: NO
Virtualization: AMD-V
Compiler Configuration: --build=x86_64-redhat-linux --disable-libgcj --disable-libunwind-exceptions --enable-__cxa_atexit --enable-bootstrap --enable-checking=release --enable-gnu-indirect-function --enable-gnu-unique-object --enable-initfini-array --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --enable-libmpx --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --mandir=/usr/share/man --with-arch_32=i686 --with-default-libstdcxx-abi=c++98 --with-isl --with-linker-hash-style=gnu --with-tune=generic
Disk Scheduler: CFQ
Disk Mount Options: relatime,rw,seclabel,space_cache,ssd
Cpu Scaling Governor: acpi-cpufreq ondemand

(below truncated for brevity)
[min@delta ~]$ sudo lspci -vkn
00:01.0 0300: 1002:130f (prog-if 00 [VGA controller])
    Subsystem: 1849:130f
    Flags: bus master, fast devsel, latency 0, IRQ 46
    Memory at b0000000 (64-bit, prefetchable) [size=256M]
    Memory at d0000000 (64-bit, prefetchable) [size=8M]
    I/O ports at f000 [size=256]
    Memory at ff700000 (32-bit, non-prefetchable) [size=256K]
    Expansion ROM at ff740000 [disabled] [size=128K]
    Capabilities: [48] Vendor Specific Information: Len=08 <?>
    Capabilities: [50] Power Management version 3
    Capabilities: [58] Express Root Complex Integrated Endpoint, MSI 00
    Capabilities: [a0] MSI: Enable+ Count=1/1 Maskable- 64bit+
    Capabilities: [100] Vendor Specific Information: ID=0001 Rev=1 Len=010 <?>
    Capabilities: [270] #19
    Capabilities: [2b0] Address Translation Service (ATS)
    Capabilities: [2c0] #13
    Capabilities: [2d0] #1b
    Kernel driver in use: radeon
    Kernel modules: radeon

. . .

01:00.0 0300: 1002:6810 (prog-if 00 [VGA controller])
    Subsystem: 1682:9275
    Flags: bus master, fast devsel, latency 0, IRQ 47
    Memory at c0000000 (64-bit, prefetchable) [size=256M]
    Memory at ff600000 (64-bit, non-prefetchable) [size=256K]
    I/O ports at e000 [size=256]
    Expansion ROM at ff640000 [disabled] [size=128K]
    Capabilities: [48] Vendor Specific Information: Len=08 <?>
    Capabilities: [50] Power Management version 3
    Capabilities: [58] Express Legacy Endpoint, MSI 00
    Capabilities: [a0] MSI: Enable+ Count=1/1 Maskable- 64bit+
    Capabilities: [100] Vendor Specific Information: ID=0001 Rev=1 Len=010 <?>
    Capabilities: [150] Advanced Error Reporting
    Capabilities: [270] #19
    Capabilities: [2b0] Address Translation Service (ATS)
    Capabilities: [2c0] #13
    Capabilities: [2d0] #1b
    Kernel driver in use: radeon
    Kernel modules: radeon

---

Both GPUs are enabled for purposes of having the MESA drivers and testing against the OpenCL support from Clover. (Using Griever's COPR repo)

[min@delta ~]$ clinfo
Number of platforms                               1
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 MESA 11.1.0-devel
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   Clover
Number of devices                                 2
  Device Name                                     AMD KAVERI (DRM 2.42.0, LLVM 3.7.0)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 MESA 11.1.0-devel
  Driver Version                                  11.1.0-devel
  Device OpenCL C Version                         OpenCL C 1.1 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               8
  Max clock frequency                             720MHz
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              64
  Preferred / native vector sizes  
    char                                                16 / 16  
    short                                                8 / 8  
    int                                                  4 / 4  
    long                                                 2 / 2  
    half                                                 0 / 0        (n/a)
    float                                                4 / 4  
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    32, Little-Endian
  Global memory size                              1073741824 (1024MiB)
  Error Correction support                        No
  Max memory allocation                           268435456 (256MiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        None
  Image support                                   No
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        268435456 (256MiB)
  Max number of constant args                     16
  Max size of kernel argument                     1024
  Queue properties  
    Out-of-order execution                        No
    Profiling                                     Yes
  Profiling timer resolution                      0ns
  Execution capabilities  
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  Device Available                                Yes
  Compiler Available                              Yes
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_fp64

  Device Name                                     AMD PITCAIRN (DRM 2.42.0, LLVM 3.7.0)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 MESA 11.1.0-devel
  Driver Version                                  11.1.0-devel
  Device OpenCL C Version                         OpenCL C 1.1 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               20
  Max clock frequency                             1050MHz
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              64
  Preferred / native vector sizes  
    char                                                16 / 16  
    short                                                8 / 8  
    int                                                  4 / 4  
    long                                                 2 / 2  
    half                                                 0 / 0        (n/a)
    float                                                4 / 4  
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    32, Little-Endian
  Global memory size                              1073741824 (1024MiB)
  Error Correction support                        No
  Max memory allocation                           268435456 (256MiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        None
  Image support                                   No
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        268435456 (256MiB)
  Max number of constant args                     16
  Max size of kernel argument                     1024
  Queue properties  
    Out-of-order execution                        No
    Profiling                                     Yes
  Profiling timer resolution                      0ns
  Execution capabilities  
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  Device Available                                Yes
  Compiler Available                              Yes
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_fp64

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Clover
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [MESA]
  clCreateContext(NULL, ...) [default]            Success [MESA]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (2)
    Platform Name                                 Clover
    Device Name                                   AMD KAVERI (DRM 2.42.0, LLVM 3.7.0)
    Device Name                                   AMD PITCAIRN (DRM 2.42.0, LLVM 3.7.0)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (2)
    Platform Name                                 Clover
    Device Name                                   AMD KAVERI (DRM 2.42.0, LLVM 3.7.0)
    Device Name                                   AMD PITCAIRN (DRM 2.42.0, LLVM 3.7.0)

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.3
  ICD loader Profile                              OpenCL 1.2
[min@delta ~]$

**Comment by michaellarabel** [comment]
The system-info view was reworked in an older PTS 7.x release and ongoing tweaks should provide better multi-GPU reporting, but there will always be shortcomings in some areas for how to concisely display all of the information when the driver stacks differ, etc. On newer PTS releases if any specific requests for improvement, feel free to let us know.
