### ISSUE TITLE
openarena-0.8.8.zip download locations (moved)

### ISSUE THREAD

**Issue by bobwya** [phoronix-test-suite/phoronix-test-suite#90]
Hi Michael,

The mirrors for OpenArena appear to have moved to...
http://distcache.freebsd.org/ports-distfiles/openarena-0.8.8.zip
http://sourceforge.net/projects/oarena/files/openarena-0.8.8.zip/download

Tested and working if I download openarena-0.8.8.zip, with wget, into the Phoronix Test Suite cache.

Robert

**Comment by michaellarabel** [comment]
Thanks for the notice. Download links now updated in pts/openarena-1.5.3.
