### ISSUE TITLE
csv report contains wrong data

### ISSUE THREAD

**Issue by ptzafrir** [phoronix-test-suite/phoronix-test-suite#91]
Consider the following scenario:
1. gcc is used to run test A
2. clang is used to run Test A and Test B

The web report and the pdf reports are fine.
But using result-file-to-csv command, the csv looks like:

```
, gcc, clang
TestA, 1.00, 2.00
TestB, 3.00
```

Making the wrong impression that gcc finished testB, while actually this configuration wasn't tested.
The same problem could also happen if there was an error running gcc on the test.

For csv report **missing information should be noted**.
The expected output for this case would then be:
```
, gcc, clang
TestA, 1.00, 2.00
TestB, , 3.00
```

**Comment by michaellarabel** [comment]
Commit https://github.com/phoronix-test-suite/phoronix-test-suite/commit/20593608791d6e0011220a43f18858150de937f4 should fix this bug by properly handling CSV output when there are missing/incomplete results, it should be properly separated to maintain proper column association. Let me know if you run into any other issues or encounter any other corner cases where the CSV formatting isn't ideal.

**Comment by ptzafrir** [comment]
Thanks! This fixed the issue
