### ISSUE TITLE
Slow startup time caused by network latencies

### ISSUE THREAD

**Issue by ghost** [phoronix-test-suite/phoronix-test-suite#93]
Executing `$ 'time' ./phoronix-test-suite` takes 0.85 (or more) seconds on my machine. This is too long.

```
0.187user 0.082system 0:00.852elapsed 31%CPU (0avgtext+0avgdata 41512maxresident)k
```

This seems to be caused by network connection latencies. PTS is contacting haswell.phoronix.com which has 145ms ping time:

```
$ ping haswell.phoronix.com
PING haswell.phoronix.com (69.46.29.26) 56(84) bytes of data.
64 bytes from haswell.phoronix.com (69.46.29.26): icmp_seq=1 ttl=42 time=145 ms
64 bytes from haswell.phoronix.com (69.46.29.26): icmp_seq=2 ttl=42 time=145 ms
^C
```

Please reduce the startup time of PTS by improving the networking performance.

**Comment by michaellarabel** [comment]
Unfortunately we're limited right now by our server infrastructure. There's plans to add more servers to fix this situation, but right now tight funds for that are blocking this from happening.

**Comment by atom-symbol** [comment]
Ok. I thought it is mostly a matter of software optimization.

**Comment by ptzafrir** [comment]
Is it possible to run in offline mode, while still allowing download of files from downloads.xml?

**Comment by michaellarabel** [comment]
The current options are exposed in the ~/.phoronix-test-suite/user-config.xml. The only way to download files while being in offline mode would be to setup a PTS download cache.

**Comment by ptzafrir** [comment]
Michael, I've seen those options, and disabled the network. And am also using the download cache option. But when I want to write a new test, I need to re-enable network support, download the files for the first time, cache them, and disable that option again. Since I'm running PTS on several computers, this manual process needs to be repeated for each one, for each new test.

**Comment by michaellarabel** [comment]
@ptzafrir while not the main aim of the Phoromatic Server, it does have a built-in download cache server as another alternative for easily distributing files to PTS systems across your network, if you keep your Phoromatic Server with an open Internet connection or just manually download the files to that lone system.
