### ISSUE TITLE
log output of pre.sh

### ISSUE THREAD

**Issue by ptzafrir** [phoronix-test-suite/phoronix-test-suite#95]
What is the best way to display the output of pre.sh script?

**Comment by michaellarabel** [comment]
At the moment I don't have that log stored anywhere. What is your use case / issue for needing it? If you can elaborate on what you're after, I should be able to support it.

**Comment by ptzafrir** [comment]
There are two use cases,

1. During creation of test script, the test fails. It turns out there was a problem with unzip/configure commands, but what fails is the test itself. I would like to get that output to know where to look for. currently I'm guessing the problem is from the pre script, manually set the folders, and run the commands to track the problem.

2. I'm using PTS to test a compiler against several open source projects. In my pre.sh script I run the configure script of the project. I would like to see this output and track it regularly for any red flags.

**Comment by michaellarabel** [comment]
Have you tried looking at the output when running: phoronix-test-suite debug-run <your test>. Off hand I don't remember if debug-run prints the pre.sh output, but I think it does. Otherwise I can make it there or if preferred just as easily dump it into the directory as say pre.log.

**Comment by ptzafrir** [comment]
I have overlooked the debug-run, and it indeed address the need for the first use case. However for the second, debug-run does not save the results. I think (always) dumping the output to pre.log will be the best solution.
