### ISSUE TITLE
Phoronix tries to download from webkikr.com

### ISSUE THREAD

**Issue by hickford** [phoronix-test-suite/phoronix-test-suite#96]
On Windows:

```
>phoronix-test-suite.bat install pts/cpu

1 Test To Install
    1 File To Download [0.29MB]
    6MB Of Disk Space Is Needed

pts/crafty-1.3.0:
    Test Installation 1 of 1
    1 File Needed [0.29 MB / 1 Minute]
    Downloading: crafty-23.4-win64.exe.zip                      [0.29MB]
        Download Failed: http://www.webkikr.com/files/crafty-23.4-win64.exe.zip
        Downloading of needed test files failed.
```

That URL http://www.webkikr.com/files/crafty-23.4-win64.exe.zip looks dodgy to me. What's going on?

**Comment by hickford** [comment]
<?xml version="1.0"?>
    
    <PhoronixTestSuite>
      <Downloads>
        <Package>
          <URL>http://www.craftychess.com/crafty-23.4.zip, http://fossies.org/unix/privat/crafty-23.4.zip, http://freebsd.ntu.edu.tw/FreeBSD/distfiles/crafty/crafty-23.4.zip</URL>
          <MD5>7e0811dd2d801428d8da48a4e487885a</MD5>
          <FileName>crafty-23.4.zip</FileName>
          <FileSize>426295</FileSize>
          <PlatformSpecific>Linux, Solaris, BSD, MacOSX</PlatformSpecific>
        </Package>
        <Package>
          <URL>http://www.webkikr.com/files/crafty-23.4-win64.exe.zip</URL>
          <MD5>081bb376050fba43e4df3d2ef3ae94a5</MD5>
          <FileName>crafty-23.4-win64.exe.zip</FileName>
          <FileSize>299923</FileSize>
          <PlatformSpecific>Windows</PlatformSpecific>
        </Package>
      </Downloads>
    </PhoronixTestSuite>

**Comment by michaellarabel** [comment]
It was just in search for a Crafty mirror of the Windows binary. Can see if there are any other mirrors still available.

**Comment by airvzxf** [comment]
Other solution in Linux is replace the URL
http://www.craftychess.com/crafty-23.4.zip
to
http://www.craftychess.com/downloads/source/crafty-23.4.zip

And the file size, MD5 and SHA256 sums.

crafty-1.3.0:
```XML
<?xml version="1.0"?>
<!--Phoronix Test Suite v3.8.0m1 (Bygland)-->
<PhoronixTestSuite>
  <Downloads>
    <Package>
      <URL>http://www.craftychess.com/downloads/source/crafty-23.4.zip</URL>
      <MD5>a6dec14d636d9f50a7e93ea9ada723a0</MD5>
      <FileName>crafty-23.4.zip</FileName>
      <FileSize>427044</FileSize>
      <PlatformSpecific>Linux, Solaris, BSD, MacOSX</PlatformSpecific>
    </Package>
    <Package>
      <URL>http://www.webkikr.com/files/crafty-23.4-win64.exe.zip</URL>
      <MD5>081bb376050fba43e4df3d2ef3ae94a5</MD5>
      <FileName>crafty-23.4-win64.exe.zip</FileName>
      <FileSize>299923</FileSize>
      <PlatformSpecific>Windows</PlatformSpecific>
    </Package>
  </Downloads>
</PhoronixTestSuite>
```

crafty-1.3.1:
```XML
<?xml version="1.0"?>
<!--Phoronix Test Suite v6.6.0m2-->
<PhoronixTestSuite>
  <Downloads>
    <Package>
      <URL>http://www.craftychess.com/downloads/source/crafty-23.4.zip</URL>
      <MD5>a6dec14d636d9f50a7e93ea9ada723a0</MD5>
      <SHA256>87a22362c804bead6130839a2c3dc2041885ce010578e72527d617bae088da3c</SHA256>
      <FileSize>427044</FileSize>
      <PlatformSpecific>Linux, Solaris, BSD, MacOSX</PlatformSpecific>
    </Package>
    <Package>
      <URL>http://www.webkikr.com/files/crafty-23.4-win64.exe.zip</URL>
      <MD5>081bb376050fba43e4df3d2ef3ae94a5</MD5>
      <FileSize>299923</FileSize>
      <PlatformSpecific>Windows</PlatformSpecific>
    </Package>
  </Downloads>
</PhoronixTestSuite>
```

**Comment by michaellarabel** [comment]
Looks like I forgot to close this issue after previously updating the mirror list, but anyhow, Crafty was just updated again to its latest upstream release and in the process also new mirrors.
